### ISSUE TITLE
github.io全挂

### ISSUE THREAD

**Issue by hipboi** [cubieplayer/Cubian#1]
github.io的链接全挂，修复一下吧。

**Comment by cubieplayer** [comment]
嗯，昨天改了个名字，改成了从cubino-base改成了cubian，更喜欢cubian这个名字，cubieboard+debian，原来那个名字有点儿不够贴切，而且太长，下狠心就改掉了。原链接没法修复了，但我已经更新了所有的文档和帖子，包括截图等，都使用这个新名字替换掉了。
