### ISSUE TITLE
firmware update command to provide the equivalent of rpi-update

### ISSUE THREAD

**Issue by throwcomputer** [cubieplayer/Cubian#10]
It would be nice to have a firmware update command similar to https://github.com/Hexxeh/rpi-update

which would pull from the linux-sunxi repo.

**Comment by cubieplayer** [comment]
Hi, I will make something like this to update firmware,drivers online. Thanks for sharing.

**Comment by cubieplayer** [comment]
Hi, The update tool is released. http://cubian.org/2013/08/09/cubian-update-is-available/

**Comment by ghost** [comment]
after the last update showing me this:

cubie@Cubian:~$ sudo cubian-update
**\* Checking updates from server
**\* Downloading updates (this may take a while)
Unknown option: -q
Usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
[-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
[--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
[-c name=value] [--help]
<command> [<args>]</args></name></path></path></path>
...

**Comment by cubieplayer** [comment]
What's the output of cubian-update -v?

**Comment by ghost** [comment]
cubie@Cubian:~$ sudo cubian-update -v
Update From: https://github.com/cubieplayer/cubian-update.git
Root Path: /
Update Kernel: yes
Update Modules: yes
Branch:
SysInstallType: mmc
**\* Checking updates from server
Checking updates from server https://github.com/cubieplayer/cubian-update.git
Remote revision: a20-3.4.43_1
Local revision: a33f68007c1dd205f3b5a5f55669405adebd1aba
**\* Downloading updates (this may take a while)
clean up repository
From https://github.com/cubieplayer/cubian-firmware
 = [up to date]      a10        -> origin/a10
 = [up to date]      a20        -> origin/a20
Already up-to-date.
**\* Updating firmware
As requested using tag a20-3.4.43_1 from local repository
clean up repository
error: pathspec 'tags/a20-3.4.43_1' did not match any file(s) known to git.

**Comment by cubieplayer** [comment]
run **cubian-update -cv**, then run **cubian-update** again.

**Comment by cubieplayer** [comment]
Thank for report this bug, i will fix it quickly

**Comment by ghost** [comment]
oh now i've got this:
cubie@Cubian:~$ sudo cubian-update
**\* Downloading firmware (this may take a while)
!!! Failed to download firmware,Please check internet connection
cubie@Cubian:~$ sudo cubian-update -v
Update From: https://github.com/cubieplayer/cubian-update.git
Root Path: /
Update Kernel: yes
Update Modules: yes
Branch:
SysInstallType: mmc
**\* Downloading firmware (this may take a while)
error: option `branch' requires a value
usage: git clone [options] [--] <repo> [<dir>]

!!! Failed to download firmware,Please check internet connection
 now i reinstall cubian-update

**Comment by cubieplayer** [comment]
Sry, I mistyped A10 to A1O, This caused an error. I've update to version 1.0-4, you may update to newest version by executing

> apt-get install cubian-update

If you have any problems, please let me know, Thanks.
