### ISSUE TITLE
SATA not working on r5?

### ISSUE THREAD

**Issue by supermarioprof** [cubieplayer/Cubian#100]
I'm not able to have SATA working with r5.
I dd to SD, then lsmod but nothing about SATA is showed, while /etc/modules contains SATA modules.
So what?

**Comment by cubieplayer** [comment]
Sry, I just fixed the problem. The problem only happens on A10 which is caused by a wrong configuration of script.bin https://github.com/mmplayer/sunxi-boards/commit/7bb2feaaf6257eee80d7896c095482ec01952ad8

**Comment by cubieplayer** [comment]
Forget to mention how to solve it

> apt-get install cubian-update
> cubian-update

should do the trick

**Comment by s-kostyuk** [comment]
Many thanks :)

**Comment by hawk0107** [comment]
Hi all, Today (September14th) the fixed script.bin will not be downloaded by the cubian-update. the version is from September 4th. But the fix from September 9th. I fixed it by modifing the script.fex file on /boot (https://github.com/mmplayer/sunxi-boards/commit/7bb2feaaf6257eee80d7896c095482ec01952ad8) and with that created the modified script.bin with fex2bin (https://www.olimex.com/forum/index.php?topic=184.0). 

@cubieplayer 
thank you very much for your great work on cubian. 
You only need to check why there is no new script.bin downloaded by cubian-update

**Comment by cubieplayer** [comment]
@hawk0107 Hi, the script.bin is not updated because you needs to update the cubian-update itself to newer version. For current is v1.1.1

> apt-get update
> apt-get install cubian-update

**Comment by hawk0107** [comment]
Hi cubieplayer, 

apt-get install cubian-update tells me:
cubian-update is already the newest version.

I checked the cubian-update script. I already had Version 1.1.1

But when i started cubian-update again it updated the script.bin today. And the sata hdd works with the script.bin from the server. :-)

I do not know why it didn´t work in the first place. But more important is, that it works now. 
Thank you for this updater.

**Comment by cubieplayer** [comment]
You need to use the following command to update the script.bin.

> cubian-update --update-board-cfg

If there is no updates for you, you needs to run

> cubian-update --update-board-cfg --reinstall
