### ISSUE TITLE
Slow downloads → add BitTorrent

### ISSUE THREAD

**Issue by xHire** [cubieplayer/Cubian#104]
Download links are very slow. I looked for bittorrent files, but didn't found any. So after downloading both images, I created them:
http://uploaduji.mujmalysvet.cz/Cubian-base-r5-arm-a10.img.7z.torrent
http://uploaduji.mujmalysvet.cz/Cubian-base-r2-arm-a20.img.7z.torrent

Magnet URLs:

```
magnet:?xt=urn:btih:f9a6a87ad1e7e9ed3c5336f3374dca503d0242fa&dn=Cubian-base-r5-arm-a10.img.7z&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.istole.it%3A80
magnet:?xt=urn:btih:c64db2077c3d9fb723409d74fe2a41e60af9e92e&dn=Cubian-base-r2-arm-a20.img.7z&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.istole.it%3A80
```

It would be very helpful to add them to the website (copy there magnet URLs or upload my torrent files, please try not to link to my server :-)) so that everyone immediately sees BitTorrent as another method for downloading. Checksums would be great too. And for next releases as well. Thank you!

**Comment by cubieplayer** [comment]
Nice work

**Comment by najlepsiwebdesigner** [comment]
Hi, 

I uploaded latest Cubieboard2 version to my personal website and I offer it for download, because download speeds from mirrors provided are really slow (at least here in Europe). 
Here is the link:

http://peterbeno.com/Cubian-base-r4-arm-a20.img.7z

Thank you all for great job!

**Comment by vtlonn** [comment]
Added Cubian-base-r4-arm-a20.img.7z as a torrent also:

<code>
magnet:?xt=urn:btih:CAF2B2A7D31D429E6DAB7235C2E2F6471286A196&dn=Cubian-base-r4-arm-a20.img.7z&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%2ftracker.publicbt.com%3a80%2fannounce&tr=udp%3a%2f%2fopen.demonii.com%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.istole.it%3a80</code>

**Comment by freespace** [comment]
For sake of security, can the the cubie player team post sha256 hashes of the two 7z files, so we can verify the integrity of the mirrors?

_edit_ In the mean time, I finally got Cubian-base-r4-arm-a20.img.7z from the offical link, and its sha256 hash is `64155541915a29ea538301c3dc48e646dcaa4b265004bbc1e753a250c984bc78`.

**Comment by cubieplayer** [comment]
Thanks, the newer version will publish through torrent to save my money on hosting XD.
