### ISSUE TITLE
allow-hotplug and auto eth0 enabled

### ISSUE THREAD

**Issue by derekdhaas** [cubieplayer/Cubian#107]
In /etc/network/interfaces, both auto eth0 and allow-hotplug eth0 are enabled. In my point of view this is a choise, eighter set it to auto or set it to allow-hotplug. You might want to comment one out.

The first line might be overruled by the second line, but you might want to fix it by default.

Documentation:
http://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_gui_network_configuration_tools

**Comment by cubieplayer** [comment]
Ok, I think your are correct

**Comment by cubieplayer** [comment]
This bug has been solved on the new release http://cubian.org/2013/11/08/cubian-r6-for-a10-and-r3-for-a20-released/
