### ISSUE TITLE
Lower default clockrate

### ISSUE THREAD

**Issue by 346L3** [cubieplayer/Cubian#109]
Please lower the default CPU clock. As far as I understand the values under /sys, cubian overclocks the Allwinner A10 (can't speak for A20) to 1.2GHz instead of the default 1.0GHz. This lead to some serious issues for me like failures while compiling the kernel (but at diferent stages), cubian-update failing when it fetches files over git, crashes etc... I currently fixed it by writing 1GHz to scaling_max_frequency in /etc/rc.local...
Maybe some A10 can handle this clockrate at default CPU voltage, but apparantly not all, so it shouldn't be Cubian's default in my opinion.
(Might as well be the cause of some user problems like the file corruption when uploading over network, freezes...?)
Thanks!

**Comment by cubieplayer** [comment]
@346L3 You are right, Thanks for sharing, I will fix it.

**Comment by cubieplayer** [comment]
Fixed on https://github.com/mmplayer/fsupdate/commit/63887f743d4b0341abdbaedcfeec53de354711a1

**Comment by s-kostyuk** [comment]
I see it solves problems like https://github.com/cubieplayer/Cubian/issues/70 and https://github.com/cubieplayer/Cubian/issues/74 as well, right?
