### ISSUE TITLE
Unable to activite the GPIO ports

### ISSUE THREAD

**Issue by patersigmund** [cubieplayer/Cubian#110]
Ahoi!

I have installed Cubian into the NAND drive. But i can't activate the GPIO ports like it is described in the tutorial.

If I type the command

echo 17 > /sys/class/gpio/export

in the terminal, I get the message

-bash: echo: write error: Invalid argument

Maybe someone have an idea what i did wrong.

Greetings,
    me

**Comment by chuprex** [comment]
A10 or A20???

**Comment by patersigmund** [comment]
Oh sorry. It is the A10 version.

**Comment by sbstjn** [comment]
Make sure everything is updated and you have loaded the needed kernel module. Edit `/etc/modules` for autoload…

```
root@Cubian:/home/cubie# echo 17 > /sys/class/gpio/export
bash: echo: write error: Invalid argument
```

## 

```
root@Cubian:/home/cubie# cubian-update
*** Performing self-update
*** Cubian updater v1.1.1 http://cubian.org
*** Checking updates from server
*** Your firmware is up to date
```

## 

```
root@Cubian:/home/cubie# bin2fex /boot/script.bin script.fex
root@Cubian:/home/cubie# cat script.fex | grep gpio_pin_17
gpio_pin_17 = port:PG09<1><default><default><1>
```

## 

```
root@Cubian:/home/cubie# modprobe gpio-sunxi
```

## 

```
root@Cubian:/home/cubie# echo 17 > /sys/class/gpio/export
```

**Comment by patersigmund** [comment]
Ah ok, didn't know that I have to activate the sunxi module.
Now it works... at least I got no error ^^
Thanks!
