### ISSUE TITLE
Missing driver for DM9601

### ISSUE THREAD

**Issue by abhaymin** [cubieplayer/Cubian#111]
Hi,

It seem the kernel compiled modules is missing driver for DM9601 or USBNet?

Could a module driver be pre-compile to be consumed under 3.4.43+, so that these usb-ethernet cards be supported as well.

Thanks in Advance

Abhay.

**Comment by abhaymin** [comment]
Hi,

additional the driver code is present in the source code link that provide in the issue log before

https://github.com/mmplayer/linux-sunxi/blob/stage/sunxi-3.4-a10/drivers/net/usb/dm9601.c

Thanks,

Abhay.

Ps. The current kernel for A10 does also works well with pcDuino boards as well which is A10 allwinner (w 1GB RAM) as well.

**Comment by abhaymin** [comment]
Is there any chance by which I can get the compile modules for DM9601.ko and usbnet.ko for Linux Kernel 3.4.43+???

**Comment by cubieplayer** [comment]
Hi, These modules are compiled now, you can try `cubian-update` to get it, Please re-open the issue if it's not working.
