### ISSUE TITLE
Crashes when trying to apt-get install samba

### ISSUE THREAD

**Issue by SubZane** [cubieplayer/Cubian#113]
I installed cubian on NAND then did the update, then I did apt-get install samaba and it started out fine, then suddenly the screen was filled with HEX data scrolling continuously. Unable to stop it I let it run for 10 minutes, then I pulled the plug, now the installtion is corrupt and I have to do it all again.

The same thing then happened when I tried to install midnight commander

I was wondering if this is because cubian isn't compatible with debian? And if so, how can I know what I can apt-get install? it's like russian roulette :P

**Comment by danielnilsson9** [comment]
Hi

Had this problem too but found another issue here which offered a solution. Not sure what it does really but after doing this my cubian is 100% stable, never had a single crash after this. 

Here is the thread: https://github.com/cubieplayer/Cubian/issues/57

And here is what I did:
sudo -i
update-rc.d cpufrequtils disable
update-rc.d cubian-ondemandcpufreq disable
reboot

**Comment by danielnilsson9** [comment]
Actually its probably related to this issue: https://github.com/cubieplayer/Cubian/issues/109 

 I just found this issue now and tried the fix and it seems to be working!

**Comment by cubieplayer** [comment]
Marked as duplicated with https://github.com/cubieplayer/Cubian/issues/109

**Comment by cubieplayer** [comment]
Hi, Please take a look at http://cubian.org/2013/09/18/fix-random-crash/, does it help?

**Comment by SubZane** [comment]
Actually this https://github.com/mmplayer/fsupdate/commit/63887f743d4b0341abdbaedcfeec53de354711a1 helped :)

**Comment by michalliu** [comment]
Follow the instructions on http://cubian.org/2013/09/18/fix-random-crash should sove the problem
