### ISSUE TITLE
cubieboard 2 fails to boot from nand in 50% of the cases

### ISSUE THREAD

**Issue by klankschap** [cubieplayer/Cubian#115]
AFter flashing the nand using cubian-nandinstall in half of the cases the cubieboard2 fails to boot from the hand. It just sits there and wait.
Re-insterting the SD card will bring the device up.

A workaround is to first flash another image (e.g lubuntu.img) using liveSuit
Then reboot using SD and cubian-nandinstll

How to proceed?
Any hints?

**Comment by mishoboss** [comment]
Same here!

**Comment by klankschap** [comment]
reducing the clockspeed from 1.2MHz to 1MHZ did not help

**Comment by 346L3** [comment]
Did you remove the SD-Card when trying this? If the cubieboard finds a bootable SD-Card, it will try this first.

**Comment by klankschap** [comment]
Of course :-)
It is after removing the SD and booting from the nand that the system will hang.
Unless you have flashed the nand before cubian_nandinstall with the liveSuit app.
Then it will boot as intended.

**Comment by mishoboss** [comment]
Any workaround except PhoenixSuit NAND install another image before execute cubian_nandinstall? For some reason I can't enter into FEL mode. So, for now I'm stuck with cubian, living on the SD card :(

**Comment by klankschap** [comment]
just checking, i guess you did it already:
disconnect the CB2.
laucnh livesuit app, choose the image file.
connect usb cable to computer, press the FEL button on the CB2 and while pressed insert the usb cable in the CB2.
release all buttons. a question will pop-up to confirm the erasure of the hand. Choose yes and the transfer to hand will automatically start. (takes about ten minutes)

**Comment by mishoboss** [comment]
Hi, klankschap. I used PhoenixSuit, not LiveSuit, as this is the suggested flash tool for A20 (at least this is what I read in the download page). Everything else I did as you describe, but PhoenixSuit doesn't see my cubie.

**Comment by klankschap** [comment]
you could try liveSuit
it works here on mac

**Comment by mishoboss** [comment]
I just tried with LiveSuit v1.11. I get "initialization fails (513)" when I try to boot in FEL.

**Comment by michalliu** [comment]
I guess this problem related to the CPU overlocking, http://cubian.org/2013/09/18/fix-random-crash

**Comment by michalliu** [comment]
Follow the instructions on http://cubian.org/2013/09/18/fix-random-crash should sove the problem
