### ISSUE TITLE
自己编译的驱动为什么不能加载？

### ISSUE THREAD

**Issue by lanzf** [cubieplayer/Cubian#118]
自己编译了sunxi-ir的驱动，相关信息如下：
其中sunxi-ir.ko不能加载，系统自带的hv2605.ko就可以成功加载，驱动信息如下
root@Cubian:/lib/modules/3.4.43+/kernel/drivers/input/keyboard# modinfo sunxi-ir.ko 
filename:       /lib/modules/3.4.43+/kernel/drivers/input/keyboard/sunxi-ir.ko
license:        GPL
author:         DanielWang
description:    Remote IR driver
srcversion:     E910E8252AA04A39879D6DB
depends:  
vermagic:       3.4.43+ SMP preempt mod_unload modversions ARMv7 p2v8 

root@Cubian:/lib/modules/3.4.43+/kernel/drivers/input/keyboard# modinfo hv2605.ko 
filename:       /lib/modules/3.4.43+/kernel/drivers/input/keyboard/hv2605.ko
license:        GPL
description:    hv keypad driver
author:         zhengdixu@allwinnertech.com
srcversion:     72B380B93CCEE12867DAD12
alias:          i2c:hv_keypad
depends:  
intree:         Y
vermagic:       3.4.43+ SMP preempt mod_unload modversions ARMv7 p2v8 
root@Cubian:/lib/modules/3.4.43+/kernel/drivers/input/keyboard#
复制代码
版本信息什么都是一样的，为什么sunxi-ir.ko加载的时候会报：
Error: could not insert module sunxi-ir.ko: Invalid module format
而系统自带的hv2605.ko 就没有问题？

用的源码也是Cubian  A20的源码？  点解啊

**Comment by cubieplayer** [comment]
closed duplicated with https://github.com/cubieplayer/Cubian/issues/121
