### ISSUE TITLE
/sys/class/gpio permissions error

### ISSUE THREAD

**Issue by throwcomputer** [cubieplayer/Cubian#12]
After setting up the GPIO driver gpio_sunxi and modifying the .fex to set up some gpio pins..exporting those pins using echo 1 > /sys/class/gpio/export fails due to permissions error.

/sys/class/gpio is owned by root and group root requiring a temporary solution that includes creating group gpio, assigning group gpio to user and chgrp /sys/class/gpio recursively to gpio while chmod 775 recursively to same /sys/class/gpio.

This resets on reboot requiring a fresh setup on each boot before default cubie user can work with the gpio pins using /sys/class/gpio.

**Comment by cubieplayer** [comment]
thanks for sharing, It's will be fixed on r3
