### ISSUE TITLE
r5 apt-get install xorg just coredumps

### ISSUE THREAD

**Issue by EvF** [cubieplayer/Cubian#120]
That's it really
I also tried a freshly imaged SD card, resized up to 16GB first.

sudo apt-get install xserver-xorg-core

Also resulted in a coredump followed by
 kernel: Internel error: Oops: 805 [#1] PREEMPT ARM.

**Comment by cubieplayer** [comment]
Hi, Please take a look at http://cubian.org/2013/09/18/fix-random-crash/, does it help?

**Comment by EvF** [comment]
Yes, that seems to have sorted it. Thanks.
(and sorry it took me so long to check it)
