### ISSUE TITLE
IR Received can't be use in A20. Please Update Kernel.

### ISSUE THREAD

**Issue by chuprex** [cubieplayer/Cubian#121]
root@Cubian:/home/cubie# dmesg | grep IR
[    0.000000] NR_IRQS:160
[    0.572821] Serial: 8250/16550 driver, 8 ports, IRQ sharing disabled
[    2.785223] lirc_dev: IR Remote Control driver registered, major 251 
[    2.795164] IR NEC protocol handler initialized
[    2.803446] IR RC5(x) protocol handler initialized
[    2.811728] IR RC6 protocol handler initialized
[    2.819747] IR JVC protocol handler initialized
[    2.827843] IR Sony protocol handler initialized
[    2.836991] IR RC5 (streamzap) protocol handler initialized
[    2.846225] IR SANYO protocol handler initialized
[    2.855719] IR MCE Keyboard/mouse protocol handler initialized
[    2.864954] IR LIRC bridge handler initialized
root@Cubian:/home/cubie# 

result from modprobe

root@Cubian:/home/cubie# modprobe sunxi_ir
FATAL: Module sunxi_ir not found.
root@Cubian:/home/cubie# modprobe sun4i_ir
FATAL: Module sun4i_ir not found.
root@Cubian:/home/cubie# modprobe sun7i_ir
FATAL: Module sun7i_ir not found.

Result from LIRC

root@Cubian:/home/cubie# lircd -n --device=name='IR*' -H devinput
lircd-0.9.0-pre1[4115]: config file contains no valid remote control definition
lircd-0.9.0-pre1[4115]: lircd(devinput) ready, using /var/run/lirc/lircd

^Clircd-0.9.0-pre1[4115]: caught signal

root@Cubian:/home/cubie# for i in /sys/class/input/input\* ; do echo -n "$(basename "$i"): "; cat "$i/name"; done
input0: axp20-supplyer
input1: USB2.0 PC CAMERA
input2: USB2.0 PC CAMERA
root@Cubian:/home/cubie# 

Please to help me about this IR.

**Comment by michalliu** [comment]
Closed duplicated with https://github.com/cubieplayer/Cubian/issues/126
