### ISSUE TITLE
Please add 'capture_used = 1' to script.fex

### ISSUE THREAD

**Issue by autostatic** [cubieplayer/Cubian#125]
With the current script.bin provided with the Cubian-base-r2-arm-a20 image the capture controls of the onboard audio codec do not work. When adding `capture_used = 1` to script.fex the capture controls show up again.

**Comment by cubieplayer** [comment]
Okay

**Comment by cubieplayer** [comment]
Hi, this issue is solved, but i forgot to close the issue. The latest image is here. http://cubian.org/2013/11/08/cubian-r6-for-a10-and-r3-for-a20-released/
