### ISSUE TITLE
Please Add IR Module Driver

### ISSUE THREAD

**Issue by chuprex** [cubieplayer/Cubian#126]
@cubieplayer , please add IR Module Driver.

Thank's

**Comment by cubieplayer** [comment]
Hi this module is supported by now, try cubian-update

**Comment by chuprex** [comment]
OK, i try now. Thx

**Comment by chuprex** [comment]
@cubieplayer : 
I am still confused, which indicates the position of infrared device??

**Comment by cubieplayer** [comment]
Is `modprobe sunxi-ir` working?

**Comment by chuprex** [comment]
[28998.454262] input: sunxi-ir as /devices/virtual/input/input1
[28998.456827] IR Initial OK

/sys/devices/virtual/input/input1   <=== right this??

How i can use this device on LIRC ??
