### ISSUE TITLE
SSH连接不上Cubian

### ISSUE THREAD

**Issue by Garfield550** [cubieplayer/Cubian#13]
li@Lenovo:~$ ssh -p 36000 192.168.0.104
The authenticity of host '[192.168.0.104]:36000 ([192.168.0.104]:36000)' can't be established.
ECDSA key fingerprint is 55:49:9a:d0:51:a6:d8:85:44:e6:d1:19:25:41:6e:d3.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[192.168.0.104]:36000' (ECDSA) to the list of known hosts.
li@192.168.0.104's password: 
Permission denied, please try again.
li@192.168.0.104's password: 
Permission denied, please try again.
li@192.168.0.104's password: 
Permission denied (publickey,password).

我输入的密码就是 cubie 但还是连不上

系统 Debian 7
环境 Xfce 4.8.6

**Comment by cubieplayer** [comment]
你没有指定用户名，因此实际上你是在尝试用`li`这个用户名登录，当然会失败。解决办法是修改`~/.ssh/config`,没有的话就新建，内容输入

```
User cubie
```

**Comment by Garfield550** [comment]
好的谢谢
