### ISSUE TITLE
How to move debian to hdd?

### ISSUE THREAD

**Issue by EvF** [cubieplayer/Cubian#131]
Apologies if this has been asked before.
How do I move a working SD boot to a HDD install?

I partitioned a 60GB SSD and rsync'd / across from the SD and marked sda1 as bootable.
But if I shutdown, pull the SD, then power-up it boots demo Lubuntu image from nand instead.

I assume there is a config file somewhere I need to edit?

**Comment by michalliu** [comment]
Edit uEnv.txt on nand may helps

**Comment by EvF** [comment]
I've not looked in tehre before. I'm having a bit of trouble understanding what is what on nand.
I see nand is parted into nanda thru nandg

nanda has a lot of linux-like stuff ... but no boot dir
nandc looks more like a big linux and it has a boot dir but no uEnv.txt

But so I can have a bit more of an idea what I am doing, is there a guide somewhere that explains how this thing boots?

**Comment by EvF** [comment]
Rather than modify nand to boot HDD would i be betetr to put a bootloader onto SD that just boots the HDD instead?
Any recommendations?

**Comment by cubieplayer** [comment]
This is a planned feature. Closed duplicate with https://github.com/cubieplayer/Cubian/issues/152
