### ISSUE TITLE
USB Modem support

### ISSUE THREAD

**Issue by James8192** [cubieplayer/Cubian#135]
Add please these kernel options to support USB modems
CONFIG_USB_ACM
CONFIG_USB_SERIAL_OPTION
also good to have CONFIG_TUN option too. (required by openvpn)

**Comment by BBELLIDO** [comment]
Hello,

I have the same problem and i have Been trying to solve ir for 5 days, but ir doesnt works. I have compiled the kernel but the module doesn't works, it Seems to be a different kernel layout. Have You solved this issue? Antes suggestion?

I really need it for my university project

Best regards

**Comment by cubieplayer** [comment]
Issue relates to tun.ko https://github.com/cubieplayer/Cubian/issues/147

**Comment by cubieplayer** [comment]
It's enabled by now, try cubian-update
