### ISSUE TITLE
Logitech wireless kbd/mouse not working after cubian-update

### ISSUE THREAD

**Issue by hubaiz** [cubieplayer/Cubian#138]
After booted with Cubian-base-r2-arm-a20.img the Logitech wireless keyboard/mouse was working.
Checked the kernel config and
CONFIG_HIDRAW=y

I did a cubian-update and after that my Logitech wireless keyboard/mouse stoped working
After the update CONFIG_HIDRAW in kernel config was not set anymore.

**Comment by cubieplayer** [comment]
It's a regression on kernel config.I switched kernel to patwood's branch which caused the problem on it's default config. Now it has been fixed, run cubian-update again. 
https://github.com/mmplayer/sunxi-kernel-config/commit/a054793384cb2883222da9669d6409be6ac96377

**Comment by hubaiz** [comment]
Thnaks for fast reponse. It is working now. Tested the LXDE install, NAND install and also installed on a SSD and all is working fine.
