### ISSUE TITLE
Driver usbserial ftdi

### ISSUE THREAD

**Issue by railton** [cubieplayer/Cubian#14]
Driver not found in r2 version
I need to connect an Arduino via serial

 ls /dev/ttyUSB0
ls: cannot access /dev/ttyUSB0: No such file or directory

**Comment by cubieplayer** [comment]
Yeah, it's not compiled to kernel by default, I will fix this on r3, and i will make a script to update kernel and drivers dynamically in the futuer

**Comment by cubieplayer** [comment]
Usb serial cable driver is compiled in r3
