### ISSUE TITLE
Screen gets black

### ISSUE THREAD

**Issue by rainerfritz** [cubieplayer/Cubian#144]
Hi !

With the opengles desktop I'm getting after a couple of minutes a black screen and after that I can only login via SSH or VNC to restart the cubie to get on the desktop again on my HDMI screen...
Screensaver is switched off....

**Comment by cubieplayer** [comment]
Please disable X power management

> xset -dpms

**Comment by rainerfritz** [comment]
thx that seem to work

**Comment by ghost** [comment]
works here too :) thanks

**Comment by sbsohrabi** [comment]
mine doesn't work !!
I also tested :
 xset -dpms
xset s off
xset s noblank
nothing happened
I feel really depressed with this thing !
how to disable the Lock screen after 5min ??
CT and cubian X
