### ISSUE TITLE
Messed owner/group in fresh install  - cb2 image.

### ISSUE THREAD

**Issue by MrSpock** [cubieplayer/Cubian#146]
Hello,

Just after dd'ing image on sd card and login into system I have following owner/group values:

drwxr-xr-x 22 cubie gpio 4.0K Aug 25  2013 .
drwxr-xr-x 22 cubie gpio 4.0K Aug 25  2013 ..
drwxr-xr-x  2 cubie gpio 4.0K Aug 25  2013 bin
drwxr-xr-x  2 root  root 4.0K Jan  1 00:03 boot
drwxr-xr-x 10 root  root 3.3K Jan  1 00:01 dev
drwxr-xr-x 60 root  root 4.0K Jan  1 00:00 etc
drwxr-xr-x  3 cubie gpio 4.0K Sep  4  2013 home
drwxr-xr-x 12 cubie gpio 4.0K Sep  4  2013 lib
drwx------  2 root  root  16K Sep  4  2013 lost+found
drwxr-xr-x  2 root  root 4.0K Aug 25  2013 media
drwxr-xr-x  2 cubie gpio 4.0K Dec 14  2012 mnt
drwxr-xr-x  2 root  root 4.0K Aug 25  2013 opt
dr-xr-xr-x 81 root  root    0 Jan  1  1970 proc
drwx------  3 cubie gpio 4.0K Jan  1 00:03 root
drwxr-xr-x 11 root  root  420 Jan  1 00:01 run
drwxr-xr-x  2 cubie gpio 4.0K Aug 25  2013 sbin
drwxr-xr-x  2 cubie gpio 4.0K Jun 10  2012 selinux
drwxr-xr-x  2 root  root 4.0K Aug 25  2013 srv
dr-xr-xr-x 12 root  root    0 Jan  1 00:00 sys
drwxrwxrwt  2 root  root   40 Jan  1 00:01 tmp
drwxr-xr-x 10 root  root 4.0K Jul 25  2013 usr
drwxr-xr-x 11 cubie gpio 4.0K Aug 25  2013 var

I never saw / owned by user. How to fix this ? Is chown  -R is reasonable ?

**Comment by MrSpock** [comment]
Good news is that only folders are messed. Files inside are ok  - however every folder deeper is also broken.

**Comment by MrSpock** [comment]
Temporary solution:
- cd /var; find . -type d -group gpio -user cubie -print -exec chown root:root {} \;
- cd /lib; find . -type d -group gpio -user cubie -print -exec chown root:root {} \;
- manual changes in "/"

**Comment by cubieplayer** [comment]
Something is wrong, I'll follow up this problem

**Comment by michalliu** [comment]
I noticed this issue only happens on A20.The problem is caused by the udev rules https://github.com/mmplayer/fsupdate/blob/base/common/etc/udev/rules.d/99-gpio-permission.rules

Because the GPIO driver is not working on cb2 in previous release, The rule will cause the problem.

**Comment by cubieplayer** [comment]
This problem should be solved on r3 for A20. http://cubian.org/2013/11/08/cubian-r6-for-a10-and-r3-for-a20-released/
