### ISSUE TITLE
wifi adapters

### ISSUE THREAD

**Issue by McBodik** [cubieplayer/Cubian#148]
On r5 I have problem: cubian not see wifi adapter - "device wlan0 not found".  In r4 all fine. Also all fine in r4 update to r5. Maybe you need add guide how to install some drivers etc?

**Comment by michalliu** [comment]
what's your wifi dongle?

**Comment by McBodik** [comment]
Mercury WiFi USB Adapter

When I reboot Cubieboard after update r5 I have the same :(

**Comment by cubieplayer** [comment]
What's the output of lsmod? You can try `modprobe 8188eu` or `modprobe 8192cu`

**Comment by McBodik** [comment]
<code>lsmod</code> give me 

<blockquote> cpufreq_userspace       3412  0 <br/>
cpufreq_stats           2930  0 <br/>
cpufreq_powersave       1224  0 <br/>
cpufreq_conservative     5408  0 <br/>
ump                    58137  0 <br/>
rtl8192cu             114408  0 
rtlwifi                88894  1 rtl8192cu <br/>
rtl8192c_common        74347  1 rtl8192cu <br/>
mac80211              276829  3 rtlwifi,rtl8192c_common,rtl8192cu</blockquote> 

About <code>modprobe</code>'s : first message is 

<blockquote> Message from syslogd@Cubian at Oct  9 06:00:01 ... <br/>
 kernel:[  183.810000] Internal error: Oops: 807 [#1] PREEMPT ARM </blockquote> 

others, I think, normal, but it doesn't help.

**Comment by cubieplayer** [comment]
Ok,May be i missed some wifi modules on A10

**Comment by cubieplayer** [comment]
Hi, These modules are compiled now, you can try `cubian-update` to get it, Please re-open the issue if it's not working.
