### ISSUE TITLE
Update to new u-boot

### ISSUE THREAD

**Issue by derekdhaas** [cubieplayer/Cubian#150]
The new u-boot ( https://github.com/linux-sunxi/u-boot-sunxi ) will speed up boot time by 10+ seconds.

Changelog: (as described by patwood in a cubieforums topic)
I changed the "Hit any key to stop autoboot" timeout to 1 second, and it has a change made on 11 Aug by Hans de Goede that enabled the caches in u-boot (there was a ~10 second delay here while u-boot loaded and decompressed the kernel).

Tried to flash it: http://dl.cubieforums.com/patwood/u-boot-mmc-ext4.tar.gz but didn't work.

**Comment by derekdhaas** [comment]
Source: http://www.cubieforums.com/index.php/topic,838.msg5049.html#msg5049

**Comment by cubieplayer** [comment]
Thanks, but it's already 1s for now. I didn't use the public u-boot.

**Comment by derekdhaas** [comment]
In the version I use, there's still a delay of 10 seconds while u-boot is loading the kernel.

**Comment by derekdhaas** [comment]
Left out too many details: The current cubian version will uncompress and load the kernel the first 10 seconds of boot. Then it will boot the kernel. In the u-boot patwood is using, the u-boot will only wait 1 second before booting the linux image. It's not the delay of "Hit any key to stop autoboot", but the new enabled cache in u-boot for loading the kernel almost instant.

**Comment by cubieplayer** [comment]
Okay, Sry, i misunderstood what you said.

**Comment by cubieplayer** [comment]
I tested the new u-boot. It's faster than the old one. I'll switch to use the new u-boot.

**Comment by derekdhaas** [comment]
Great news! Thanks a lot!

**Comment by cubieplayer** [comment]
If you cubian-update, you will get the new u-boot now.

**Comment by cubieplayer** [comment]
you should use

```
cubian-update --update-bootloader --reinstall
```

for now, the bootloader will **NOT** updated unless you tell it to do so.
