### ISSUE TITLE
can't connect to ssh

### ISSUE THREAD

**Issue by lpwcn** [cubieplayer/Cubian#151]
I wrote cubian to a sdcard,and power on.I can see the cubieboard get a IP from my router.It is 192.168.1.249.I try to telnet it.The command is "telnet 192.168.1.249 36000".I got a message said "SSH-2.0-OpenSSH_6.0p1 Debian-4".but when I use SSH Secure Shell Client to connect it,The SSH Secure Shell Client return a message "Server responded 'Connection closed' ".
I try to close my firewall in the windows7,But still can not connect.
Has anyone encountered this situation,Please tell me，thanks.

**Comment by reycyril** [comment]
I have also the same issue :

ssh -v -p 36000 cubie@192.168.1.121
OpenSSH_6.2p2 Debian-6, OpenSSL 1.0.1e 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 192.168.1.121 [192.168.1.121] port 36000.
debug1: Connection established.
debug1: identity file /home/cyril/.ssh/id_rsa type 1
debug1: Checking blacklist file /usr/share/ssh/blacklist.RSA-2048
debug1: Checking blacklist file /etc/ssh/blacklist.RSA-2048
debug1: identity file /home/cyril/.ssh/id_rsa-cert type -1
debug1: identity file /home/cyril/.ssh/id_dsa type -1
debug1: identity file /home/cyril/.ssh/id_dsa-cert type -1
debug1: identity file /home/cyril/.ssh/id_ecdsa type -1
debug1: identity file /home/cyril/.ssh/id_ecdsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.2p2 Debian-6
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.0p1 Debian-4
debug1: match: OpenSSH_6.0p1 Debian-4 pat OpenSSH*
debug1: SSH2_MSG_KEXINIT sent
Read from socket failed: Connection reset by peer

I have same issue from two computer. One running Debian testing and one running debian squeeze.
Cubieboard is running : Cubian-base-r5-arm-a10.img

Should it be that Cubian image have some know host interfering with 192.168.1.\*   ?

Cyril

**Comment by cubieplayer** [comment]
wired, I have no clue on this issue

**Comment by charudatt** [comment]
Even I have the same problem and after a couple of attempts the Board Hangs.

**Comment by charudatt** [comment]
any solution in Site ?

**Comment by michalliu** [comment]
Needs to know how to reproduce the problem.

**Comment by lpwcn** [comment]
I connect the cubieboard with a HDMI TV, and run three command like this:
ssh-keygen -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key
ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key

restart ssh,Finally solved the problem

**Comment by michalliu** [comment]
ssh-key is generated at first boot.

**Comment by lpwcn** [comment]
May be there are something wrong with my first boot

**Comment by charudatt** [comment]
Any idea why does the Board handup after a couple of tries ?

**Comment by mylselgan** [comment]
If your ssh failed to connect it may be because of initial miss configuration. Do the following to fix it

```
rm /etc/ssh/ssh_host_*
dpkg-reconfigure openssh-server 
```
