### ISSUE TITLE
Problem Realtek RTL8188SU WLAN Adapter(NOT Compiled)

### ISSUE THREAD

**Issue by cover-itx** [cubieplayer/Cubian#153]
Hi cubieplayer and thanks for support u...
i have a dongle wifi  Realtek RTL8188SU but this dongle not compiled for cubian
but worked with Lubuntu 12.04
please compile this dongle ...

kernel configuration name of this module
output lsusb
ID 0bda:8171 Realtek Semiconductor Corp. RTL8188SU 802.11n WLAN Adapter

output lsmod
r8712u

thanks.

**Comment by cubieplayer** [comment]
Okay

**Comment by cubieplayer** [comment]
Hi, These modules are compiled now, you can try `cubian-update` to get it, Please re-open the issue if it's not working.

**Comment by phylocko** [comment]
There is a wifi dongle ASUSTek USB-N10 built on the same chip but having another ID.
Not working when loading rtl8187 module.

lsusb:
ID 0b05:1786 ASUSTek Computer, Inc. USB-N10 802.11n Network Adapter [Realtek RTL8188SU]

Could you please add this ID into drv?
Thank you!
