### ISSUE TITLE
Could you please add kernel-device-mapper to kernel for cubieboard2

### ISSUE THREAD

**Issue by vbretsch** [cubieplayer/Cubian#154]
I am trying to mount my hdds which are a lvm2 volume group and i consistently get following error message:

---

root@Cubian:/dev/mapper# sudo pvscan
 /dev/mapper/control: open failed: No such device
 Failure to communicate with kernel device-mapper driver.
 Check that device-mapper is available in the kernel.

---

Am i doing something wrong or is there something that has to be compiled into the kernel which is not currently in it?
I am running Cubian-base-r2-arm-a20.img on cubieboard2.

Regards,
Volker

**Comment by vbretsch** [comment]
Is there already a recommended solution for this problem?

Regards

**Comment by cubieplayer** [comment]
What's the name in kernel configuration?

**Comment by vbretsch** [comment]
i think it is Logical Volume Manager and Device Mapper:

http://www.linuxtopia.org/online_books/linux_kernel/kernel_configuration/ch09s05.html

**Comment by cubieplayer** [comment]
Ok, I think it's easy to fix

**Comment by vbretsch** [comment]
Patwoods current kernel has device mapper enabled. (http://dl.cubieforums.com/patwood/A20-kernel-3.4.61.tar.gz). Unfortunately i was not able to get it to boot in Cubian... 
maybe a helpful starting point though..

**Comment by cubieplayer** [comment]
Hi, These modules are compiled now, you can try `cubian-update` to get it, Please re-open the issue if it's not working.

**Comment by vbretsch** [comment]
Thx! lvm2 now works nicely.
Only problem was after cubian-update cubieboard did not boot anymore from nand (issue #137).
