### ISSUE TITLE
CDC-ACM USB MODEM SUPPORT

### ISSUE THREAD

**Issue by BBELLIDO** [cubieplayer/Cubian#155]
Hello,

I need usb modem support, could you be so kind to do this?

----- USB Device Class drivers

CONFIG_USB_ACM=m
CONFIG_USP_PRINTER=m
CONFIG_USB_WDM=m

I have this problem and i have Been trying to solve ir for 5 days, but ir doesnt works. I have compiled the kernel but the module doesn't works, it Seems to be a different kernel layout. Have You solved this issue? Antes suggestion?

I really need it for my university project

Best regards

**Comment by cubieplayer** [comment]
Ok

**Comment by BBELLIDO** [comment]
Thanks a lot, I use cubie 2, I will wait impatiently :-) It's the only thing I need to finish my university project.

Thanks in advance from Spain

**Comment by cubieplayer** [comment]
Closed duplicated with https://github.com/cubieplayer/Cubian/issues/92

**Comment by cubieplayer** [comment]
Hi, It's supported by now. try with cubian-update

**Comment by BBELLIDO** [comment]
It works!!!!  I`m very gratefully!!!  thanks a lot!!!!

You make me happy guy!!!
