### ISSUE TITLE
Overclocking settings, script.bin, apt-get problems on A10-based tablets

### ISSUE THREAD

**Issue by ghost** [cubieplayer/Cubian#157]
First, thanks for this great distro - Debian is much better and faster than any Ubuntu distro, even than Linaro nano.

It works great on my sun4i based tablet (http://www.pcadvisor.co.uk/reviews/tablets/3379659/goclever-tab-a73-review/) after changing script.bin (to enable LCD) and adding 8192cu to ''/etc/modules''. I am even trying to make wiki about tuning Cubian on tablets (http://cubiana73.informatick.net). But yesterday I noticed few problems:
- After cubian-update, my overclocking settings (fantasy/120/816) was restored to 1008MHz. I know about random resets bug, but maybe make some change, and edit ''/etc/init.d/cubian-ondemandfreq'' file ONLY when max_freq is set to 1200MHz?
- cubian-update has options --skip-kernel and --skip-modules, but I don't see --skip-bootloader. Maybe it's good to add this feature? In another case, other A10 based devices will never boot after update (because of changed script.bin) :(
- apt-get upgrade is veeeeeery slow, I think that is caused by ondemand governor. Is there option to change temporarily governor when apt is used?

**Comment by cubieplayer** [comment]
Thanks for sharing your experience.
1. I'd like to add an option to skip the patches when running cubian-update
2. If the update is slow, you may edit the `/etc/apt/sources.list` . Use a [mirror](http://www.debian.org/mirror/list) which is nearest from your geolocation, or you can set a proxy by

> export http_proxy="http://someurl"

**Comment by ghost** [comment]
Sorry, my mistake. I meant not apt, but dpkg is working slow, for example when

> Preparing to replace package_name x.y.z-x (using package_name_x.y.z-x_armhf.deb) ...

My internet connection is good and also Debian mirrors are working correctly.

**Comment by cubieplayer** [comment]
Hi, cubian-updates (v1.2.4 ) supports various skip commands. Take a look at `cubian-update -h` after you installed it
