### ISSUE TITLE
Dualboot on Cubieboard

### ISSUE THREAD

**Issue by s-kostyuk** [cubieplayer/Cubian#158]
Good day everyone! Maybe this is not correct place for U-Boot questions but I hope find an answer there.

I have Cubieboard 1, last Cubian on NAND, it's full rootfs copy on external HDD (/dev/sda2) and very strong desire to organize dualboot with Android TV Box 2.2 from http://cubieboard.org. How to modify U-Boot for support of OS choosing on startup, do I must to use different kernels for Cubian and Android both and can I simply install Cubian bootloader with changed uEnv.txt to boot Android (I mean change "root=/dev/nandb" string to "root=/dev/nandc" in uEnv.txt file and leave other components as is)? Many thanks and sorry for my English.

**Comment by cubieplayer** [comment]
It's a good idea but AFAIK the u-boot doesn't include a display driver, so you can't display anything on to the screen.

**Comment by s-kostyuk** [comment]
This is not big problem if we can use some button/GPIO pins/file on internal storage to choose needed OS. If so, is any way to realize it? And previous questions (about uEnv.txt, modifying of U-Boot, different kernels) is still actual too.

**Comment by cubieplayer** [comment]
Yes, it seems possible, The new uboot does support gpio operations on a10, but not on a20.

**Comment by s-kostyuk** [comment]
OK. How to build U-Boot for Cubian from source, activate and set this feature? And what manuals can you advice for my problem?

**Comment by cubieplayer** [comment]
For A10 and A20 SD-card: https://github.com/mmplayer/u-boot-sunxi/tree/sunxi
A10 nand: https://github.com/mmplayer/u-boot-sunxi/tree/sunxi-nand
A20 nand: https://github.com/mmplayer/u-boot-sunxi/commits/dev/a20-nand-ext4

**Comment by s-kostyuk** [comment]
OK, many thanks :)
