### ISSUE TITLE
ftdi driver

### ISSUE THREAD

**Issue by railton** [cubieplayer/Cubian#16]
Please

I want to use an Arduino connected to cubieboard, put the FTDI driver is not available. 

Look
Ubuntu or other Debian based systems
The FTDI Driver is included with Ubuntu/Debian. After plugging in the USB cable, you can find your device under /dev/ttyUSB0 (and ttyUSB1, ttyUSB2, etc, if you have more) or /dev/ttyACM0
url: http://wiki.ultimaker.com/FTDI_Driver_installation

Thanks.

**Comment by cubieplayer** [comment]
Hi,
I compiled the FTDI driver for you.You need
1. [download the driver](http://cubieplayer.github.io/static_files/temp/).
2. copy it to `/lib/modules/3.4.43/kernel/drivers/usb/serial/`.
3. execute `sudo depmod` 
4. execute `sudo modprobe ftdi_sio`

Hope it helps, I will make something like rpi-update to update driver online in the future.

**Comment by railton** [comment]
Now it worked, thank you

ls / dev / ttyUSB *
/ dev/ttyUSB0 / dev/ttyUSB1 / dev/ttyUSB2

java-jar acesso.jar debug
   15:54:33 | 25/06/2013 | CONTROLADORA INICIALIZADO [/ dev/ttyUSB0]
   15:54:33 | 25/06/2013 | RFID1 INICIALIZADO [/ dev/ttyUSB1]
   15:54:33 | 25/06/2013 | RFID2 INICIALIZADO [/ dev/ttyUSB2]
