### ISSUE TITLE
rtlwifi (rtl8192cu) not working anymore

### ISSUE THREAD

**Issue by derekdhaas** [cubieplayer/Cubian#163]
Since the new kernel, the rtlwifi for the rtl8192cu isn't working anymore.

dmesg:
ADDRCONF(NETDEV_UP): wlan0 link is not ready

/etc/init.d/networking restart: (when using static configuration)
RTNETLINK answers: File exists
Failed to bring up wlan0.

/etc/init.d/networking restart: (when using dhcp)
No DHCPOFFERS

DHCP btw doesn't work at all 

Scanning networks will work, but using the same configuration on the older kernel and the newer one, the older will work, but the newer won't.

My config:

auto wlan0
iface wlan0 inet static
address 192.168.1.40
gateway 192.168.1.1
dns-nameservers 192.168.1.1
netmask 255.255.255.0
wpa-ssid MYSSID
wpa-ap-scan 1
wpa-proto RSN
wpa-pairwise CCMP
wpa-group CCMP
wpa-key-mgmt WPA-PSK
wpa-psk MYHexKey

Great tutorial: http://ubuntuforums.org/showthread.php?t=318539

Also tried hotplug wlan0
Disabled WPA on router (which gives the same errors displayed above)

Btw I had to download the firmware (via apt-get realtek-firmware)

Was hoping more users would have this problem...

**Comment by bowsa** [comment]
I am having the same issue too.

**Comment by cubieplayer** [comment]
Have you tried  `cubian-update` ?

**Comment by bowsa** [comment]
Yes I did. I had to do apt-get install Realtek-firmware to get the board to recognize the wireless dongle. I am now getting DHCP from my router and I can ping from the Cubieboard but I cannot ping to it or ssh to it 
through the wireless dongle.

**Comment by cubieplayer** [comment]
I don't have a rtl8192cu, so i can't test for it. I just recompiled and uploaded the driver. I hope it will work. Try run cubian-update.If not please report and re-open the issue.

**Comment by cubieplayer** [comment]
Please aslo take a look at https://github.com/cubieplayer/Cubian/issues/181 to solve the problem
