### ISSUE TITLE
No g_ether module

### ISSUE THREAD

**Issue by ghost** [cubieplayer/Cubian#166]
My mate have problems with using USB ethernet adapther on original Cubieboard (A10).
It looks like g_ether module is not compiled, as modprobe says:

> FATAL: Module g_ether not found.

It's possible to add module to new kernel as soon as possible?
## References
- http://linux-sunxi.org/USB_Gadget

**Comment by cubieplayer** [comment]
Hi, These modules are compiled now, you can try `cubian-update` to get it, Re-open the issue if it's not working.
