### ISSUE TITLE
Troubles on boot from sd 

### ISSUE THREAD

**Issue by McBodik** [cubieplayer/Cubian#167]
Hi. After update I can't boot from sd(system is installed on it). But I think is not update problem, because earlier I have the similar problem after restart(input, output sd.. n times help me:))
But I have no monitor connected thats why I didn't see message. Now I connect monitor and see the next:
<code>EXT4-fs (mmcblk0p1): re-mounted. Opts: (null)</code>
After out - in sd I have:
<code>EXT4-fs error (device mmcblk0p1): ext4_find_entry:932: inode #22902 (and another 22097) comm udevd: reading directory lblock 0</code>
It's stay on this. I try change uEnv.txt but really I don't know what I need put there:) 

Can I fix this?

**Comment by sebastianrothe** [comment]
same here

**Comment by cubieplayer** [comment]
May be you need to call `sync` after `dd`

**Comment by sebastianrothe** [comment]
I'm using a 32gb sdcard. The image is written on windows with windiskimage32. I think i had no problems with 8gb sdcard. I will check again.

Power supply is 2A.

**Comment by cubieplayer** [comment]
@McBodik  @blackpat  please refer to https://github.com/cubieplayer/Cubian/issues/132 to solve the problem
