### ISSUE TITLE
Troubles with nandinstall

### ISSUE THREAD

**Issue by BBELLIDO** [cubieplayer/Cubian#168]
Hello every body,

I'm usin cubieboard 2 and cubian a20 r2.

I want to install cubian on nand. I have updated cubian with apt-get, cubian-update,  and I have installed the latest cubian-nandinstall (I see the tutorial).

I execeute cubian-nandinstall, all is succeded and I shutdown when it's finished. I remove SD but cubieboard doesn't work with nand, No flashing led, nothing at all, what can I do?

I have try it several times but doesn't work. 

I see the nanda and nandc and has all the files. uEnv.txt seems to be oK. Any suggestion?

Thanks in advance

**Comment by a2life** [comment]
Hi, I am having the same or similar issue. My system was already on Nand when I did the the latest update.
#apt-get update
#apt-get install cubian-update
#cubian-update

 I see the kernel is upgraded to 3.4.6.  Unfortunately, Cubian would not boot up from nand any longer.

**Comment by a2life** [comment]
Update:   Thinking kernel might have been corrupted, I went ahead and replaced kernel and library modules with the ones that Patwood was providing (3.4.61) in curibeforum. While doing that, from SD installation trial I noticed the /dev/nandc has changed to /dev/nand3,  So I changed the uEnv reference from nandc to nand3, and also changed etc/fstab reference (dont know if this was needed)   I dont know which part (replacing kernel or changing nand naming) worked, or patwood's implementation just calls for nand3 instead of nandc.   Bottom line is Cubian is back to life and booting from nand (with Patwood's kernel tarball => http://dl.cubieforums.com/patwood/A20-kernel-3.4.61.tar.gz)
I also noticed that when doing this kernel surgery with SDcard,  I simply copied firmware over the existing firmware version (3.43) and noticed various RTL\* directories were missing from 3.61 firmware.  Again it may simpy means thoese fw are no longer needed, but the working copy ended up having RTL8192E, RTL8192SU, rtl_nic and rtlwifi directories. - and I ran out of time.  and cubie is working so I stopped my investigation there.

**Comment by cubieplayer** [comment]
@a2life Thanks for reporting the problem, cubian doesn't agree with patwookd's configuration.It use nandc as the device name.

**Comment by BBELLIDO** [comment]
Hello again,

any notice?  i don't know what to do. I have tried it several times, with another new cubieboard2, booting cubian from SD, and I do

$apt-get update
$apt-get install cubian-update
$cubian-update
$apt-get install cubian-nandinstall
$cubian-nandinstall

It finish succesfully and I type 'yes' to shutdown. After it I remove SD and init cubieboard2, but no flashing led and nothing at all. :-(

Any suggestion?

**Comment by BBELLIDO** [comment]
Please, 

any suggestion? how can I set nand new and restart from zero? I'm runout of ideas ...

Thanks in advance

**Comment by cubieplayer** [comment]
@BBELLIDO If you can provide some log from serial port (http://linux-sunxi.org/Cubieboard/TTL) it will be helpful

**Comment by BBELLIDO** [comment]
I saw in cubian-nandinstall logs, "unable to get drive geometry, using default 255/63", it gives you any clue?

Best regards

**Comment by BBELLIDO** [comment]
I post you cubian-nandinstall logs:

dev/nanda on /mnt/nanda type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=cp437,iocharset=ascii,shortname=mixed,errors=remount-ro)
^[[36mumounting /dev/nanda^[[m
/dev/nandc on /mnt/nandb type ext4 (rw,relatime,data=ordered)
^[[36mumounting /dev/nandc^[[m
^[[36mcontinue to install on NAND^[[m
mkfs.vfat 3.0.13 (30 Jun 2012)
unable to get drive geometry, using default 255/63
Filesystem label=
OS type: Linux
Block size=4096 (log=2)
Fragment size=4096 (log=2)
Stride=0 blocks, Stripe width=0 blocks
248496 inodes, 992960 blocks
49648 blocks (5.00%) reserved for the super user
First data block=0
Maximum filesystem blocks=1019215872
31 block groups
32768 blocks per group, 32768 fragments per group
8016 inodes per group
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736

Allocating group tables:  0/31^H^H^H^H^H 1/31^H^H^H^H^H 2/31^H^H^H^H^H 3/31^H^H^H^H^H 4/31^H^H^H^H^H 5/31^H^H^H^H^H 6/31^H^H^H^H^H 7/31^H^H^H^H^H 8/31^H^H^H^H^H 9/31^H^H^H^H^H10/31^H^H^H^H^H11/31^H^H^H^H^H12/31^H^H^H^H^H13/31^H^H^H^H^H14/31^H^H^H^H^H15/31^H^H^H^H^H16/31^H^H^H^H^H17/31^H^H^H^H^H18/31^H^H^H^H^H19/31^H^H^H^H^H20/31^H^H^H^H^H21/31^H^H^H^H^H22/31^H^H^H^H^H23/31^H^H^H^H^H24/31^H^H^H^H^H25/31^H^H^H^H^H26/31^H^H^H^H^H27/31^H^H^H^H^H28/31^H^H^H^H^H29/31^H^H^H^H^H30/31^H^H^H^H^H     ^H^H^H^H^Hdone
Writing inode tables:  0/31^H^H^H^H^H 1/31^H^H^H^H^H 2/31^H^H^H^H^H 3/31^H^H^H^H^H 4/31^H^H^H^H^H 5/31^H^H^H^H^H 6/31^H^H^H^H^H 7/31^H^H^H^H^H 8/31^H^H^H^H^H 9/31^H^H^H^H^H10/31^H^H^H^H^H11/31^H^H^H^H^H12/31^H^H^H^H^H13/31^H^H^H^H^H14/31^H^H^H^H^H15/31^H^H^H^H^H16/31^H^H^H^H^H17/31^H^H^H^H^H18/31^H^H^H^H^H19/31^H^H^H^H^H20/31^H^H^H^H^H21/31^H^H^H^H^H22/31^H^H^H^H^H23/31^H^H^H^H^H24/31^H^H^H^H^H25/31^H^H^H^H^H26/31^H^H^H^H^H27/31^H^H^H^H^H28/31^H^H^H^H^H29/31^H^H^H^H^H30/31^H^H^H^H^H     ^H^H^H^H^Hdone
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information:  0/31^H^H^H^H^H 1/31^H^H^H^H^H 2/31^H^H^H^H^H 3/31^H^H^H^H^H 4/31^H^H^H^H^H 5/31^H^H^H^H^H 6/31^H^H^H^H^H 7/31^H^H^H^H^H 8/31^H^H^H^H^H 9/31^H^H^H^H^H10/31^H^H^H^H^H11/31^H^H^H^H^H12/31^H^H^H^H^H13/31^H^H^H^H^H14/31^H^H^H^H^H15/31^H^H^H^H^H16/31^H^H^H^H^H17/31^H^H^H^H^H18/31^H^H^H^H^H19/31^H^H^H^H^H20/31^H^H^H^H^H21/31^H^H^H^H^H22/31^H^H^H^H^H23/31^H^H^H^H^H24/31^H^H^H^H^H25/31^H^H^H^H^H26/31^H^H^H^H^H27/31^H^H^H^H^H28/31^H^H^H^H^H29/31^H^H^H^H^H30/31^H^H^H^H^H     ^H^H^H^H^Hdone

^[[36mmount NAND partitions^[[m
^[[36minstall bootloader^[[m
sending incremental file list
boot.axf
boot.ini
linux/
linux/linux.ini
linux/u-boot.bin

sent 431418 bytes  received 92 bytes  863020.00 bytes/sec
total size is 431023  speedup is 1.00
sending incremental file list
created directory /mnt/nandb/boot
script.bin
uEnv.txt
uImage

sent 5571477 bytes  received 69 bytes  11143092.00 bytes/sec
total size is 5570561  speedup is 1.00
^[[36minstall rootfs^[[m
sending incremental file list
./
bin/
bin/bash
bin/cat
bin/chgrp
bin/chmod
bin/chown
bin/cp
bin/cpio
bin/dash
bin/date
bin/dd

.......

var/spool/exim4/db/retry.lockfile
var/spool/exim4/input/
var/spool/exim4/msglog/
var/spool/rsyslog/
var/tmp/

sent 525725799 bytes  received 374288 bytes  2499287.82 bytes/sec
total size is 524015203  speedup is 1.00
^[[36msync disk... please wait^[[m
/dev/nanda on /mnt/nanda type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=cp437,iocharset=ascii,shortname=mixed,errors=remount-ro)
^[[36mumounting /dev/nanda^[[m
/dev/nandc on /mnt/nandb type ext4 (rw,relatime,data=ordered)
^[[36mumounting /dev/nandc^[[m
^[[32m**\* Success! remember to REMOVE your SD card from board ***^[[m
 answer yes or no.

I shutdown and remove sd, and initi, but nothing at all.

Thanks in advance

**Comment by BBELLIDO** [comment]
Thanks for yout support!! I have fix it, I reflash nand with livesuit and linaro on  nand, then I reboot cubie with cubian sd, and run cubian-nandisntall, and it works!!   my nand was corrupted I think!!

Please, fix OTG support on cubian!!!

Thanks guys

**Comment by sophana** [comment]
Hi

I also have the same problem. It doesn't work.
I couldn't flash ubuntu with livesuit or phoenixsuit.
I could only flash android
What do you mean by flashing by "reflash nand with livesuit and linaro on nand"

**Comment by cubieplayer** [comment]
This problem has solved.
Closed duplicated with https://github.com/cubieplayer/Cubian/issues/231
