### ISSUE TITLE
/sys/class/gpio directories still not containing appropriate ownership/permissions

### ISSUE THREAD

**Issue by throwcomputer** [cubieplayer/Cubian#17]
r3 fixed top level /sys/class/gpio directory permissions yet when you activate a pin using echo 1 > /sys/class/gpio/export it creates a directory based on the pin activated which then must also contain the same permissions.  This newly activated subdirectory currently does not have correct permissions.

Example:

echo 1 > /sys/class/gpio/export (correct permissions)

----- results in creation of /sys/class/gpio/gpio1_pg0 which returns the ls -l:

total 0
-rw-r--r-- 1 root root 4096 Jun 26 01:31 active_low
lrwxrwxrwx 1 root root    0 Jun 26 01:31 device -> ../../../gpio-sunxi
-rw-r--r-- 1 root root 4096 Jun 26 01:31 direction
drwxr-xr-x 2 root root    0 Jun 26 01:31 power
lrwxrwxrwx 1 root root    0 Jun 26 01:30 subsystem -> ../../../../../class/gpio
-rw-r--r-- 1 root root 4096 Jun 26 01:30 uevent
-rw-r--r-- 1 root root 4096 Jun 26 01:31 value

these folders need to be executable in order to send commands to the GPIO pins as follows:

echo 'out' > /sys/class/gpio/gpio1_pg0/direction
-bash: direction: Permission denied

or

echo 1 > /sys/class/gpio/gpio1_pg0/value
-bash: direction: Permission denied

**Comment by cubieplayer** [comment]
Hi, Thanks for report, I don't know why the newly created folder don't have the correct permission. I will figure it out soon.

**Comment by cubieplayer** [comment]
Someone has found a solution, http://www.raspberrypi.org/phpBB3/viewtopic.php?p=198148#p198148

**Comment by cubieplayer** [comment]
Fixed on newly updated r3 img (md5:404b723b347501f4bfc703ead65810c4). http://cubieplayer.github.io/Cubian/dist/.

**Comment by throwcomputer** [comment]
Great!  Thanks!  I'll test it out later today.
