### ISSUE TITLE
Question about cubian r5 and GPIO

### ISSUE THREAD

**Issue by mehrdad-seno** [cubieplayer/Cubian#171]
Hello,
I'm using cubieboard-1 and cubian r5 installed on sd-card.
Trying to manually work with gpio, I'm getting error:

$echo 23 > /sys/class/gpio/export
-bash: echo: write error: Invalid argument

Is there any other step to activate/work with the gpios?

Thanks

**Comment by Suranto** [comment]
Hi sharpedia, 

please check issue #110 , you should load gpio-sunxi module first.

regards,

@nto

**Comment by mehrdad-seno** [comment]
The mentioned issue resolved the problem. Thanks
