### ISSUE TITLE
Touchscreen not working on A13-lcd43ts

### ISSUE THREAD

**Issue by hargithub** [cubieplayer/Cubian#172]
Hello cubieplayer,

I really appreciate your works on the cubian. The booting time for this image is the fastest among all the image I've been working on Cubieboard2.

When I want to add a touchscreen support for my board, I used A13-lcd43ts before on the olimex A20 debian image for SD Card and the display and touchscreen works like a charm on cubieboard2.

But when I tried it on cubian, the tft display works but the touchpanel isn't. I have recompiled the kernel and module with the sun4i-ts.ko added but haven't got any success with it.

I'm really thankful if you or everyone in this community can give me direction for my problem (or even help me solve it).

**Comment by hargithub** [comment]
Long story short, can add the sun4i_ts.ko module to the touchscreen? I will cross check it with your module.

**Comment by griffinsklo** [comment]
I was able to get the 7" Touchscreen from olimex working using this guide: http://www.dimrobotics.com/2013/06/olinuxino-a13-touchscreen-support-in.html
To get it working inside X I additionally removed libts.so and libts-0.0.so.0 from /usr/lib/arm-linux-gnueabihf and created symlinks to /usr/lib/libts.so for them.

**Comment by hargithub** [comment]
thanks for sharing the information. Will try it and post the result.

**Comment by hargithub** [comment]
I have successfully integrate the A13-lcd43ts display with cubian on cb2 with the link you provide griffinsklo. But on the dependency step (first step) on the guide, I have to add the libtool as it is ask for it on the autoreconf -vi step. (cubian doesn't have it on default)

So the dependency step should be :

aptitude install xorg-dev xserver-xorg-dev x11proto-core-dev git automake make libtool
