### ISSUE TITLE
Reopen #164 issue

### ISSUE THREAD

**Issue by BBELLIDO** [cubieplayer/Cubian#173]
Hello again,

Sorry, but I don't know how reopen the issue.

I have tested it but it doesn't work (i have update linux and make cubian-update succesfully), then I plug a pl2303 device in a usb port and it works (load pl2303 module andlsusb detects it)but I plug the same device in OTG port but it doesn't work (no load module and lsusb don't detect it)

Any suggestion?

Thanks in advance

**Comment by cubieplayer** [comment]
Ok reopen #164
