### ISSUE TITLE
关于a10编译网卡找不到headers目录的问题求助

### ISSUE THREAD

**Issue by deyu260** [cubieplayer/Cubian#175]
root@cubian:/opt/temp/compat-wireless-2012-05-10# make
make -C /lib/modules/3.4.43+/build M=/opt/temp/compat-wireless-2012-05-10 modules
make: **\* /lib/modules/3.4.43+/build: No such file or directory.  Stop.
make: **\* [modules] Error 2
root@cubian:/opt/temp/compat-wireless-2012-05-10# ll /lib/modules/3.4.43+/build
lrwxrwxrwx 1 root root 30 Sep  5 01:27 /lib/modules/3.4.43+/build -> /usr/src/linux-headers-3.4.43+

请问是要到哪里下载这个head？

**Comment by michalliu** [comment]
header暂时没有提供，参见 https://github.com/cubieplayer/Cubian/issues/18
