### ISSUE TITLE
kernel compilation to enable QOS

### ISSUE THREAD

**Issue by devandcom** [cubieplayer/Cubian#177]
I'm developing a server with cubieboard.
I need 2 NIC, to create a simple router.
I tried successfully cubian.
I need to enable QOS in the kernel
I tried to recompile kernel many times, following different howto
Compilation produce files without error, but cubieboard doesn't boot

Do you have a guide for kernel compilation and can you tell me where can i find the correct sources ? 

Regards

Umberto

**Comment by devandcom** [comment]
Another information
I followed this howto : 
https://github.com/cubieplayer/Cubian/issues/39

**Comment by cubieplayer** [comment]
Resolved by https://github.com/mmplayer/sunxi-kernel-config/commit/5582326d2eb8cab92d9ca9bbfe1960b2942c2386
