### ISSUE TITLE
Unable to build V4L-DVB device drivers - Missing kernel-source or kernel-headers

### ISSUE THREAD

**Issue by geptto** [cubieplayer/Cubian#178]
Hi! I'm unable to build the V4L-DVB drivers from linuxtv.org.

I'm following the tutorial from here:
http://linuxtv.org/wiki/index.php/How_to_install_DVB_device_drivers

To be more specific, the exact driver I need can also be found here:
http://linuxtv.org/downloads/firmware/dvb-usb-dib0700-1.20.fw

This driver is for a USB DVB-T TV tuner from DiBcom where the device id is 10b8:1fa0 (not sure if this can help).

Can you help with how can I install kernel-source or kernel-headers?

Thank you for working on Cubian! Great distro!

**Comment by cubieplayer** [comment]
Closed duplicate with https://github.com/cubieplayer/Cubian/issues/18
