### ISSUE TITLE
Cubian for Cubieboard3.

### ISSUE THREAD

**Issue by asprakash** [cubieplayer/Cubian#179]
Dear All,
       I am unable find the Cubian porting for Cubieboard 3.0(cubietruck)?. Kindly let me know if we have any.

Also like to know whether I can get the Cubian source to create the fresh Cubian image.

Thanks in adv,
Prakash.

**Comment by cubieplayer** [comment]
Hi, I'm going to support cb3. But needs to wait a little bit of time.

**Comment by asprakash** [comment]
Thanks for your prompt reply and glad to hear from you. Let me know the Cubian complete source is available for public?. So that I can also contribute since I am also the working on embedded Linux more than 8 years. However, I am new to Cubieboard.

**Comment by cubieplayer** [comment]
Very happy to hear that, are you want the script to create cubian? It's at https://github.com/michalliu/CubieDebian. but it's a bit old. The newer version which i used hasn't pushed to github yet as they are in heavy development. You can contribute your work by following the wiki https://github.com/cubieplayer/Cubian/wiki/Wiki-Index#contribute

**Comment by kasteleman** [comment]
Hi there. Also waiting for support for my cubietruck. Need a betatester?

**Comment by kutschwo** [comment]
Hi there,
I've a cubietruck.
How could i help to port cubian to cubietruck an build a image for a SD Card.

Regards
Wolfgang

**Comment by asprakash** [comment]
Hi Wolfgang,
    Thanks for get back to me. Glad to heard that you have been received
your cubietruck.

I am intended to port debian for cubietruck with xfce. Kindly let me know
if you have any build script to create cubian from scratch for cubietruck.

BTW, I am not yet tried existing cubieboard 2.0 version of cubian on
cubietruck.

Thanks in adv,
-Prakash

**Comment by kasteleman** [comment]
Tried cubieboard 2.0 of cubian on cubietruck. Boots just fine, but indeed as mentioned before no network. Have to find a way around that one.

**Comment by kutschwo** [comment]
That's true, CB2 cubian, boots fine on CB3 except network, because the network chip driver is not compile static in the kernel.
Therfore someone has to build a working kernel an install it into the cb2 cubian SD-card.
I've found on http://docs.cubieboard.org a tutorial to compile the latest kernel on cb1 or cb2.
Combined with a article on http://www.cubieforums.com I’ll try to build a kernel with the proper network chip driver on my cubieboard 2, (cubian with rootfs on a SATA-SSD) and install it on a micro SD card.
This will need some days because i had to wait until my litle son sleeps fine in the evening.
If I'll succeed, I'll post a download link for the kernel files in this forum.
Sorry could only post the kernel files, because my private web-space ist not so big and my DSL-Uplink is not very fast.

Regards from 'Lower Bavaria' http://en.wikipedia.org/wiki/Lower_Bavaria

**Comment by alexdetsch** [comment]
That would be great!
Is it something like that? http://www.pro-linux.de/artikel/2/1572/2,kompilieren-und-installieren.html I mean, install the kernel into the Cubie 2 Image?

Regards from Thuringia ;)

**Comment by kasteleman** [comment]
I think more likely the chinees artikel at cubieboard.org:
http://dl.cubieboard.org/public/users/soloforce/Construct_Your_Own_Debian_Linux_for_CubieBoard_zh-new.pdf
Unfortunately i can't read chinees........

I tried, crosscompiling on my ubuntu 12.04. Almost got there. But forgot
one step so i had no modules. Then i copied the files in nanda (lubuntu
desktop version) to the first partion on my sdcard.
 Next step i did was copie the contents of /boot on nandb to the /boot on
the second partion of the sdcard.
Followed with copy /lib/modules/"kernel version" from nandb to /lib/modules
and /lib/firmware from nandb to /lib/firmware on the sdcard.

Now i have a fresh compleet thin install debian wheezy armhf with ssh
running on my cubietruck.

Gigabit network works fine. Hdparm reports 80 mb/s for 2,5 wd hd. Also 2Gb
ram.

No cedarx at this moment, but i don't need that. Wireless works as wel, but
no bluetooth at this moment.

Now installing lxde and xde logon manager so i can use X11vnc.......

Op dinsdag 3 december 2013 schreef alexdetsch (notifications@github.com):

**Comment by kasteleman** [comment]
Sorry typo: it's xdm logon manager

Op dinsdag 3 december 2013 schreef martin brasse (kasteleman@gmail.com):

**Comment by ghost** [comment]
Hello,
What is current status?

**Comment by kutschwo** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Am 18.12.2013 19:54, schrieb nekoexmachina:

> Hello, What is current status?
> 
> — Reply to this email directly or view it on GitHub 
> https://github.com/cubieplayer/Cubian/issues/179#issuecomment-30869354.
> 
> I'v a working cubian on Cubietruck since Sunday.

Sorry, I'm acutally sick.
I'l complet what I've done, when I'm fit again.

The manual is actually in German only, had to translate it to Englisch.

Best Regards

Wolfgang

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)
Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/

iEYEARECAAYFAlKx+WMACgkQVzb/NjjEH6WqAgCg8Pn8Mge85OllN1kynYJOEpcW
8lAAoLck0eWxI+P78dM1yWtSxuir9CJ4
=Wcu6
-----END PGP SIGNATURE-----

**Comment by alexdetsch** [comment]
Can I have the German manual, please? Its easier for me to read it in German ;)
Thank you!

Alex

**Comment by kasteleman** [comment]
Would be fine for me to as German is my second language.

Op woensdag 18 december 2013 schreef alexdetsch (notifications@github.com):

**Comment by ghost** [comment]
> I'v a working cubian on Cubietruck since Sunday.
> 
> Sorry, I'm acutally sick.
> I'l complet what I've done, when I'm fit again

Thank you  kutschwo for all your work! ^^

**Comment by kutschwo** [comment]
Hello the German BETA-Version of the manual could be fount at the following link.
Hallo zusammen, die BETA-Version der Anleitung findet Ihr unter:
http://www.dingolfing.org/members/kutschi/cubietruck-server.html

Best Regards from Lower-Bavaria
Viele Grüße aus Niederbayern.

**Comment by HLFH** [comment]
@kutschwo Dankeschön. Ich liebe dich <3

**Comment by alexdetsch** [comment]
Hervorragend, Dankeschön!
Probier ich dann über Weihnachten aus.

Alex

EDIT: Unter welchem Linux hast du es denn gemacht? Mein Live-Ubuntu 13.10 32bit meint, es könne die Pakete qemu-user-static und gcc-arm-linux-gnueabihf nicht finden (ja, apt-get update hatte ich)

**Comment by kutschwo** [comment]
Sorry für die Verzögerung.

Ich hab das unter Ubuntu 12.04. LTS AMD 64 gemacht.
Vielleicht fehlen in der /etc/apt/sources.list die universe und multiverse repositories...
Ich würde mir eine Ubuntu richtig installieren, entweder auf eine zusätzliche Platte oder in eine virtuelle Maschine.

Wolfgang

**Comment by ghost** [comment]
Hello again!
How are you?
Can we expect the release in the nearest future? 
:)

**Comment by HLFH** [comment]
Debian is now fully supported for CubieTruck : http://dl.cubieboard.org/software/a20-cubietruck/debian/debieez/

**Comment by alexdetsch** [comment]
Ich habe mal ein Image zusammengebastelt: http://sdrv.ms/1dnLBke (804MB)
weitere Erklärungen dazu hier: http://blog.alex-detsch.de/?p=47

**Comment by cubieplayer** [comment]
sry guys,I'm a little busy in the last two month.
The cb3 cubian image is prepared to release soon.

**Comment by kutschwo** [comment]
Hi cubieplayer,
thanks a lot.
I faild to build a bootable image based on the manual at cubieboard.org
The arm universe is quite differnt to the PC world. :-o

**Comment by InfoSec812** [comment]
So excited for a Debian image for my Cubietruck... I want to run [Ceph](http://ceph.com/) on a series of Cubietruck boards so that I can use it as my expandable file server.

**Comment by cubieplayer** [comment]
Hi everyone, 
Cubian for cubietruck has released! Both text mode and desktop version are available.
Download: http://cubian.org/downloads/
Details: http://cubian.org/2014/02/08/cubian-desktop-released/
