### ISSUE TITLE
3.4.43 Kernel Headers

### ISSUE THREAD

**Issue by conrad-merling** [cubieplayer/Cubian#18]
Is there anyway to install the kernel headers package for version 3.4.43? I can only seem to find the packages for the wheezy version (3.2.0). I'm trying to build a usb wifi driver that's normally in the rt2800usb module. Thanks!

**Comment by cubieplayer** [comment]
Hi, I don't have the kernel header package. But there is a link to the kernel source (3.4.43)
https://github.com/cubieplayer/Cubian/wiki

BTW. Where you download the driver? may be i can compile the driver for you :-)

**Comment by conrad-merling** [comment]
The usb wifi chipset I'm trying to use is RT3070, the driver is available from the manufacturer here http://www.mediatek.com/_en/07_downloads/01-1_windowsDetail.php?sn=5016
After you enter an email address it begins the download. I'm a big fan of Cubian so far, thank you!

**Comment by cubieplayer** [comment]
Hi, I compiled this driver for you, download link http://cubieplayer.github.io/static_files/temp/rt5370sta.ko. I don't own the hardware. so, would you please test it, thanks.

**Comment by maq99** [comment]
Hallo, 
Great Job!
Is it possible to include another wifi driver?
I have problem with my wifi dongle base on Realtek RTL8192SU (drv: rtl8712) 
Don't know where to find src for it. 
I have try to switch to latest kernel from https://www.miniand.com/forums/forums/development--5/topics/linaro-ubuntu-custom-server-images-armhf  (its include my wifi support)  but it does not boot . - any idea why? 
Im newbie in arms world - can you add some docs about booting process. Cubian seams to be different then other distros - I can not find boot partition (confused). 
Thanks!

**Comment by cubieplayer** [comment]
Hi,
You can compile the kernel and driver by yourself. It's not too hard actually. The kernel source for Cubian is here
https://github.com/mmplayer/linux-sunxi

Your wifi dongle's driver i can compile for you tonight. 
I will make something to install the driver online in the future to simplify the process.

If you install cubian on SD card, there is no boot partition,all files needs on booting is locate at `/boot`
If you instal cubian on NAND, there is a boot partition. just executes `sudo mount /dev/nanda /mnt/nanda`(make sure /mnt/nanda is exists), you will see the booting files at `/mnt/nanda`.

**Comment by conrad-merling** [comment]
Thank you very much cubieplayer, I've tried your driver rt5370sta.ko and it works! I haven't been able to get an ip from my router yet, but I don't think that's a driver issue. Thanks!

**Comment by maq99** [comment]
Hallo again,
I get sources and compile this module but unfortunately gets this message after modprobe:
no symbol version for module_layout
<b>ERROR: could not insert 'r8712u': Exec format error</b> 
Wrong libs versions? Doing it (compiling) wrong? (i think that compilation parametes can be wrong.. maybe it it worth to consider to create compilation process description for cubian something simmilar to http://jas-hacks.blogspot.com/2012/10/hackberry-a10-compiling-kernel-armhfs.html )
I made my croscompile similar way: http://lists.debian.org/debian-arm/2012/08/msg00090.htm
also base on those descriptions
http://jas-hacks.blogspot.com/2012/10/hackberry-a10-compiling-kernel-armhfs.html
http://www.debian-administration.org/article/640/Rebuilding_a_single_kernel_module
With native compile i got same result.. Today I will try to recompile whole kernel.
Could you provide me this module? 

Thanks for help

**Comment by maq99** [comment]
Kernel recompilation helps...

**Comment by cubieplayer** [comment]
Hi,
If you really want to learn how to compile the kernel, take a look at this script https://github.com/EddyBeaupre/CubieDebian
In the script, you will get everything you need to compile the kernel.

**Comment by maq99** [comment]
I have added description http://www.cubieforums.com/index.php/topic,327.msg1947.html#msg1947 
Thank you for yours help

**Comment by mazBR** [comment]
cplayer, first of all: fantastic OS!
i'm creating a solution with it already. gps tracking system with other things. the only thing missing right now is the support to my huawei 3g modem(Bus 004 Device 008: ID 12d1:1506 Huawei Technologies Co., Ltd. E398 LTE/UMTS/GSM Modem/Networkcard). I installed modeswitch to bypass the block device in it, but it's not creating the right ttyUSB\* and mounting the modem. there's a way to enable it using 'modprobe usbserial vendor etc..etc" but seems that usbserial module is not compiled, right? can you help me on that? 
regards!

**Comment by cubieplayer** [comment]
Hi maz,
I am not a hardware expert, I think you just need the right driver. If you can provide the driver source, Maybe i can port  it to our kernel to support that chip.

BTW, I am currently working on cubieboard2 and the website, maybe i will not have enough time to solve the driver problem.Later i will work on that.

**Comment by mazBR** [comment]
Cubie, according to some indications(like: modprobe option vendor=0x12d1 product=0x1506 ) seems that the module i need is the 'option'. If you could compile that one, i would appreciate. regards,.

**Comment by wowbvbv** [comment]
I have had try to compile snd-usb-asyncaudio driver for Cubieboard2 with Cubian 3.4.43，but I am stumped。
Here is the Kernel I used "https://github.com/mmplayer/linux-sunxi/tree/dev/sunxi-3.4-a20".
The "make" command always stoped with error..

**Comment by viseu93** [comment]
Hi cubieplayer,

I need to send sms from cubian (cubieborad1), using a usb modem. But when i connect the usb modem to cubieboard1, I can,t see the /dev/ttyUSB\* devices. 

Using dmesg i see:
[ 5891.340000] ehci_irq: port change detect
[ 5891.400000] The port change to OHCI now!
[ 5891.700000] usb 3-1: new full-speed USB device number 2 using sw-ohci
[ 5891.890000] ====usb_stor_huawei_e220_init===>

I think I need usbserial and option modules or recompile the kernel, but i need help with this. 
Please can you help me?

Best Regards
Augusto

**Comment by michalliu** [comment]
Have you tried cubian-update to get the latest kernel and modules?

**Comment by viseu93** [comment]
Yes I run cubian-update.

Thanks

**Comment by ghost** [comment]
hi
could you please also compile garmin_gps.ko for latest a10
Linux Cubian 3.4.43+ #14 PREEMPT Mon Sep 2 02:03:22 CST 2013 armv7l GNU/Linux
thanks in advance!

**Comment by cubieplayer** [comment]
Hi all, I recently make the linux-image and linux-headers. The following packages are provided. remember  run `apt-get update` first
1. linux-headers-3.4.79-sun4i  
2. linux-headers-3.4.79-sun7i
3. linux-image-3.4.79-headless-sun4i
4. linux-image-3.4.79-headless-sun7i
5. linux-image-3.4.79-sun4i
6. linux-image-3.4.79-sun7i

**Comment by cubieplayer** [comment]
I am sorry for waiting too long

**Comment by 10code** [comment]
Hi Cubieplayer,
Can you please help me to install linux-image-3.4.79-headless-sun7i, i need to compile the usbtv utv007 driver module on cubietruck board.

Regards,
Hemanth

**Comment by sourov146** [comment]
Hi Cubieplayer,
can you please help me to solve my cubieboard2 wifi usb dongle problem, i spend 3 days to make it work. tried several process including compile kernel but not succeeded. 

here are the details of my os and dungle-

 uname -a
Linux cubieboard2 3.4.43+ #1 SMP PREEMPT Sat Sep 7 16:45:20 CST 2013 armv7l armv7l armv7l GNU/Linux

lsusb
Bus 004 Device 002: ID 148f:7601 Ralink Technology, Corp.

driver address: https://github.com/art567/mt7601usta

regards,
sourov

**Comment by skamristo** [comment]
Отправлено с iPhone

**Comment by michalliu** [comment]
@skamristo  @sourov146 For wireless driver compilation take a look at
https://github.com/cubieplayer/Cubian/issues/470
