### ISSUE TITLE
on apt-get install nandinstall 404 error

### ISSUE THREAD

**Issue by bakroistvan** [cubieplayer/Cubian#180]
Hi

cubieboard2 & Cubian-base-r2-arm-a20.img.7z  on SD.

i want a nandinstall, but after these command i get a 404 error.
http://packages.cubian.org/pool/main/c/cubian-nandinstall/cubian-nandinstall_1.0-3_all.deb

how to change to search for the new

http://packages.cubian.org/pool/main/c/cubian-nandinstall/cubian-nandinstall_1.0-5_all.deb

please
help me

**Comment by bakroistvan** [comment]
and if i try to apt-get update, the cubieboard2 just shuts down with these message

root@Cubian:~# apt-get update
Get:1 http://security.debian.org wheezy/updates Release.gpg [836 B]
Hit http://security.debian.org wheezy/updates Release
Get:2 http://http.debian.net wheezy Release.gpg [1,672 B]
Get:3 http://packages.cubian.org wheezy Release.gpg [316 B]
Get:4 http://security.debian.org wheezy/updates/main armhf Packages [114 kB]
Get:5 http://http.debian.net wheezy Release [168 kB]
Get:6 http://packages.cubian.org wheezy Release [920 B]
Get:7 http://security.debian.org wheezy/updates/contrib armhf Packages [14 B]
Get:8 http://security.debian.org wheezy/updates/non-free armhf Packages [14 B]
Get:9 http://http.debian.net wheezy/main armhf Packages [5,693 kB]
5% [4 Packages bzip2 0 B] [9 Packages 13.4 kB/5,693 kB 0%] [Waiting for headers

**Comment by cubieplayer** [comment]
`apt-get update` is the correct way

**Comment by bakroistvan** [comment]
yes, while the board do the `apt-get update` command its shut downs itself.

is there any another way?

**Comment by gpascualg** [comment]
I once had this problem with `apt-get update`, or really alike, and got solved by a `ntpdate-debian` run.  Give it a try.
I've noticed `ntpdate` is not always ran on boot, at least on mine, so there are time mismatches.

**Comment by cubieplayer** [comment]
You need to run `apt-get update` to synchronize the software database.
