### ISSUE TITLE
rtl8192cu fix

### ISSUE THREAD

**Issue by derekdhaas** [cubieplayer/Cubian#181]
Still great progress on cubian (best and most stable version around).

If anyone has the rtl8192cu wifi module, to get it working, please blacklist the rtl8192cu driver, since there are 2 (8192cu and rtlwifi/rtl8192cu/rtl8182c_common).

sudo touch /etc/modprobe.d/wifi-blacklist.conf
sudo echo "blacklist rtl8192cu" > /etc/modprobe.d/wifi-blacklist.conf

Now reboot, and your wifi will work. If it's asking for the firmware (dmesg) please do as follows:

apt-get install firmware-realtek

And you're done.

P.s. your current u-boot doesn't include the new cached linux loader. It still waits 10 seconds for me before it's booting. You might want to test the "Patrick Wood 
Linaro Quantal 13.04 developer for A20" (http://cubieboard.cmabreu.com.br/ ) to see how fast it's loading and booting the image.

**Comment by derekdhaas** [comment]
P.s. it's not the boottime itself, but the loading of the zImage that's 10 times faster. I tried to flash patwoods u-boot, but it currently doesn't boot your ROM (can be many things, I haven't got the time to figure it out, but we are hiring a person to get some progress on the cubieboard, and hopefully he will also add some great features to your distro)

**Comment by cubieplayer** [comment]
The new u-boot has been applied to cubian, please check https://github.com/cubieplayer/Cubian/issues/150

**Comment by cubieplayer** [comment]
Closed duplicated with https://github.com/cubieplayer/Cubian/issues/163
