### ISSUE TITLE
how to access uboot partition on Cubian SD Card

### ISSUE THREAD

**Issue by hargithub** [cubieplayer/Cubian#184]
I have my own compiled uboot with some setting for the booting process on it. But I couldn't find any partition with the u-boot.bin on it. For the debian wheezy Olinuxino it always on the 17 MB FAT partition and I just have to change the file with my own uboot.

But where is the FAT/boot partition of Cubian on SD Card ?

**Comment by cubieplayer** [comment]
u-boot is burned into sd-card, so, there is no such file u-boot.bin, see http://linux-sunxi.org/Bootable_SD_card
