### ISSUE TITLE
github里的代码跟cubian-update更新下来的内核不一致

### ISSUE THREAD

**Issue by lanzf** [cubieplayer/Cubian#185]
如题，为什么 @cubieplayer  不能把最新的代码commit呢？

**Comment by michalliu** [comment]
是指内核代码吗？

**Comment by lanzf** [comment]
你有checkout 3.4-a20 这个分支下来吗？ 编译模块还是 3.4.34的 但是 系统update后 是3.4.61的了

**Comment by michalliu** [comment]
使用默认分支sunxi-3.4就可以了呀，你干嘛要用3.4-a20这个分支呢

**Comment by lanzf** [comment]
我的是CB2 弱弱的问一下 不是用a20的吗？

**Comment by michalliu** [comment]
默认分支支持cb2的，用正确的内核配置就好了

**Comment by lanzf** [comment]
可以加你的QQ之类的 即时工具吗？ 求指导
