### ISSUE TITLE
ACPID support on Cubieboard 2

### ISSUE THREAD

**Issue by hargithub** [cubieplayer/Cubian#188]
Is there any updates on the ACPID support for cubian on CB2 ?

I still have no response on acpi_listen for power button clicking even though I have installed acpid, acpi-support-base and powermgmt-base. 

When I start the acpid, it shows : 
RTNETLINK1 answers : no such file or directory
acpid: error talking to the kernel via netlink

**Comment by cubieplayer** [comment]
Hi still in progress
Closed duplicate with https://github.com/cubieplayer/Cubian/issues/102
