### ISSUE TITLE
CubieBoard 2

### ISSUE THREAD

**Issue by VivienGiraud** [cubieplayer/Cubian#19]
Hi,
Are you curently working on CubieBoard 2 ?
Sorry for opening an issue for that, but I haven't find an other way to contact you ...
Best regards
Vivien

**Comment by cubieplayer** [comment]
No problem, m8, feel free to contact me here

The current kernel and u-boot doesn't support A20. But the community is working on that https://groups.google.com/forum/#!topic/linux-sunxi/OQgEkSTwNeA As soon as the kernel released offcially, I will make cubian support cubieboard2.

**Comment by VivienGiraud** [comment]
Great, thank's !

Do you think XBMC(A10) will be compatible A20 without mod ? A10 and A20 are quite similar, they have Mali400 and CedarX both.

**Comment by cubieplayer** [comment]
I believe its compatible. The kernel and driver will handle everything.
