### ISSUE TITLE
Broken audio after last cubian-update

### ISSUE THREAD

**Issue by s-kostyuk** [cubieplayer/Cubian#190]
Good day.

I had made an update to a10-3.4.67_1 cubian version and now ALSA is not working. Rather no ALSA devices is available. Why it's happened? And please fix it. 

/var/log/messages: http://pastebin.com/dagfqFVN, this strings is very remarkable:

```
Nov  4 18:45:16 Cubian kernel: [   15.275751] ALSA device list:
Nov  4 18:45:16 Cubian kernel: [   15.287810]  No soundcards found.
```

MPD log: http://pastebin.com/FMiB8Jri

**Comment by cubieplayer** [comment]
It's confirmed a bug in the sound card driver, solved by this commits https://github.com/mmplayer/linux-sunxi/commit/606d4d10c7b5b50d624e6e7c6ad7f3ebc639bb5a

Later you can update to a10-3.4.67_2 to solve the problem

**Comment by s-kostyuk** [comment]
OK, many thanks. It is working fine now.
