### ISSUE TITLE
rootfs on sata disk

### ISSUE THREAD

**Issue by pizzulicchio** [cubieplayer/Cubian#194]
Is it planned an automated script to "switch" the root fs to an external sata disk using the sata port of my cubieboard? An equivalent of nand-install, but for sata disk, ( like sata-install :-) )
Otherwise, where is possible to find an how to ?

I need to boot from sd card and switch to rootfs on sata.

**Comment by cubieplayer** [comment]
Yes, It's planned.https://github.com/cubieplayer/Cubian/issues/152
