### ISSUE TITLE
How to boot another rootfs

### ISSUE THREAD

**Issue by Mad-ness** [cubieplayer/Cubian#195]
Hi,

I am gentoo fan. I would like to install gentoo's rootfs instead of installed cubian into cubieboard2. 
What I did. I have installed cubian by cubian-nandinstall command after that I loaded gentoo's rootfs by link http://distfiles.gentoo.org/releases/arm/autobuilds/current-stage3-armv7a_hardfp/ and unpacked it to /dev/nandc. Directories /boot and /lib/modules I left original from cubian. In this configuration I have cubian's kernel+modules with gentoo's environment. In further I would prefer to compile the kernel inside gentoo's environment.
But after these steps when I start to run cubieboard2 and see only two cartoon monkeys and no any text messages. About 5 seconds later the monkeys disappear for 5 seconds and appear again, disappear, appear, and so on. I have not any serial ports on my PC so I can't see what output. I have only hdmi output converted to VGA output. When I have unpacked gentoo's rootfs I may chroot inside gentoo and all commands work fine! I have only trouble with booting.
Could you please advice me where I mistake and what I have to do to fix booting process. I also tried install gentoo on the mmc flash card the same way but the result is the same.
I do not see any reasons why debian kernel cannot work with alien environment, if you are, please say your thoughts.

I will appreciate any suggestions.
Dmitriy

**Comment by cubieplayer** [comment]
You should modify `/etc/inittab` in debian, I don't know how to do it in gentoo, something like that maybe. https://github.com/mmplayer/fsupdate/blob/base/common/etc/inittab.patch
This will send the kernel booting messages to serial port. see http://linux-sunxi.org/Cubieboard/TTL.
From your description, I think it's a kernel panic.
