### ISSUE TITLE
Make command ?

### ISSUE THREAD

**Issue by charudatt** [cubieplayer/Cubian#197]
I am trying to install No-ip on CB1 and have to to a situation where I have to issue a Make command.

System responds "Make: command not found"

Anyhelp ?

regards
Charudatt

running r6 on A10 hardware.

**Comment by cubieplayer** [comment]
`make` isn't a preinstalled software on cubian, you need install it manaually. try `apt-get install make`

**Comment by charudatt** [comment]
Thanks Cubieplayer, I managed to install make , but how to install gcc compiler as that's what's required to compile and install. Sorry , a newbie and learning.

regards

**Comment by vtlonn** [comment]
Try the following:
sudo apt-get update && apt-get upgrade
sudo apt-get install build-essential

This should include make, gcc-compiler and other software needed to compile software.
