### ISSUE TITLE
[Cubieboard2]  Full µSD after installation

### ISSUE THREAD

**Issue by Mimoza** [cubieplayer/Cubian#198]
Well i'm testing the new Cubieboard 2 image but i can't install or juste update anything with apt-get. I get this message :

 sudo apt-get install cubian-update
Reading package lists... Error!
E: Write error - write (28: No space left on device)
E: IO Error saving source cache
E: The package lists or status file could not be parsed or opened.

It's  appear  the cache of apt isn't  clean and the list directory too

 ls -l /var/lib/apt/lists/
total 72540
-rw-r--r-- 1 root root   124029 Oct 12 11:10 ftp.debian.org_debian_dists_wheezy_contrib_binary-armhf_Packages
-rw-r--r-- 1 root root   123828 Oct 12 11:10 ftp.debian.org_debian_dists_wheezy_contrib_i18n_Translation-en
-rw-r--r-- 1 root root   175617 Oct 12 11:10 ftp.debian.org_debian_dists_wheezy_contrib_source_Sources
-rw-r--r-- 1 root root 27815606 Oct 12 11:10 ftp.debian.org_debian_dists_wheezy_main_binary-armhf_Packages
-rw-r--r-- 1 root root 18502871 Oct 12 11:10 ftp.debian.org_debian_dists_wheezy_main_i18n_Translation-en
-rw-r--r-- 1 root root 25224286 Oct 12 11:10 ftp.debian.org_debian_dists_wheezy_main_source_Sources
[...]

So it's not a  bug, but resize the next image to have enough space to make just a update will be fine

$ df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs          630M  630M     0 100% /
/dev/root       630M  630M     0 100% /
devtmpfs        405M     0  405M   0% /dev
tmpfs            81M  164K   81M   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           162M     0  162M   0% /run/shm
tmpfs           405M  4.0K  405M   1% /tmp
tmpfs           405M     0  405M   0% /var/tmp

**Comment by cubieplayer** [comment]
More freespaces is needed.  
1. Run `apt-get clean && apt-get install cubian-resizefs`
2. Run `cubian-resizefs /dev/mmcblk0`
After a reboot run `resize2fs /dev/mmcblk0p1`

Tutorial http://cubian.org/2013/08/12/enlarge-cubian-rootfs-partition/

**Comment by bytears** [comment]
i have exactly same problem.
Cubieboard1 + microsd 16g + cubian r6 + Cubian-base-r6-arm-a10.img[724 MB (759,169,024 bytes)]
all the same.
first, i made bootable sd card and inserted to cubieboard.
in first booting, i met the problem.

**Comment by Mimoza** [comment]
@cubieplayer  : Yes i know, i have  see this tutorial. But it's just  a  remark for the next release. It's not fine to install this great  distro without space  to personlise  it.
Well  for µSD card it's easy to resize the partition with gparted (or other)  on  PC and re-run on the board

**Comment by cubieplayer** [comment]
yep, i will fix the problem in next release.

**Comment by mvha** [comment]
We can't 
apt-get install resizefs
or install resize2fs
because we've got 100% used space on rootfs.

Only method is resize the partition using another device or isn't ?

**Comment by cubieplayer** [comment]
@mvha @Mimoza @bytears 
The newest release has fixed the problem. http://cubian.org/2013/11/12/cubian-r7-for-a10-and-r4-for-a20-released/
