### ISSUE TITLE
如何更改第一个分区大小？

### ISSUE THREAD

**Issue by mut0u** [cubieplayer/Cubian#2]
我想让系统容量更大一些，使用的是32G sd卡，第一个分区只使用了1G（貌似），我使用fdisk ,resize2fs 对这个分区进行重新分区后，fdisk显示的块是增加了,但是使用df 检测的时候，空间依然没有增加。因此，扩容失败。

如果我直接将img的第一个分区挂载到我系统上，使用cp 复制所有文件到sd卡第一个分区，cubie无法启动。

如果我dd img第一个分区到sd卡的第一个分区，df显示我使用了非常大的空间。（大概有17G） 

我将这个img文件里面的两个img文件更换位置，然后直接dd到sd卡中，修改fstab文件，系统无法启动。

求教我需要如何解决呢

**Comment by cubieplayer** [comment]
root分区确实有点儿小，这主要是为了照顾2G内存卡的用户，不建议通过分区调整扩容，建议通过挂载目录的方式扩容。后续我会发4G内存卡分区的版本，默认root分区会是3G，应该够用了。

**Comment by cubieplayer** [comment]
r2默认root分区大约为3G，应该足够使用了

**Comment by mut0u** [comment]
能教我一下如何制作这个镜像么？

**Comment by mut0u** [comment]
我也想知道这个其中的原理到底是什么。自己折腾了好几天了。没有一个成功的。我自己更换了两个分区的顺序，将swap放在前面，然后扩展第二个分区，依然失败。然后从网上找了一个，第一个分区正好是 Swap的，然后直接扩容第二个分区，依然是失败。

我也很想知道这其中的原理。

**Comment by cubieplayer** [comment]
我不知道如何扩容，但创建Cubian的脚本是开源的，看一下[Wiki](https://github.com/cubieplayer/Cubian/wiki)，在构建脚本里只要改一个参数就可以了
