### ISSUE TITLE
有没有自动更新？（从Cubie 较低版本升级到较新版本）

### ISSUE THREAD

**Issue by Garfield550** [cubieplayer/Cubian#20]
非要重装？

**Comment by cubieplayer** [comment]
这个功能在计划中了，包括在线安装驱动与更新内核的功能

**Comment by Garfield550** [comment]
那么，图形界面会不会有？

**Comment by cubieplayer** [comment]
图形界面考虑使用lxde，但还没时间弄

**Comment by Garfield550** [comment]
哦，这样的啊，还是谢谢你啦

**Comment by cubieplayer** [comment]
内核和模块可以使用工具更新了
http://cubian.org/2013/08/09/cubian-update-is-available/

**Comment by Garfield550** [comment]
谢谢了！

**Comment by cubieplayer** [comment]
重复 https://github.com/cubieplayer/Cubian/issues/10
