### ISSUE TITLE
UInput support

### ISSUE THREAD

**Issue by gpascualg** [cubieplayer/Cubian#205]
I've been fighting for hours with the kernel to get UInput working.
I'm using `dev/sunxi-3.4-a20` as kernel and I've tried compiling it, but when in the menuconfig, there is not such option under:

Device Drivers  --->
    Input device support  --->
        [*]   Miscellaneous devices  --->
            <M>   User level driver support

I've tried manually setting the option `CONFIG_INPUT_UINPUT`, but it gets overwritten and deleted.

Weird enough, when using cubian, I can see `/usr/include/linux/uinput.h`, though no `/dev/uinput`. Of course, `modprobe uinput` complains about it not existing, and it's not under modules.

How may I do it? Thank you.

**Comment by amelentev** [comment]
3.4.67+ A10 kernel still doesn't have uinput module.
Please add it.
It needed for droidmote server (remote kb/mice): http://www.videomap.it/droidmote-faq.html
