### ISSUE TITLE
hfsplus in Cubian

### ISSUE THREAD

**Issue by ghost** [cubieplayer/Cubian#21]
Hello,

I am using the Cubieboard together with my mac and would like to have my HFS+ formatted media disk attached to Cubieboard that will distrubute it as media server. Could you please compile hfsplus support into the kernel and incorporate HFS+ as standard filesystem to Cubian? On Raspberry Pi that works since some newer version:

https://github.com/Hexxeh/rpi-firmware/commit/c3270ad649659119648b69ac2b9faf6448eca3e3

Cheers!

**Comment by ghost** [comment]
Any news on this? It's a showstopper for me using Cubian with my Mac-formatted disks (i.e. I want to use it for Time Machine Backups).

**Comment by cubieplayer** [comment]
Hi, I will make something like rpi-update to update kernel and modules online. Thanks for the information you provided. I will recompile the kernel with hfs support nearly.

**Comment by ghost** [comment]
Hi cubieplayer,

thanks a lot for your effort. I managed to compile a kernel myself as well, and hfsplus works now like a charm. Anyhow it would be convenient, if hfsplus (not the old hfs module) was available out of the box as there may be many Mac users around.

Great Job!
--A

**Comment by cubieplayer** [comment]
HFS is compiled into kernel for both A10 and A20. Use [cubian-update](http://cubian.org/2013/08/09/cubian-update-is-available) to update to the latest kernel.

**Comment by ghost** [comment]
Thanks! This is great. I will try it out! :-)
