### ISSUE TITLE
Btrfs support

### ISSUE THREAD

**Issue by Mimoza** [cubieplayer/Cubian#214]
Hi,
It's possible to had the Btrfs support to the linux kernel ?
It's seem difficult to compile the 3.4.67 of linux for Debian.
I know Btrfs is experimental file system but have  sympatic feature  ...

**Comment by crackerizer** [comment]
+1 from me

**Comment by hgonzale** [comment]
+1

**Comment by cubieplayer** [comment]
Solved by https://github.com/mmplayer/sunxi-kernel-config/commit/2a77cb08f69221bfe9fdcba96c3e77c32dce2357
