### ISSUE TITLE
Kernel TPM Support

### ISSUE THREAD

**Issue by mzapa** [cubieplayer/Cubian#226]
Is there support for the Atmel AT97SC32041 chip in 3.4.67+?  If not, will it in the future?

TIA

**Comment by mzapa** [comment]
Old eyes & small fonts...  Correct chip is Atmel AT97SC3204T.

**Comment by cubieplayer** [comment]
Problem solved.

**Comment by mzapa** [comment]
tpm_atmel loads but my project calls for a different module.
Requesting support for tpm_i2c_atmel (CONFIG_TCG_TIS_I2C_ATMEL).

Thanks
