### ISSUE TITLE
Kernel - More Modules (DVB-S/2)

### ISSUE THREAD

**Issue by Lolek001** [cubieplayer/Cubian#227]
Hello, please add more Kernel modules to next release - example USB DVB-S/2 (Tevii S660)

thanks

**Comment by ghost** [comment]
and 1wire please!

**Comment by solenskiner** [comment]
I need veth module. Can you please add it to next update or tell me how i can get it myself in the meantime?

**Comment by solenskiner** [comment]
Actually, I would be very happy if the kernel and firmware ware debian packages and source packages managed by apt instead of the cubian-update script.

**Comment by cubieplayer** [comment]
Cubian-update is just a tool to keep your system has the latest kernel and modules support.It's totally different with apt things.

**Comment by solenskiner** [comment]
Updating things is what apt is designed to do. cubian-update seems like a hack to patch over the maintainers lack of know-how of debian packaging. Every debian-derived distro but cubian uses apt for managing the kernel, bootloader and modules.

**Comment by cubieplayer** [comment]
[cubian-update](https://github.com/mmplayer/cubian-packages/blob/master/cubian-update/usr/sbin/cubian-update) is based on [rpi-update](https://github.com/Hexxeh/rpi-update). Maybe it's a good idea using apt to manage the kernel update. Thanks for pointing out this issue.

**Comment by solenskiner** [comment]
I can think of numerous advantages by doing that. For example DKMS for e.g. ZFS-on-Linux once they release an ARM version, or the apt-get source command for local kernel compilation with whatever config the user pleases.

I'm sorry about my tone earlier.

**Comment by cubieplayer** [comment]
No problem mate, I think you are quite right. We should follow [debian policy](http://www.debian.org/doc/debian-policy/) as much as we can.

**Comment by cubieplayer** [comment]
Resolved by https://github.com/mmplayer/sunxi-kernel-config/commit/7160f0f6390d2c587d9454f1a03accc807acccf1

**Comment by Lolek001** [comment]
all works, big thanks...
