### ISSUE TITLE
建议写入nand时默认关闭日志，同时调整分区

### ISSUE THREAD

**Issue by fy0** [cubieplayer/Cubian#23]
nand上使用带日志的ext4非常不利。建议格式化时：
mkfs.ext4 -O ^has_journal $NANDB

此外NANDC挂载在/mnt/nandc 缺乏实际意义，不如并入根分区或者挂成 /opt 或者其他什么东西。

**Comment by fy0** [comment]
export PATH=/sbin:/usr/sbin:$PATH 

希望加入这句话。这样普通账户就不会看不到fdisk halt等等命令了。

**Comment by cubieplayer** [comment]
这两个建议很不错，谢谢分享

**Comment by cubieplayer** [comment]
目前的分区策略的确有问题。计划下次调整一下NAND上的分区。
1. 3G分给rootfs，ext4不带日志。
2. 剩余的给`/home`，ext4带日志，确保home下重要文件不会丢失。
另外会提供修复rootfs的功能，可以在rootfs出问题时可以使用sd卡上的系统进行修复。

**Comment by cubieplayer** [comment]
已经解决 http://cn.cubian.org/2013/07/26/cubian-for-cubieboard1-r4-released/
