### ISSUE TITLE
cubian-nandinstall error

### ISSUE THREAD

**Issue by bobylapointe63** [cubieplayer/Cubian#231]
lib/arm-linux-gnueabihf/libgcrypt.so.11.7.0
rsync: writefd_unbuffered failed to write 4 bytes to socket [sender]: Broken pipe (32)
rsync: write failed on "/mnt/nandb/lib/arm-linux-gnueabihf/libgcrypt.so.11.7.0": No space left on device (28)
rsync: connection unexpectedly closed (16647 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]

I use cubian-nandinstall
i dont't know why i have no space!!!! 

/dev/nanda         16334     404      15930   3% /mnt/nanda
/dev/nandb         15863   15757          0 100% /mnt/nandb

**Comment by ua3prq** [comment]
Hello!
I tried to move a working system Cubian on Nand. The script runs smoothly. After rebooting with Nand I have splash-screen (a piece of green progress bar). 

Here Cubietruck A20 rev.B. Do you have any statistics on problem Nand on rev.B A20? I have long tormented with Nand crash on android and I can not solve the problem. 
The same symptoms began to appear in other users revision B. (CubieboardForum >> Cubieboard itself >> Beginners >> Cubian installation trouble ), forum not ready same days, sorry. 
The problem arises because of the change boot versions from 2 to 3. Here TTY log nand:

"HELLO! BOOT0 is starting!
boot0 version : 3.0.0
...
...
In:    serial
Out:   serial
Err:   serial
--------fastboot partitions--------
mbr not exist
base bootcmd=run setargs_nand boot_normal
bootcmd set setargs_nand
key 0
recovery key high 6, low 4
cant find fstbt value
no misc partition is found
to be run cmd=run setargs_nand boot_normal
the part isn't exist
WORK_MODE_BOOT
WORK_MODE_BOOT
[      7.870]Hit any key to stop autoboot:  3  2  1  0 
cant find part named boot
sunxi_flash - sunxi_flash sub-system

Usage:
sunxi_flash read command parmeters : 
parmeters 0 : addr to load(hex only)
parmeters 1 : the name of the part to be load
[parmeters 2] : the number of bytes to be load(hex only)
if [parmeters 2] not exist, the number of bytes to be load is the size of the part indecated on partemeter 1
boota: bad boot image magic, maybe not a boot.img?
sunxi# "

Today I received a mail with CB2, where there is also installed revision B. Thus problem has already acquired a mass character. SD version work fine.
What do you say about this?

**Comment by cubieplayer** [comment]
Boot0 on A20 has changed, it's close source. It take time to figure out the solution.

**Comment by ua3prq** [comment]
Hi cubieplayer !
I uploaded the files, let's try to work together in Cubieboard Forum.
http://cubieforums.com/index.php?topic=1738.0
If you do not mind?

**Comment by facsi** [comment]
@cubieplayer http://linux-sunxi.org/BROM#Source_code_for_boot0_and_boot1

**Comment by jraymondli** [comment]
I am running into the same issue as ua3prq  described.
What's the solution? 
Thanks,

**Comment by jraymondli** [comment]
I am running into the same issue as ua3prq  described.
What's the solution? 
Thanks,

**Comment by kdeenkhoorn** [comment]
I don't know if it helps but for me cubian-nandinstall also failed therefor i've installed ubuntu for cubietruck using the OTG port first then hijacked it's partitions.

What i have done while booted from SD card:
1) Replace the kernel on /dev/nanda with the version of the SD card.
2) Use nand-part to remove /dev/nandc and extend /dev/nandb to the maximum size followed by a reboot of the cubietruck.
3) Extended the /dev/nandd file system with resize2fs.
4) Use rsync to copy the OS files the way it's done in the script cubian-nandinstall.

Probably it's enough to copy boot0 using dd from the ubuntu distro and overwrite it on the cubian install after cubian-nandinstall is finished.

It is no solution but it works.

**Comment by liguangbz** [comment]
good!
do you mean just 2 partitions, nanda & nandb will work?
failed for me, ;-)
so, could you be more detailed?

**Comment by kdeenkhoorn** [comment]
I have it working with 2 partitions, here's what i did:

First i've made a working install on an 8GB SD card based on the file: Cubian-base-r5-a20-ct.img.7z from www.cubian.org. Just follow the tutorial 'Install to Micro-SD card', play around until you think "this is what i want on my nand drive". At this point I've updated cubian SD with `cubian-update`, don't know if this will make a difference in the following procedure.

Try the tutorial 'Install to NAND' first maybe it works for you out of the box, no harm done here, and if it doesn't here's what i did from this point:
Reminder: the following commands are executed as root ;-)

1) Remove the SD card with the cubian version from the cubietruck and install the file: lubuntu-desktop-nand.img using the OTG port and LiveSuite or an equivalent. I've downloaded ct_lubuntu_desktop_v1.00'.

2) After installing 'lubuntu-desktop-nand.img' on nand, boot once to check if it works, one never knows.

3) Boot from SD card again and start nand-part to change the partitions on /dev/nand, remove the partitions 'rootfs' and 'UDISK' and create one 'rootfs' partition with the maximum available size:

Using:

```
nand-part -f a20 /dev/nand 32768 'bootloader 131072' 'rootfs 14778368'
```

Partition layout before:

```
partition  1: class =         DISK, name =   bootloader, partition start =    32768, partition size =   131072 user_type=0
partition  2: class =         DISK, name =       rootfs, partition start =   163840, partition size =  4194304 user_type=0
partition  3: class =         DISK, name =        UDISK, partition start =  4358144, partition size = 10584064 user_type=0
```

And after:

```
partition  1: class =         DISK, name =   bootloader, partition start =    32768, partition size =   131072 user_type=0
partition  2: class =         DISK, name =       rootfs, partition start =   163840, partition size = 14778368 user_type=0
```

Reminder: 4194304 (rootfs) + 10584064 (UDISK) = 14778368

Answer 'Y' to write the partitions to /dev/nand and then reboot, still from SD.

4) After the system has booted replace the lubuntu kernel with the cubian one from SD and change boot parameters:

```
mount /dev/nanda /mnt
cp /boot/uImage /mnt
```

Edit `vi /mnt/uEnv.txt` and replace `nand_root=/dev/nandc` with `nand_root=/dev/nandb` and change if you want `/mnt/script.bin` using bin2fex. You can also copy the file `/boot/setup.bin` to /mnt in my opinion. I didn't see any important difference.

When finished umount the bootloader partition.

```
umount /mnt
```

5) Now replace the lubuntu installation with the cubian version from SD using rsync. First extend the filesystem on /dev/nandb using:

```
resize2fs /dev/nandb
```

or create new with:

```
mkfs.ext4 /dev/nandb
```

Then mount /dev/nandb and replace it's contents.

```
mount /dev/nandb /mnt
cd /mnt
rm -r *
```

Make exclusions list `vi /root/nocopy` containing:

```
/dev/*
/proc/*
/sys/*
/media/*
/mnt/*
/run/*
/tmp/*
```

Then start os-copy from SD with:

```
rsync -avc --exclude-from=/root/nocopy / /mnt
```

6) After a cup of coffee change `vi /mnt/etc/fstab` the way it will mount '/dev/nandb' as root ('/') and not the '/dev/mmcblk0p1' SD partition.
Like:

```
/dev/nandb  /       ext4    defaults    0   1
/dev/nanda  /boot   vfat    defaults    0   0
```

Reminder, i've added /dev/nanda to fstab to be mounted on /boot, usually this is done with every linux system. This makes it much easier to maintain the boot files.

Now shutdown the system, remove the SD card, and boot again to use nand.

```
shutdown -h now
```

If all went well your smiling now. ;-)

**Comment by michalliu** [comment]
I found a workaround for this problem, from http://www.cubieforums.com/index.php?topic=2023.0

```
* First grab an lubuntu image and flash it via FEL to the NAND
* boot, see if works, shutdown
* boot from your sd-card
* repartition nand with nand-part but DON`T touch the first partition:
Code: [Select]
nand-part -f a20 /dev/nand 32768 'bootloader 131072' 'rootfs 8388608' 'UDISK 6389760'
* create filesystem on second partition
* copy relevant files
* maybe exchange kernel and script.bin on the nand partition
* adopt uEnv.txt to your rootfs: beware! naming changed from nanda, nandb,... to nand1,nand2,...
* boot and enjoy :-)
*
```

**Comment by kdeenkhoorn** [comment]
@michalliu This is more or less the same, you are leaving the 3 partition layout of Lubuntu in tact.
In that case you don't even have to re-partition tough just creating a new clean file-system, thus erasing the existing data, with 'mkfs.ext4 /dev/nandb'  and 'mkfs.ext4 /dev/nandc' is sufficient.
Important is to leave the first MB of /dev/nand untouched, this block contains the bootloader "the beginning of all life"  for the cubietruck. That's why the partitions on /dev/nand start at 32768.

Bare in mind: The /dev/nanda name in your example changed to /dev/nand1 because you you use the Lubuntu kernel. If you install the cubian kernel these names change back to /dev/nanda on first boot.

**Comment by cubieplayer** [comment]
cubian-nandinstall has rewritten, no reboot required, more robust, add supports A20 RevB.
Please update your cubian-nandinstall to v1.1, This problem should be resolved. 
Let me know if you have any problems

**Comment by covek** [comment]
Hi! A cubiebord A20 with factory android firmware (http://dl.cubieboard.org/software/test/cb2-android-factory-VGA.img.gz) and cubian-nandinstall error:

root@Cubian:~# cubian-nandinstall 

 #    #   ##   #####  #    # # #    #  ####  
 #    #  #  #  #    # ##   # # ##   # #    # 
 #    # #    # #    # # #  # # # #  # #  
 # ## # ###### #####  #  # # # #  # # #  ### 
 ##  ## #    # #   #  #   ## # #   ## #    # 
 #    # #    # #    # #    # # #    #  ####  

Your data on /dev/nand will lost, Are you sure to continue?[y/n] y
Re-partitioning NAND device
Check partition table
Formating NAND devices
No device specified!
Usage: mkdosfs [-a][-A][-c][-C][-v][-I][-l bad-block-file][-b backup-boot-sector]
       [-m boot-msg-file][-n volume-name][-i volume-id]
       [-s sectors-per-cluster][-S logical-sector-size][-f number-of-FATs]
       [-h hidden-sectors][-F fat-size][-r root-dir-entries][-R reserved-sectors]
       /dev/name [blocks]

by covek

**Comment by cubieplayer** [comment]
@covek Just re-run cubian-nandinstall, If it's not working, try to reboot then run it again. Let me know if the problem still not resolved.

**Comment by covek** [comment]
ok, if I re-run cubian-nandinstall the script is work but the A20 can not boot from nand. :(

**Comment by cubieplayer** [comment]
@covek Could you attach some log from the serial output?

**Comment by covek** [comment]
Sorry, the a20 board have not, my colage have it. So I can see serial log later.

**Comment by maischus** [comment]
Experienced the same issue as covek. Also had to run the nand-install script twice because it failed the same way as covek.

**Comment by covek** [comment]
Sorry, my colage was install other software, I don't known what, so I not have serial output. :(

**Comment by michalliu** [comment]
The nand install problem finally come to a conclusion. Read http://cubian.org/2014/06/30/troubleshooting-nandinstall-on-a20/

**Comment by kdeenkhoorn** [comment]
@michalliu Have you tried to distribute a new boot0/boot1 image with your nand-install script?
It can be created from a working copy of the first blocks of your own nand drive using:

```
 dd if=/dev/nand of=nand.mbr.img bs=1M count=1
```

For example after you have written the lubuntu install to your own board.
If you want i can supply you my own.

Then the procedure, which is basically a restore after a backup, could be:

1) Use dd to overwrite/erase the first 2mb of the nanddrive with zero's to erase the android bootloader.
2) Use dd to write the new bootloader image, which you have included with your distro ;-), to the first part of the nand drive
3) execute 'sync' to commit the buffers.

After the sync start the nand-part and continue as usual.
I must say i have not tried this myself but this is how it should work when i interpret the manual at: http://sunxi.org/Installing_to_NAND#

If this does not work probably the only way to replace the boot0/boot1 is using the OTG port.

**Comment by michalliu** [comment]
@kdeenkhoorn boot0 and boot1 is beyond /dev/nand. I think we can make a small livesuit image which only contains boot0 and boot1

**Comment by kdeenkhoorn** [comment]
If this is so then why make a live-suite image only containing boot0 and boot1, why not like lubuntu create an image containing the same contents as the basic SD card image but then for use with the OTG port besides the SD card image?
This saves time if you want to use nand storage.
And i think that if you have created an SD card image the OTG image is not far away ...

**Comment by cubieplayer** [comment]
@kdeenkhoorn That's quite true.  I personally don't have much time to learn how to create a livesuit image. If there is any exist script would be nice.

**Comment by kdeenkhoorn** [comment]
@cubieplayer I'm trying to get the pieces together on how to create a livesuit image.
So far i have found out that it takes 3 pieces, a working kernel, a root filesystem and the boot files from the https://github.com/cubieboard/linux-sdk-tools repo. The pack command, form the same tools repo, should combine this together in a livesuit image.
How this command works exactly is yet for me unknown.

What i do know at this point by analyzing the scripts is that you can combine the first 2 steps, so you can use the all ready created image as a base for a livesuit image. So this will not take a lot of adjustments.
I think if you have these pieces at hand the only step missing to get a livesuit image is running the pack command with the right options. If someone can share some info on this pack command i would be thankful.

to be continued ....
