### ISSUE TITLE
Updating kernel

### ISSUE THREAD

**Issue by bublikOff** [cubieplayer/Cubian#232]
Trying to update kernel from 3.4.61+ to the latest, 
apt-get update
apt-get upgrade
cubian-update

After cubian-update Ive got a message that I need to reboot the board and after reboot I see the same kernel version "3.4.61+". In libs I see modules from 3.4.67+.

How to switch kernel?

**Comment by cubieplayer** [comment]
Very wired, actually you can download the kernel from server https://github.com/cubieplayer/cubian-updates, then put to /boot/uImage

**Comment by cubieplayer** [comment]
Answered in https://github.com/cubieplayer/Cubian/issues/233
