### ISSUE TITLE
HELP, need Cubian for cubietruck

### ISSUE THREAD

**Issue by eliacap** [cubieplayer/Cubian#234]
I open this alert in order to apply for a new release Cubian for cubietruck. 
Thank you all for the excellent work done

**Comment by cubieplayer** [comment]
Image for cubietruck is under my test. It will be released soon.

**Comment by eliacap** [comment]
You are the best in the world !!!!
Many thanks !!!!

**Comment by cubieplayer** [comment]
Hi, Cubian for cubietruck has released! Both text mode and desktop version are available.
Download: http://cubian.org/downloads/
Details: http://cubian.org/2014/02/08/cubian-desktop-released/
