### ISSUE TITLE
Please Enable CONFIG_FANOTIFY in kernel

### ISSUE THREAD

**Issue by mzhboy** [cubieplayer/Cubian#235]
I'm testing systemd on debian,
kernel config CONFIG_FANOTIFY=y is recommanded for systemd

https://wiki.debian.org/systemd#Installation
http://eewiki.net/display/linuxonarm/i.MX6x+SABRE+Lite

**Comment by cubieplayer** [comment]
Okay, resolved by https://github.com/mmplayer/sunxi-kernel-config/commit/c80838dcb9c2470eac3653755fd89a2567cbb883
