### ISSUE TITLE
Please build kernel with PPS support for NTPD/GPSD

### ISSUE THREAD

**Issue by seitzbg** [cubieplayer/Cubian#236]
Please build kernel with PPS support for NTPD/GPSD.  The cubieboard would make a great low cost low power NTP server connected to a serial GPS/PPS feed.

**Comment by cubieplayer** [comment]
Sloved by https://github.com/mmplayer/sunxi-kernel-config/commit/c80838dcb9c2470eac3653755fd89a2567cbb883
