### ISSUE TITLE
Kernel 3.4.75

### ISSUE THREAD

**Issue by freegigi** [cubieplayer/Cubian#237]
Can you please update to the latest sunxi kernel 3.4.75?
Thanks for the great distro!

**Comment by cubieplayer** [comment]
Yeah, I had merged the code. A new image will be released soon. Actually you can install the new kernel via apt.

**Comment by freegigi** [comment]
great, thanks!
does this mean that in the future the kernel upgrades will be managed by apt (like they should be in a debian based distro) and not cubian-update?

**Comment by cubieplayer** [comment]
Nope, cubian-update is abandoned soon. The kernel update will be supported via apt-get. I will release the new version contains what you need in a few hours(I'm uploading the image now). You can extract the kernel and module manualy from the image or just wait the kernel package named (linux-image-3.4.75-sun4/7i) to be ready.

**Comment by paulalting** [comment]
Many thanks for this distro cubieplayer, you have done a great job with it.
Looking forward to installing this new image to nand, so I can learn more and continue playing with my Cubian Cubieboard2 as a headless server connected to Arduino EtherMega.

**Comment by cubieplayer** [comment]
I suggest you install the package `linux-image-3.4.79-headless-sun4i` or `linux-image-3.4.79-headless-sun7i` depending on what board you have. The headless kernel can release about 50M memory for you.

You should aslo add `sunxi_g2d_mem_reserve=0` to your kernel commandline
