### ISSUE TITLE
i2cdetect give incomplete xfer on A10 cubieboard

### ISSUE THREAD

**Issue by miky2k** [cubieplayer/Cubian#238]
fresh  installed cubian 
i2cdetect -l give four i2c buses (3 + hdmi).
all buses give me after i2cdetct -l 
incomplete xfer (0x48) or (0x20).

**Comment by cubieplayer** [comment]
i2s is disabled by default in script.bin, because it's conflict with SATA. see  [this commit](https://github.com/mmplayer/sunxi-boards/commit/7bb2feaaf6257eee80d7896c095482ec01952ad8#diff-33c130ace86127ccf8a58a380bae3e89) You need to enable it manually.

See also: http://linux-sunxi.org/Fex_Guide

**Comment by miky2k** [comment]
Ok . all three channels ? 
The problem is not related to hardware or disabled i2c channel (that are enabled because there is no hardware conflict on channel i2c 0 or 1 and pmu is on channel 0!).
incomplete xfer (0x20) is kernel message that in serial console messup output of i2cdetect, if i attach with ssh i2c give me correct output  :
miky@cubie21:~$ i2cdetect 1
WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will probe file /dev/i2c-1.
I will probe address range 0x03-0x77.
Continue? [Y/n] 
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- 48 -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         

48 is my i2c device !!!
but why kernel give incomplete trasfer ?
[62070.001112] incomplete xfer (0x20)
[62070.004098] incomplete xfer (0x20)
[62070.007042] incomplete xfer (0x20)
[62070.010158] incomplete xfer (0x20)
