### ISSUE TITLE
Cubian a10 image username and password

### ISSUE THREAD

**Issue by venkateshg** [cubieplayer/Cubian#239]
Hi ,
    I have written A10 cubian board portal image on SD card using windows img writer.After  board boot up it's asked for Cubian login and Password.Anybody know username and Password details please share me.

Thanks n Advance
Raj

**Comment by s-kostyuk** [comment]
cubie/cubie. For details see here: https://github.com/cubieplayer/Cubian/wiki/Get-started-with-Cubian
