### ISSUE TITLE
How to enable UARTs

### ISSUE THREAD

**Issue by paulalting** [cubieplayer/Cubian#240]
I would like to connect my Cubieboard2 to my Arduino via TTL serial.
Currently I have Cubian r4 installed in nand.

How can I enable an additional UART that is available to the pins on the header?
I just need Rx and Tx to connect to the UART on my Arduino Due which is also 3v3.

Do I need to modify the FEX file?
If so I am having trouble with its make process with a issue with, 'libusb.h' not being found. I also read the FEX file is no longer needed, is this correct?

I just wish for a TTL serial port I can use with python or Node.js on my Cubieboard to talk to the outside world.

Any help is much appreciated.
Paul

**Comment by michalliu** [comment]
I don't have such experence, May be someone here will help you.

**Comment by cubieplayer** [comment]
Problem solved. see https://github.com/cubieplayer/Cubian/issues/18
