### ISSUE TITLE
A10 最新版 负载不正常.

### ISSUE THREAD

**Issue by kvmba** [cubieplayer/Cubian#241]
今天更新了下CB系统 ,A10的. 更新后负载一直不正常,一直在1.0左右,io CPU 貌似都正常.
怎么回事儿呢? 
QQ: 314286223

**Comment by iamgongdao** [comment]
我也遇到了这个问题
这是我的解决办法：
1/参照这个连接：
http://forum.cubietech.com/forum.php?mod=viewthread&tid=141
把script.bin  转成 script.fex 
2/参照这个连接：
http://www.cubieforums.com/index.php?topic=1084.0
将 script.fex 中的：
usb_det_vbus_gpio = port:PH17<1><0><default><0> 
改成：
usb_det_vbus_gpio = "axp_ctrl"
3/再将 script.fex 转回script.bin 放回远处 （/boot/script.bin）
4/重启

**Comment by kvmba** [comment]
ok. Thanks.

**Comment by cubieplayer** [comment]
抱歉，这个问题的存在我很早就发现了，参见 https://github.com/cubieplayer/Cubian/issues/164 所以在原来的内核是不包含OTG驱动的，所以这个问题就不存在。

新内核中包含了OTG驱动，我专门对fex[进行了修改](https://github.com/mmplayer/sunxi-boards/commit/1a25403327eae516a5826e46baca1bab349e001a#diff-33c130ace86127ccf8a58a380bae3e89)，但是对A10的修改忘记删掉旧的那一行了，导致此问题。

手动的修复方法是修改script.bin，修改这个文件的方法如2楼说的，把script.bin弄成fex后删掉usb_det_vbus_gpio = port:PH05<0><0><default><default>这一行，再转回script.bin就可以了。

注意：删掉这一行后OTG是不能用的。也就是说
usb_det_vbus_gpio = "axp_ctrl"
usb_det_vbus_gpio = port:PH05<0><0><default><default>
只能2选1，使用axp_ctrl不会有load average显示很高的问题。但是用不了OTG。使用下面那个，可以使用OTG，但是不使用OTG时系统会有负载虚高的问题，这个问题是在驱动层。

**Comment by kvmba** [comment]
谢谢
