### ISSUE TITLE
A couple things

### ISSUE THREAD

**Issue by VonGriffin** [cubieplayer/Cubian#242]
First of kudos for all the hard work, its really appreciated 

It seams it cant display the 1920x1080 resolution; if i use the hdmi when starting the board the thing just restarts and cant boot; if i plug hdmi after boot is done, the thing works fine at  1280x 720

Is it possible to move cubian from SDcard to the Sata disk ? im a nublet here so bare with me

**Comment by cubieplayer** [comment]
The screen things discussed here https://github.com/cubieplayer/Cubian/issues/246

There is no tools to transfer system to SATA yet. Here is a guide http://docs.cubieboard.org/tutorials/ct1/installation/install_lubuntu_desktop_or_server_rootfs_to_sata_drive?s[]=sata
