### ISSUE TITLE
无法安装到nand。

### ISSUE THREAD

**Issue by wikeyi** [cubieplayer/Cubian#245]
最新的ct版本无法安装到nand里面。

**Comment by michalliu** [comment]
Cubietruck有A和B两个版本

## A版

![Cubietruck A版](http://docs.cubieboard.org/_media/hardware/others/a20-version-a.png)

## B版

![Cubietruck B版](http://docs.cubieboard.org/_media/hardware/others/a20-version-b.png)

怀疑可能是B版的Cubietruck才有此问题，经测试A版的Cubietruck是可以的

**Comment by wikeyi** [comment]
之前发帖说的那个debian的版本，他用的脚本可以安装到我发现问题的板子上。
http://cubieforums.net/index.php/topic,1275.0.html
1.6版本可以直接装到我的ct3，nand上面。
不知道能不能拿来主义然后改改。
wikeyi发自 iCloud

2014年2月18日 下午05:28，michalliu notifications@github.com 写道：

Cubietruck有A和B两个版本

B版的boot1启动代码里可能有额外的东西导致，uboot nand启动不成功，A版的Cubietruck是可以的

**Comment by danielfree** [comment]
我在 rev.B 的 ct3 上刷到nand上也无法运行，cubian-nandinstall 可能只支持rev.A，英文论坛上相关的讨论 
http://www.cubieforums.com/index.php?topic=2052.0 
http://www.cubieforums.com/index.php?topic=2023.0

**Comment by cubieplayer** [comment]
Hi,
这个问题已经修复了，用apt更新一下cubian-nandinsall再试试
