### ISSUE TITLE
cubietruck VGA 1920x1080 broken

### ISSUE THREAD

**Issue by h3ndrik** [cubieplayer/Cubian#246]
Hi, VGA mode 10 (1920x1080) is broken in Cubian-desktop-r1-a20-ct.img.7z
It doesn't boot and keeps switching the monitor on and off.
Mode 4 (VGA) works.
Did work in previous releases.

**Comment by ua3prq** [comment]
A similar problem. Desktop version did not go on CT A20 rev.B. 
Cubian-base-r5-a20-ct.img work fine.

**Comment by h3ndrik** [comment]
Some Idea about what causes this?
Seems the board is stuck in some kind of bootloop.

**Comment by ua3prq** [comment]
Hello. 
I will try soon to get log TTY on rs-232. Maybe this will clarify the situation.

**Comment by avizero** [comment]
my cubietruck restarts when connecting to hdmi and 1920x1080 resolution. 720p on all OK

**Comment by cubieplayer** [comment]
Hi, All,
You can solve the problem change uEnv.txt `sunxi_fb_mem_reserve` to 16 to see if the problem solved. If not change to 32.

The default is 11, it reserved memory enough for 720p screen but not enough for 1080p screen.

**Comment by cubieplayer** [comment]
Another way is upgrade your kernel to 3.4.79, you can try
`
apt-get update
apt-get install linux-image-3.4.79-sun4i (or sun7i depends on your board)
`
3.4.79 supports CMA, so you don't need reserve any meomory, the driver will take whatever it wants.

**Comment by avizero** [comment]
Thanks, it worked!

**Comment by h3ndrik** [comment]
Nice. However, installing linux-image-3.4.79-sun7i does not work.
Seems the package "missing-firmware" is missing:

```
Setting up linux-image-3.4.79-sun7i (3.4.79) ...
Running depmod.
Error setting debconf substitutions in linux-image-3.4.79-sun7i/postinst/missing-firmware-3.4.79-sun7i: linux-image-3.4.79-sun7i/postinst/missing-firmware-3.4.79-sun7i doesn't exist at /var/lib/dpkg/info/linux-image-3.4.79-sun7i.postinst line 683, <STDIN> line 3.
dpkg: error processing linux-image-3.4.79-sun7i (--configure):
 subprocess installed post-installation script returned error exit status 255
´´´
```

**Comment by cubieplayer** [comment]
Ok, I'll check the problem. It now fixed.
