### ISSUE TITLE
can't get any visual ouput on hdmi

### ISSUE THREAD

**Issue by radagasp** [cubieplayer/Cubian#25]
Hi, 

thanks for a great image. I installed it on my sd card and booted up the cubiboard, I can ssh in just fine, my big problem is I would like to connect the board up to my screen - I have an hdmi cable. I tried this, but the screen just says there is no signal.

**Comment by cubieplayer** [comment]
It's abnormal. It should have HDMI output. What's the best resolution of your screen?

**Comment by radagasp** [comment]
Hi, 

when I power up the board, the screen just says "no signal". When I use bootberry, the screen works fine. 
The screen is an LG TV screen, I don't know how to find the resolution, but the screen is larger than most desktop screens.  Below is the contents of uEnv.txt:

boot_mmc=fatload mmc 0 0x43000000 ${fexfile}; fatload mmc 0 0x48000000 ${kernel}; bootm 0x48000000
extraargs=rootwait
fexfile=cubieboard.bin

Thanks for your help.

**Comment by radagasp** [comment]
Ok, I have read some forums, they tell me I need to flash the cubian to nand, as it is not an sd image... is this what might be causing my problems? If I flash to nand will I lose the android it comes shipped with?

**Comment by cubieplayer** [comment]
No, Cubian supports both SD card and NAND, read the [WIKI](https://github.com/cubieplayer/cubian/wiki/Install-Cubian). If you install Cubian to SD card, The u-boot will read a file called `boot.scr`, It's compiled from `boot.cmd` on the first partition of your SD card.

The following command can compile `boot.cmd` to `boot.scr`

```
mkimage -C none -A arm -T script -d boot.cmd boot.scr
```

The content of `boot.cmd` is

```
setenv bootargs console=tty0 console=ttyS0,115200 hdmi.audio=EDID:0 disp.screen0_output_mode=EDID:1280x800p60 root=/dev/mmcblk0p1 rootwait panic=10
ext2load mmc 0 0x43000000 boot/script.bin
ext2load mmc 0 0x48000000 boot/uImage
bootm 0x48000000
```

**Comment by radagasp** [comment]
I have followed these instructions but with no change.

**Comment by zerodamage** [comment]
@radagasp if not resolved yet: change resolution in boot.cmd under disp.screen0_output_mode to something suitiable for a TV, perhaps
1280x720p60

**Comment by cubieplayer** [comment]
Check your power cable or HDMI cable?
