### ISSUE TITLE
RT5572 and linux-headers

### ISSUE THREAD

**Issue by estevesd** [cubieplayer/Cubian#255]
I did a cubian-update on A10 so now I'm on 3.4.75.
Since it's not in the kernel, I'm trying to compile module rt2870 for a wifi usb dongle based on Mediatek RT5572.
but it says  : make: **\* /lib/modules/3.4.75-sun4i/build: Not a directory.  Stop.
I tried to install linux-headers but of course I can't find the good version.
Is there a solution for that issue?
Will I need to compile the kernel myself, or I just need to wait for a new cubian version?

**Comment by michalliu** [comment]
Run apt-get update, linux-headers is available

**Comment by estevesd** [comment]
I did
$ apt-get update
$ apt-get upgrade
$ cubian-update
$ uname -r
3.4.75-sun4i
$ apt-cache search linux-headers*
linux-headers-3.2.0-4-all - All header files for Linux 3.2 (meta-package)
linux-headers-3.2.0-4-all-armhf - All header files for Linux 3.2 (meta-package)
linux-headers-3.2.0-4-common - Common header files for Linux 3.2.0-4
linux-headers-3.2.0-4-mx5 - Header files for Linux 3.2.0-4-mx5
linux-headers-3.2.0-4-omap - Header files for Linux 3.2.0-4-omap
linux-headers-3.2.0-4-vexpress - Header files for Linux 3.2.0-4-vexpress
linux-headers-2.6-mx5 - Header files for Linux mx5 configuration (dummy package)
linux-headers-2.6-omap - Header files for Linux omap configuration (dummy package)
linux-headers-mx5 - Header files for Linux mx5 configuration (meta-package)
linux-headers-omap - Header files for Linux omap configuration (meta-package)
linux-headers-vexpress - Header files for Linux vexpress configuration (meta-package)
linux-headers-3.4.79-sun4i - Header files related to Linux kernel, specifically,
linux-headers-3.4.79-sun7i - Header files related to Linux kernel, specifically,

So no 3.4.75-sun4i and if I install linux-headers-3.4.79-sun4i , I can't see anything new in /lib/modules

**Comment by rigo88** [comment]
same here. no headers for 3.4.75-sun4i. only for 79.
any repo or source for headers 75?

wondering why on earth using a kernel which has no easy-to-get headers at all? i have a cubieboard1, tried ALL the available images not even one runs kernel with apt-get installable headers. why please why? upgrading the kernel is a pain too, more like impossible. (since there is no grub-like bootorderselector)
any solutions? any ideas how to install a driver which is not in the kernel?

**Comment by michalliu** [comment]
I recommend upgrading to 3.4.79 by using either cubian-update or apt-get. The newer, the better.
Sadly, Cubian is the only distro provide kernel packages.

**Comment by pato89xd** [comment]
When i try to build something I get this "make: **\* /lib/modules/3.4.79-sun4i/build: No such file or directory.  Stop." so I looked into that directory and this is what is in there 
 build -> /home/michal/CubieDebian/linux-sunxi-a10

can someone explain me this symbolic link?

**Comment by angrywasp** [comment]
Can you please tell me if there is a workaround to this issue?

**Comment by pato89xd** [comment]
sorry, i solved this by installing linux headers and linux image, but now  when I try to compile the drivers for the rtl8188eu i got this log
make ARCH=arm CROSS_COMPILE= -C /lib/modules/3.4.79-sun4i/build M=/home/cubie/De sktop/usb/rtl8188eu-master modules
make[1]: Entering directory /usr/src/linux-headers-3.4.79-sun4i' CC [M] /home/cubie/Desktop/usb/rtl8188eu-master/core/rtw_ap.o In file included from include/linux/timex.h:174:0, from include/linux/jiffies.h:8, from include/linux/ktime.h:25, from include/linux/timer.h:5, from include/linux/workqueue.h:8, from include/linux/slub_def.h:12, from include/linux/slab.h:185, from /home/cubie/Desktop/usb/rtl8188eu-master/include/osdep_ser vice.h:34, from /home/cubie/Desktop/usb/rtl8188eu-master/core/rtw_ap.c:22: /usr/src/linux-headers-3.4.79-sun4i/arch/arm/include/asm/timex.h:15:24: fatal er ror: mach/timex.h: No such file or directory compilation terminated. make[2]: **\* [/home/cubie/Desktop/usb/rtl8188eu-master/core/rtw_ap.o] Error 1 make[1]: **\* [_module_/home/cubie/Desktop/usb/rtl8188eu-master] Error 2 make[1]: Leaving directory/usr/src/linux-headers-3.4.79-sun4i'
make: **\* [modules] Error 2

**Comment by oguska** [comment]
Same problem here to compile asix ax88179_178a driver module.

 sudo make
make -C /lib/modules/3.4.79-sun4i/build SUBDIRS=/home/cubie/asix modules
make[1]: Entering directory `/usr/src/linux-headers-3.4.79-sun4i'
  CC [M]  /home/cubie/asix/ax88179_178a.o
In file included from include/linux/timex.h:174:0,
                 from include/linux/jiffies.h:8,
                 from include/linux/ktime.h:25,
                 from include/linux/timer.h:5,
                 from include/linux/workqueue.h:8,
                 from include/linux/kmod.h:26,
                 from include/linux/module.h:13,
                 from /home/cubie/asix/ax88179_178a.c:30:
/usr/src/linux-headers-3.4.79-sun4i/arch/arm/include/asm/timex.h:15:24: fatal error: mach/timex.h: No such file or directory
compilation terminated.
make[2]: *** [/home/cubie/asix/ax88179_178a.o] Error 1
make[1]: *** [_module_/home/cubie/asix] Error 2
make[1]: Leaving directory`/usr/src/linux-headers-3.4.79-sun4i'
make: **\* [default] Error 2

**Comment by cubieplayer** [comment]
The header package has been fixed. I compile this wifi driver without any problem. Please upgrade your header package to latest version.

**Comment by diemlt4** [comment]
what is your kernel version, cubieplayer ?
I have the same problem with version 3.4.75. So could I use a different kernel header version compare to kernel version ?
