### ISSUE TITLE
为什么没有bzip2 & make命令？

### ISSUE THREAD

**Issue by wolfan** [cubieplayer/Cubian#256]
Cubian怎么不把bzip2 and make 带上？这两个工具非常重要啊，应当自带上啊。

**Comment by michalliu** [comment]
这种可以自己apt-get吧，bzip2预装是可以的，make不太通用

**Comment by wolfan** [comment]
bzip2没有啊，我解了N次没成，apt-get后才成功的。

**Comment by cubieplayer** [comment]
bzip2 can be installed via apt easily
