### ISSUE TITLE
ownCloud应该怎么装？

### ISSUE THREAD

**Issue by dmxcsnsbh** [cubieplayer/Cubian#258]
为了装这个 ownCloud 费了我好多精力 可是还是装不好T T
看了好多文档还是失败 伤心……
哪位仁兄也试着装装看 看看会不会有问题T T

**Comment by electrocret** [comment]
I have installed own cloud on my cubian cubieboards without any problems. I found it extremely slow. I would suggest using Seafile instead. Much better performance. http://seafile.com

**Comment by dmxcsnsbh** [comment]
Thanks a lot ^-^
I'll try

**Comment by cubieplayer** [comment]
Please heck the documentation about Owncloud.
