### ISSUE TITLE
Cubian Latest version and network activity

### ISSUE THREAD

**Issue by facsi** [cubieplayer/Cubian#259]
Why cubian in this latest version is using internet when i am not using it? I closed ALL aplications and it still was using the internet for something... What the heck is going on? Its using almost 1Mb of my internet!!

**Comment by electrocret** [comment]
NTP possibly?

**Comment by facsi** [comment]
Deactivated and still... Does yours do the same?

**Comment by electrocret** [comment]
I don't monitor how much of my internet its using. Just curious, where did you find how much of your internet it's using?

**Comment by facsi** [comment]
First I noticed the yellow light blinking in cubieboard and then its syncronization with the WAN led in my router. Im using dd-wrt and i could check the bandwidth it was using.

Edit: Sorry the unit was kbit and I thought it was kbyte and multiplied by 8. The usage is around 120kbit/s

**Comment by facsi** [comment]
It seems the culprit was transmission with those DHT and PEX settings enabled.
