### ISSUE TITLE
kernel source package missing on packages.cubian.org

### ISSUE THREAD

**Issue by viperidae** [cubieplayer/Cubian#261]
the kernel package  linux-image-3.4.79-sun7i lists its source as linux-source-3.4.79-sun7i but that package is nowhere to be found.

In trying to compile a driver the header package doesn't work. It has CONFIG_ARCH_HAS_BARRIERS set, which causes barrier.h try to include the missing file mach/barriers.h

**Comment by guruz** [comment]
Have you run `cubian-update` ? I have `linux-headers-3.4.79-sun7i` installed, however i'm also having this issue when trying to compile ndiswrapper

```
In file included from /usr/src/linux-headers-3.4.79-sun7i/arch/arm/include/asm/domain.h:14:0,
                 from /usr/src/linux-headers-3.4.79-sun7i/arch/arm/include/asm/thread_info.h:28,
                 from include/linux/thread_info.h:53,
                 from include/linux/preempt.h:9,
                 from include/linux/spinlock.h:50,
                 from include/linux/seqlock.h:29,
                 from include/linux/time.h:8,
                 from include/linux/ktime.h:24,
                 from include/linux/timer.h:5,
                 from /var/lib/dkms/ndiswrapper/1.57/build/ntoskernel.h:20,
                 from /var/lib/dkms/ndiswrapper/1.57/build/crt.c:16:
/usr/src/linux-headers-3.4.79-sun7i/arch/arm/include/asm/barrier.h:41:27: fatal error: mach/barriers.h: No such file or directory
```

**Comment by viperidae** [comment]
I had already updated it.
It's like there are missing files in the header package, like it was packaged as if CONFIG_ARCH_HAS_BARRIERS was not set, but it is.

**Comment by michalliu** [comment]
kernel source package are avaible now! try apt-get install linux-source-3.4.79-sun7i

**Comment by qvixote** [comment]
Any progress on this problem? I'm trying to compile a driver and get the same error, related to missing mach/barriers.h, even when I have linux-source-3.4.79.sun7i
