### ISSUE TITLE
Systemd : Failed to get D-Bus connection: No connection to service manager.

### ISSUE THREAD

**Issue by HLFH** [cubieplayer/Cubian#264]
Hi,

When I'm executing systemctl, I have this issue :

> Failed to get D-Bus connection: No connection to service manager.

systemd and systemd-sysv are installed.

**Comment by HLFH** [comment]
My bad. I forgot to install systemd-sysv !

**Comment by Ropes** [comment]
@HLFH thanks for leaving your fix for those of us stumbling along in your footsteps!
