### ISSUE TITLE
Problem with cubie-nandinstall and Cubieboard-2

### ISSUE THREAD

**Issue by DavidGoodenough** [cubieplayer/Cubian#269]
I have just got a Cubieboard-2, built the SD card and booted it.  I then tried to use cubie-nand-install and it went through its two phases apparently correctly.

However when I take out the SD card and try to boot from nand, it fails.  Connecting a serial console I get a message that the boot partition can not be found.

So I rebooted with the SD card and the NAND partitions are there, but parted says it can not find the disk label for /dev/nanda.  Presumably this should be boot?  

I am using Cubian-base-r5-a20 as my SD card image.

Eventually I want to move to booting from the SATA drive, but I think I still need the NAND boot to work as that is where it will load uBoot from.

David

**Comment by electrocret** [comment]
This is a known issue with revision B of the A20 processor. an Issue already exists for it. https://github.com/cubieplayer/Cubian/issues/231

You may also want to read: http://www.cubieforums.com/index.php?topic=1880.30

**Comment by BerndKa** [comment]
I have the same issue with Cubian-desktop-r1-a20 on my Cubieboard 2.
Trying booting from nand it seems that

```
           boot0 version : 3.0.0 does not find the boot partition.
```

@electrocret 
The hint on  http://www.cubieforums.com/index.php?topic=1880.30 did not work with my cubieboard.

Bernd

**Comment by BerndKa** [comment]
I found out, that the hint (setting machid=0x000010bb in the uEnv.txt file) in the above link works fine withe boot version 2.0.

After using an older version of nandinstall wich i found at https://github.com/mmplayer/nandinstall I could clone the Cubian-desktop-r1-a20 image to nand. Cubian is now booting from nand.

Bernd

**Comment by ThunderBRZ** [comment]
BerndKa

Please... write a TODO 4 this... I need a help to work here

Many thx

**Comment by BerndKa** [comment]
Ok, I gonna try to write a TODO.
1. Install Cubian on your SD-Card and start it.
2. Backup your nand, especially the partitiontable, bootrecord and your data. For details look at:    http://linux-sunxi.org/Installing_to_NAND#Backup_NAND
3. Git clone the nandinstall repository form mmplayer at github, change to the nandinstall directory and checkout the a20 branch:
    sudo git clone https://github.com/mmplayer/nandinstall 
    cd nandinstall
    sudo git checkout a20
4. edit the install script install.sh
   replace the lines
   NANDA="/dev/nand1"
   NANDB="/dev/nand3"
   by
   NANDA="/dev/nanda"
   NANDB="/dev/nandc"
   and save the script.
   
   Make sure, the directories /mnt/nanda and /mnt/nandb do exist. If not create them.
   
   ! check your backup
   you gonna loos all data in your nand starting the install script
5. start the install script in the nandinstall directory as root:
    su
    ./install.sh
    this will change the nand partitiontable 
    reboot your cubie from SD-card
6. change to the nandinstall directory and start the install script again
   cd nandinstall
   su
   ./install.sh
   this will format the nand, copy the bootloader to the nand and create the root filesystem on the nand by rsync all the relevant directories form the SD-card. Finaly the script adds an entry for the nand to /etc/fstab
7. Mount the nand and change uEnv.txt. You schould add the machid and change the root drive.
   sudo mount /dev/nandc /mnt/nandb
   sudo nano /mnt/nandb/boot/uEnv.txt
   add the folowing line at the beginning of the file
    machid=0x000010bb
   change the entry for the root directory to:
    root=/dev/nandc rootwait
   save the file.
   1. Synchronise the files to ensure all data were written to the nand.
      sync
      wait a few (5 to 30) seconds and unmount the nand.
      sudo unmount /dev/nandc
      remove your SD-card and reboot
   2. If everything worked fine the cubie should boot from NAND!

Hope I did not forgot a step. Please give me feedback, if you get along with this.

**Comment by liguangbz** [comment]
failed for me, no output from UART,
follow you step by step,
many questions for this install.sh,
e.g. what's echo 'Android ... ' >  /dev/nand2 ?
and, what's the content of your uEnv.txt?

**Comment by cubieplayer** [comment]
This problem has solved.
Closed duplicated with https://github.com/cubieplayer/Cubian/issues/231
