### ISSUE TITLE
compiling kernel modules

### ISSUE THREAD

**Issue by radagasp** [cubieplayer/Cubian#27]
Hi, 

I want to compile the batman-adv routing kernel module on my cubian system. But I believe I need the kernel headers for /lib/modules/x.y.z/build.

How do I get these?

**Comment by cubieplayer** [comment]
Hi, you can clone the entire kernel source. look at https://github.com/cubieplayer/Cubian/wiki

**Comment by radagasp** [comment]
Thanks I did all this, and compiled my own kernel using the Cubieboard.sh script. However it is not booting. Do I need to create my own boot partition?

**Comment by cubieplayer** [comment]
I will write a tutorial talk about how to compile software and kernel for Cubian.Basiclly, I guess you didn't use the correct toolchain, I suggest you use my Toolchain which is:

https://github.com/cubieplayer/Toolchain/tree/arm-2010.09

Then just export a environment variable point to the bin folder, eg.

```
export PATH=${TOOLCHAIN}/bin:$PATH
```

To compile the kernel you need 
1. checkout the sunxi-3.4 branch. cd to `linux-sunxi`,then `git checkout sunxi-3.4`
2. copy my [kernel config](https://raw.github.com/mmplayer/sunxi-kernel-config/master/config-cubian-base-sun4i) rename to .config put to the root folder of `linux-sunxi`

Now start compile kernel

```
 make -C ./linux-sunxi ARCH=arm menuconfig
 make -j2 -C ./linux-sunxi  ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- uImage modules
```

**Comment by radagasp** [comment]
I tried this http://linux-sunxi.org/FirstSteps#The_flexible_option:_manual_build_and_installation, but am having problems. 

Please can you upload a cubian version with kernel headers so I can compile the kernel modules I need?

Thank you kindly.

**Comment by cubieplayer** [comment]
Okay, Since most of people needs the kernel header to compile software for cubieboard, I will integrate the kernel header into Cubian by default in next release, and a standalone header package will be provided soon.

**Comment by radagasp** [comment]
Hi,

I compiled my own kernel towards the allwinner a10 SoC, for my cubiboard, by following these sunxi instructions 
http://linux-sunxi.org/FirstSteps#The_flexible_option:_manual_build_and_installation.

I successfully created a debian rootfs and put everythingon the SD and it works well, but when I try and compile a kernel module, it tells me:

/bin/sh: 1: cd: can't cd to /lib/modules/3.0.76/build

Makefile:35: /lib/modules/3.0.76/build is missing, please set KERNELPATH

/home/batman-adv-2013.2.0/gen-compat-autoconf.sh /home/batman-adv-2013.2.0/compat-autoconf.h

make -C /lib/modules/3.0.76/build M=/home/batman-adv-2013.2.0 PWD=/home/batman-adv-2013.2.0 modules

make: **\* /lib/modules/3.0.76/build: No such file or directory. Stop.
make: **\* [all] Error 2

I thought that by compiling my own kernel, the kernel headers would be available to me? I am rather new at all of this, so I apologise if this is a rookie mistake, but would greatly appreciate some help :)

**Comment by radagasp** [comment]
I tried to install the headers, but with no luck either... apt-cache search does not have anything related to 3.0.7.6

root@debian:/home/batman-adv-2013.2.0# apt-get install linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree

Reading state information... Done
E: Unable to locate package linux-headers-3.0.76
E: Couldn't find any package by regex 'linux-headers-3.0.76'

**Comment by radagasp** [comment]
Thank you, where do I put these files?

On Mon, Jul 15, 2013 at 11:44 PM, cubieplayer notifications@github.comwrote:

> Hi, I upload a header packages from kernel source, download here
> http://cubieplayer.github.io/static_files/temp/linux-3.4.43-headers.tar.gz
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cubieplayer/Cubian/issues/27#issuecomment-21006135
> .

## 

*If you are going to achieve excellence in big things, you develop the
habit in little matters. Excellence is not an exception, it is a prevailing
attitude.
Colin Powellhttp://www.brainyquote.com/quotes/quotes/c/colinpowel138130.html
*

**Comment by cubieplayer** [comment]
Problem solved. see https://github.com/cubieplayer/Cubian/issues/18
