### ISSUE TITLE
Cubieboard2 no spi

### ISSUE THREAD

**Issue by HuStmpHrrr** [cubieplayer/Cubian#272]
using cubian, currently spi is required. but no spidev shows in /dev.

how to make it out? should i compile kernel to obtain the module?

**Comment by ScorpionZZZ** [comment]
I have compiled kernel 3.4.79 with spi, but no luck yet ((

**Comment by BerndKa** [comment]
I had the same problem and found a solution here: http://will-tm.com/spi-on-the-cubieboard2
It seems that the spi-sun7i.c file is missing in the kernel. After adding this file and adopting the config files as described by the above link spi is working fine.

@cubieplayer please add the file and the settings to the next kernel.

Bernd

**Comment by cubieplayer** [comment]
You can install 3.4.79 via apt, SPI driver is included
