### ISSUE TITLE
Cubian not booting on CubieTruck from SSD or Nand

### ISSUE THREAD

**Issue by SoleSS** [cubieplayer/Cubian#275]
Cubian not booting from nand nor from 2.5 SSD

Installing to nand using cubian-nandinstall after installation and removal of SD CT sticks in FEL mode...
copying installed date from nand to ssd and modifying of uEnv.txt and fstab not helping as well... system is in FEL mode...

**Comment by ScorpionZZZ** [comment]
Do you move "root=/dev/sda..." to extraargs (in uEnv.txt on nand)?

**Comment by SoleSS** [comment]
No, I changed the value only... 

Addition:
on /dev/nanda there are only 2 files: boot.axf, boot.ini and linux folder ...
and the size of the partition too small for all of files in boot folder of SD card ...

**Comment by ScorpionZZZ** [comment]
You need "/dev/nandc"

**Comment by SoleSS** [comment]
Of course I was modifying uEnv.txt on /dev/nandc moreover after cubian-nandinstall root in uEnv.txt on dev/Nandc was /dev/mmcblk0

**Comment by ScorpionZZZ** [comment]
My working config (/dev/nandc):
2 lines (all parameters "extraargs" in 1 line)

console=tty0.
extraargs=console=ttyS0,115200 hdmi.audio=EDID:0 disp.screen0_output_mode=EDID:1680x1050p60 panic=10 consoleblank=0 sunxi_no_mali_mem_reserve sunxi_g2d_mem_reserve=0 sunxi_ve_mem_reserve=0 root=/dev/sda1 rootwait

**Comment by SoleSS** [comment]
mb i'm doing something wrong... but cubian declines to boot from nand!.. FEL MODE only...

here's what i'm doing (latest cubian for cubietruck):
1. i'm making bootable SD
2. boot from SD
3. apt-get install cubian-nandinstall
4. sudo cubian-nandinstall
5. reboot
6. sudo cubian-nandinstall
7. removing SD and power ON
8. FEL mode ...

on nandc in uEnv.txt root=/dev/mmcblk0 changing to /dev/nandc does nothing...

BUT official linaro works...

i assume that if cubian not booting from nand it won't boot from ssd as well...

**Comment by SoleSS** [comment]
Well, i've fixed the problem...

Looks like there were some problems with copying of image to ssd and cubie somehow tried to boot from ssd even when uEnv was set to boot from nand...

**Comment by cubieplayer** [comment]
Aslo recommend to read http://cubian.org/2014/06/30/troubleshooting-nandinstall-on-a20/
