### ISSUE TITLE
Can't boot from NAND after booting from SD

### ISSUE THREAD

**Issue by george-4** [cubieplayer/Cubian#276]
Hello!
 I was running Cubian R4 on cubieboard 1. I had updated it with Cubian update and I had moved it into NAND.
 I then booted from an SD card to test Cubian Desktop. After I removed the SD I could no longer boot from NAND.

 Seems like the Cubian Desktop has messed with the NAND, is that possible?

**Comment by electrocret** [comment]
This is a known issue with Cubieboard 2, and is currently being worked on here: http://www.cubieforums.com/index.php?topic=1880.0

I have not heard of this issue on the Cubieboard 1 however.

**Comment by george-4** [comment]
I thought that the issue with Cubieboard 2 is that you generally cannot boot from NAND.
In my case I was always able to boot from NAND, and also in the past (with different releases) I had been able to alternate booting from SD and NAND with no problem.
This time however a single boot with Cubian Desktop caused the problem so I assume it must be specific to these Cubian releases.

**Comment by cubieplayer** [comment]
http://cubian.org/2014/06/30/troubleshooting-nandinstall-on-a20/
