### ISSUE TITLE
wifi connection problem

### ISSUE THREAD

**Issue by CliffHan** [cubieplayer/Cubian#278]
I'd like to connect cubian to wifi, and I did what the instruction told as this https://github.com/cubieplayer/cubian/wiki/%E4%B8%8A%E6%89%8BCubian

but wifi still not connected, while the wlan0 interface cannot be found while using "ifconfig"

I tried to load bcmdhd using "modprobe bcmdhd", and then wlan0 found, but wifi network is still not working.

I understand that I must missed some basic fundamental configuration concepts, could you explain more in your tutorial?

**Comment by ScorpionZZZ** [comment]
https://github.com/cubieplayer/Cubian/wiki/Get-started-with-Cubian
section "Connect to network", subsection "Wireless"

**Comment by CliffHan** [comment]
I did as the tutorial, and cannot connect properly.
But I used wpa_passphrase and generated a wpa.conf, and used wpa-conf option in /etc/network/interfaces, then it works
