### ISSUE TITLE
ufw enable error

### ISSUE THREAD

**Issue by Celillo** [cubieplayer/Cubian#28]
I am proving Cubian. I want to use the ufw firewall, but when I enable the firewall, I obtain this error message and the ufw is not activated:

cubie@Cubian:~$ sudo ufw enable
Command may disrupt existing ssh connections. Proceed with operation (y|n)? y
ERROR: problem running ufw-init

**Comment by cubieplayer** [comment]
Hi,
Take a loot at http://ubuntuforums.org/showthread.php?t=1660916
