### ISSUE TITLE
Not displayed in 1080p

### ISSUE THREAD

**Issue by MEGA-PRO** [cubieplayer/Cubian#282]
I installed Cubian, checked MD5, after launching the console is visible in 720p, then automatically changes the resolution to 1080p and shows clearly that, porridge of different colors. Checked on the TV and monitor both 1080p. Attached is a screenshot.
![img_20140329_012538](https://cloud.githubusercontent.com/assets/7100100/2558292/8e2bca22-b73f-11e3-942a-22dfdc188e26.jpg)

**Comment by michalliu** [comment]
duplicate with https://github.com/cubieplayer/Cubian/issues/246

**Comment by MEGA-PRO** [comment]
Any solution?

**Comment by michalliu** [comment]
see #246
