### ISSUE TITLE
including btsync in the repo

### ISSUE THREAD

**Issue by swetoast** [cubieplayer/Cubian#286]
not sure if this is the right forum for this but i would love to see btsync included in the repo for cubian makes it so much easier to update etc.

**Comment by s-kostyuk** [comment]
There is third-party repositories for btsync already, there is no need to duplicate btsync packages in the cubian repo. Details:
here http://www.yeasoft.com/site/projects:btsync-deb:btsync-repo
and here http://forum.bittorrent.com/topic/18974-debian-and-ubuntu-server-unofficial-packages-for-bittorrent-sync/

**Comment by cubieplayer** [comment]
I will take a look on it, Thanks for share
