### ISSUE TITLE
openssl update

### ISSUE THREAD

**Issue by swetoast** [cubieplayer/Cubian#287]
need to update the libs to 1.0.1g due to the heartbleed bug

http://heartbleed.com/

**Comment by s-kostyuk** [comment]
Interesting. I have libssl and openssl with 1.0.1e-2+deb7 version installed, but it built on 8 Apr 2014 and server marked as save in online tests. Already patched?
first screenshot: https://cloud.githubusercontent.com/assets/5122578/2659530/cd54d476-c015-11e3-8678-b8c017d98acd.png
second screenshot: https://cloud.githubusercontent.com/assets/5122578/2659639/dd2448fe-c016-11e3-887e-ca10dd799fe2.png
