### ISSUE TITLE
Howto edit led trigger file

### ISSUE THREAD

**Issue by dvwyngaa** [cubieplayer/Cubian#288]
Hi,

If I want the green led to blink on disk activity or just for a specific disk, say sda1, how do I add this option to the led trigger file? 

I have tried to do this with "echo disk-activity > /sys/class/leds/blue:ph21:led2/trigger" but I get a error: "-su: echo: write error: Invalid argument"

Any help would be appreciated.

Regards,

Dawid

**Comment by kdeenkhoorn** [comment]
Dawid,

If you do:  `more /sys/class/leds/orange:ph20:led2/trigger`
You see the available options for this led:

none
rfkill0
battery-charging-or-full
battery-charging battery-full
battery-charging-blink-full-solid
ac-online
usb-online
mmc0
mmc1
timer
heartbeat
backlight
gpio
[cpu0]
cpu1
default-on 

With, in my case, 'cpu0'  selected.
Unfortunate 'disk-activity'  is not one of the options the driver has to offer.

Also look at http://linux-sunxi.org/Cubieboard/Programming/StatusLEDs for reference.
