### ISSUE TITLE
Is is safe to use cubian on sdcard without using nand

### ISSUE THREAD

**Issue by notihnio** [cubieplayer/Cubian#291]
Hello thank you for this wonderfull distro.  I would like to use my A20 as small lampp server. So i bought a 64GB sd card to use it as root fs. After flashing cubian text version on sd card, A20 boots normaly but root fs is mounted as read only and i cannot mount it as rw.

If i disable ext4 journal i can mount my sdcard  rw but the system is quite unstable.  After some reboots I expirence boot loop.  

So  is any way to use my sdcard as my rootfs or should i install cubian on nand for more stability?

**Comment by notihnio** [comment]
The problem is with the sd card. My sd card is 64 gb. I installed  cubian on a 8 gb sd card and everything works ok. But why i can use my 64gb card?????

**Comment by cubieplayer** [comment]
I believe it's the same issue with https://github.com/cubieplayer/Cubian/issues/326
