### ISSUE TITLE
Kernel panic cubieboard 1

### ISSUE THREAD

**Issue by lucaaamaral** [cubieplayer/Cubian#296]
I've installed cubian as says here: https://github.com/cubieplayer/cubian/wiki/Install-Cubian
with the r8-a10 .img available for download at the cubian's website. As it was on 7z, I've unpacked to .iso and followed the process on a mac, but when I load it up, the cubieboard keeps in a loop of shutting down/restarting. It says it had a kernel panic, what can I do?

**Comment by michalliu** [comment]
Write to SD card using lower blocksize bs=2M, it's slow, but safe
