### ISSUE TITLE
这是为什么

### ISSUE THREAD

**Issue by Garfield550** [cubieplayer/Cubian#299]
我已经将系统安装至 NAND ，但是他的目录结构似乎不科学啊！

<pre>
Filesystem      Size  Used Avail Use% Mounted on
rootfs          3.8G  807M  2.8G  23% /
/dev/root       3.8G  807M  2.8G  23% /
devtmpfs        405M     0  405M   0% /dev
tmpfs            81M  144K   81M   1% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           162M     0  162M   0% /run/shm
cubie@Cubian:~$ sudo cubian-nandinstall
!!! This tool must be run on SD-card system
</pre>

**Comment by michalliu** [comment]
哪里不科学?

**Comment by Garfield550** [comment]
与官网安装指南展示的不一样

**Comment by cubieplayer** [comment]
这是正常的
