### ISSUE TITLE
Ipv6

### ISSUE THREAD

**Issue by elmatou** [cubieplayer/Cubian#3]
Nice work you've done !

I'm unable to load the ipv6 module, don't you want to compile your next release with the module ?

thx bye

**Comment by cubieplayer** [comment]
ok, noted

**Comment by cubieplayer** [comment]
r2 supported IPv6, It's builded inside kernel now

**Comment by elmatou** [comment]
thanks, it will be useful.
Any how, did you intend to share your patches and configuration files of your Cubian release ?
Maybe others (and me later) would like to help in this work.

**Comment by cubieplayer** [comment]
Hi,
Everything is open sourced, include my building script, checkout it out the [WiKi](https://github.com/cubieplayer/Cubian/wiki)

**Comment by elmatou** [comment]
I didn't notice (I went directly to the install & get started Page) !
That's the spirit, thanks

El Matou
