### ISSUE TITLE
Wireless Cards

### ISSUE THREAD

**Issue by ghost** [cubieplayer/Cubian#30]
Good morning,

I'm having trouble installing the drivers for usb wireless cards.

AR9271
RT3070

Install firmware-atheros firmware-ralink and not work.

Could you help me?

**Comment by cubieplayer** [comment]
Where is the driver source?

**Comment by ghost** [comment]
managed to solve

2013/7/23 cubieplayer notifications@github.com

> Where is the driver source?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cubieplayer/Cubian/issues/30#issuecomment-21391361
> .

## 

Lucas Padilia
(17) 8201-2542
