### ISSUE TITLE
After update I can't connect to my board via SSH

### ISSUE THREAD

**Issue by Zlyton** [cubieplayer/Cubian#302]
Early all was fine.
I wrote image (r8-A10) on SD-card, system started.
SSH worked successfully.
But after update something happend.
And now I can't connect via SSH to my board.
There are opened few ports (25 and 110) but 36000 (and 22 too) is closed.
Rewriting image to SD card has no result.
System is started as usualy (green led blinking) but I don't have a cable to connect a monitor.
What may be wrong and how can I fix it?

**Comment by opless** [comment]
Is the web admin panel running?

IIRC it's on port 8080 without any ssl or password

On 11 May 2014, at 10:31, Zlyton notifications@github.com wrote:

Early all was fine.
I wrote image (r8-A10) on SD-card, system started.
SSH worked successfully.
But after update something happend.
And now I can't connect via SSH to my board.
There are opened few ports (25 and 110) but 36000 (and 22 too) is closed.
Rewriting image to SD card has no result.
System is started as usualy (green led blinking) but I don't have a cable
to connect a monitor.
What may be wrong and how can I fix it?

—
Reply to this email directly or view it on
GitHubhttps://github.com/cubieplayer/Cubian/issues/302
.

**Comment by Zlyton** [comment]
From diapazone 21-23, 25, 53, 80, 110, 135, 137-139, 443, 445, 1080, 1433, 3128, 3306, 8000, 8080, 36000.opened only 25 and 110.

**Comment by Zlyton** [comment]
At the moment there is new clear image of Cubian (last revision)

**Comment by Zlyton** [comment]
If necessary I have USB-to-TTL adapter.

**Comment by opless** [comment]
I'm not sure if the serial port is 5v or 3v TTL

Are you sure you can't find a HDMI monitor (or a HDMI -> DVI converter) and
USB keyboard?

On 11 May 2014, at 10:39, Zlyton notifications@github.com wrote:

At the moment there is a new clear image of Cubian (last revision)

—
Reply to this email directly or view it on
GitHubhttps://github.com/cubieplayer/Cubian/issues/302#issuecomment-42766245
.

**Comment by Zlyton** [comment]
USB keyboard is not a problem.
But I need few days to find HDMI monitor or hdmi-vga converter.
What should I do when a monitor will be connected?

**Comment by opless** [comment]
The behavior will be identical to a PC booting Linux. So you'd be presented
regular boot messages, finally being given either a text mode login prompt,
or some kind of desktop login (I always elect to install a text mode or
server distro when I install Linux)
If the SD card doesn't work you boot into android.

On 11 May 2014, at 10:53, Zlyton notifications@github.com wrote:

USB keyboard is not a problem.
But I need few days to find HDMI monitor or hdmi-vga converter.
What should I do when a monitor will be connected?

—
Reply to this email directly or view it on
GitHubhttps://github.com/cubieplayer/Cubian/issues/302#issuecomment-42766494
.

**Comment by Zlyton** [comment]
I so shamed but it was my f*****g firewall.
It was turned off but with in some magic way it blocked my connection requests via SSH.
Issue was false, sorry :)
