### ISSUE TITLE
git clone not working

### ISSUE THREAD

**Issue by joselalupa** [cubieplayer/Cubian#305]
i got cubian for cb2.
the desktop version doesn't boot, it shows a screen with color noise and keep a booting loop. the text version works fine but i try to get sunxi-tools using git clone and i receive error... "git: command not found"
anyone? please

**Comment by mattlm** [comment]
You need to install git - `sudo apt-get install git-core`

**Comment by joselalupa** [comment]
thanks a lot martin

On Sat, May 17, 2014 at 10:59 AM, Matthew Martin
notifications@github.comwrote:

> You need to install git - sudo apt-get install git-core
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cubieplayer/Cubian/issues/305#issuecomment-43409160
> .

## 

---

Inventando cositas pa hacer que las masas reaccionen.

**Comment by michalliu** [comment]
Maybe the same issue with #282
