### ISSUE TITLE
R8设置内核参数释放mali内存时系统无法启动。

### ISSUE THREAD

**Issue by sundev126** [cubieplayer/Cubian#306]
下载的是最新的R8，我的是A10.
我将sunxi_no_mali_mem_reserve sunxi_g2d_mem_reserve=0 sunxi_ve_mem_reserve=0这几个参数添加到uEnv.txt中，
reboot -p后，系统无法启动。

**Comment by sundev126** [comment]
经过我一次次的实验，只添加sunxi_ve_mem_reserve=0参数，系统可以启动。
其他两个参数添加任何一个，系统都无法正常重启！

**Comment by michalliu** [comment]
那些选项只能在3.4.79以下的内核工作，3.4.79以上这些指令都被干掉了，因为内核支持CMA

**Comment by sundev126** [comment]
谢谢！知道了！
