### ISSUE TITLE
Wrong download link for A20 server edition.

### ISSUE THREAD

**Issue by mosesgi** [cubieplayer/Cubian#307]
On the page  http://cn.cubian.org/downloads/  
the download link (mirror 2 Beijing) for Cubieboard 2 server edition is wrong. 
It is same with the download link for Cubietruck.

I used a whole night using that wrong edition, in which Ethernet doesn't work. That indeed sucked.

**Comment by cubieplayer** [comment]
Thanks for reporting, Fixed.
