### ISSUE TITLE
"iptables -m owner" not working

### ISSUE THREAD

**Issue by POMATu** [cubieplayer/Cubian#31]
Hi, 

Thanks for this awesome distribution.
Everything is great and stable except that I cannot forward individual user traffic via another gateway as I did on debian x86 and raspbian.

root@Cubian:~# iptables -m owner —uid-owner 101 -j MARK —set-mark 0x1 -t mangle -A OUTPUT
iptables: No chain/target/match by that name

"-m owner" is not working. When I installed xtables-addons-common it downloaded old kernel and I was unable to switch to it.

How I can switch to another kernel or are there any other way to get the "-m owner" working?

Thanks

**Comment by cubieplayer** [comment]
Thanks for report,But I don't know too much about iptable. I did some search and try to fix this issue later.

**Comment by POMATu** [comment]
how can I boot into 3.2.0 kernel downloaded from repo? Everything should work there, because xtables-addons-common is compiled for this kernel

**Comment by cubieplayer** [comment]
The kernel didn't compiled with `owner` support, I recompiled the kernel, it worked. This will be fixed in r4

**Comment by POMATu** [comment]
when are you planning to release r4? or can you upload recompiled kernel separately for me?

Thanks a lot

**Comment by cubieplayer** [comment]
Hi, The seprate uImage is available here http://cubieplayer.github.io/static_files/uImage/a10-3.4.43/
