### ISSUE TITLE
负载太重时，会死机或花屏

### ISSUE THREAD

**Issue by lingcoln** [cubieplayer/Cubian#316]
我用cubian来编译mono 3.4，用4线程同时开工时，就死机了，或者花屏

**Comment by inn1983** [comment]
确实有这个现象，这里有解决办法
https://groups.google.com/forum/#!searchin/linux-sunxi/dcdc3/linux-sunxi/1Orj-ukBb6s/qjfAh_NrL3YJ

**Comment by michalliu** [comment]
集中在 https://github.com/cubieplayer/Cubian/issues/319 讨论吧，@inn1983 好样的

**Comment by michalliu** [comment]
Closed duplicated with #319
