### ISSUE TITLE
Stability issue

### ISSUE THREAD

**Issue by michalliu** [cubieplayer/Cubian#319]
I've discovered the board isn't stable when workload is high...

**Comment by opless** [comment]
Some questions:

Which board are you using?

What are you running to make the workload high?

What problems are you having that indicates that the board isn't stable?

I'm pretty sure cubian doesn't support lm-sensors, so I'm not sure how to
get you to check basic things like cpu temperature.

On 10 June 2014 09:01, michalliu notifications@github.com wrote:

> I've discovered the board isn't stable when workload is high...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cubieplayer/Cubian/issues/319.

## 

Earth. What a planet. On Earth, you enjoy eating a tasty clam. On my
planet, clams enjoy eating a tasty you.
-Dr ZoidBerg

**Comment by cubieplayer** [comment]
Follow this commit should resolve the issue.
https://github.com/mmplayer/sunxi-boards/commit/4e0a4f288d3effbc77b94e53a3e7e8d37220e997#diff-4b7200d0b3e085ee9d5ba4673c597d80

**Comment by michalliu** [comment]
See aslo: https://www.mail-archive.com/linux-sunxi@googlegroups.com/msg04662.html

**Comment by michalliu** [comment]
Checkout this article: http://cubian.org/2014/07/05/resolve-stability-issue-on-cb2
