### ISSUE TITLE
problem with cubian-nandinstall

### ISSUE THREAD

**Issue by masoudmm** [cubieplayer/Cubian#321]
Hi @cubieplayer ,first of all thank you for providing nandinstall script
I followed these instructions after I installed cubian-base-r4 for A20 (I am using cubieboard2):
sudo cubian-update
sudo apt-get install cubian-nandinstall
sudo cubian-nandinstall

but the nandinstall command doesn't work and it seems to stops in nand-part command with following message:
usage: nand-part nand-device 'name2 len2 [usertypr2]' ['name3 len3 [usertype3]']
...

where is the problem and how can I fix it??
I have currently installed cubian r1 in my nand (with booting issu)

**Comment by cubieplayer** [comment]
My mistake, it should be okay now. We use patwood's new nand-part. The usage is quite different than the old one.

```
apt-get update && apt-get install cubian-nandinstall
```

**Comment by masoudmm** [comment]
I installed the r1 image for A20 in my sd and followed your instructions, and it worked..., thank you
