### ISSUE TITLE
Cubian with Desktop. How to set Auto Logon?

### ISSUE THREAD

**Issue by ETiV** [cubieplayer/Cubian#323]
I've searched the web by `LXDE auto logon`.
All of the results said "edit /etc/lxdm/lxdm.conf", but there is no file, even directory there.

what can I do?

**Comment by cubieplayer** [comment]
We use slim as login manager.
You can modify /etc/slim.conf, change default_user accordingly, then set auto_login to yes

**Comment by ETiV** [comment]
thanks for your replying :)

but ... after i set those options:

```
default_user        cubie
auto_login          yes
```

and a `sudo reboot`

the screen would not display any graphic, except a cursor showing "X".

command `ps aux | grep slim` shows:

```
root      2012  0.2  0.6  11908  5508 tty7     Ss+  10:45   0:00 /usr/bin/X11/X -nolisten tcp -auth /var/run/slim.auth vt07
```

any further instructions?

thank you!

---

update:

finally it works.

seems I need to login to the desktop first, then edit /etc/slim.conf
