### ISSUE TITLE
Can't boot Cubian from SD card

### ISSUE THREAD

**Issue by timo-keller** [cubieplayer/Cubian#326]
Hi,

I've downloaded the Cubietruck Desktop Image from the homepage and copied it on a SD card with dd.

If I try to boot from this card  the bootup stops at "Waiting for root device /dev/mmcblk0p1". (i've waited a couple of hours)

How can I get Cubian to boot properly?

**Comment by michalliu** [comment]
You can try a different SD-card and different tools to write the image. I'm sure the image is fine. BTW, did you check the md5?

**Comment by timo-keller** [comment]
I tried two different SDHC cards and different tools (including dd) to write the image to the card.
I don't think the "HC" is a problem. Can you recommend a SD(HC) card?

And of course I did check the MD5.

**Comment by billryan** [comment]
@t1mer  Maybe its the problem of your large microSD card, I found that with small microSD card it is ok with Cubian, but Cubian do not support 32G or bigger microSD card now.

If you want to use 32G or bigger microSD card for Cubian, some workaround you should do as follows:  
1. extract the Cubian.img file to a sd card or some directory.  
2. `dd` the u-boot file separately as `sudo dd if=u-boot-sunxi-with-spl.bin of=/dev/sdX bs=1024 seek=8;sync`.  
3. mkdir `/boot` separately on `/dev/sdX1`, put the uImage, uEnv, script.fex, script.bin there.  
4. Put other file into `/dev/sdX2`  

This workaround is just a rough idea, it works for me on Cubieboard2-2card, you should do carefully with respect to your microSD card and hardware.

**Comment by michalliu** [comment]
@billryan Do you mean by repartition the large SD-card to two partitions, one for `/boot`, another for `/` ?
or just write a new uboot?

BTW: Where i can get u-boot-sunxi-with-spl.bin?

Thanks for sharing the solution, I'm a little confused

**Comment by billryan** [comment]
@michalliu I am not sure whether just writing a new uboot work. Repartition the large SD-card to two partitions would be safe. the u-boot-sunxi-with-spl.bin I mentioned is from the document wrote in http://dl.cubieboard.org/docs/CN/CB2-2Card/CB2-2Card_debian_installation_guide.pdf

**Comment by michalliu** [comment]
Yeah, using two partitions will solve the problem, one for /boot one for rootfs

**Comment by cubieplayer** [comment]
The new cubian will be released recently.  The SD-card image is using two partitions layout.
