### ISSUE TITLE
Scaling Governor

### ISSUE THREAD

**Issue by deksan** [cubieplayer/Cubian#33]
Hi,

By default /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
is on ondemand, this makes cubian looking slower than other distribution.

Add a bit on the wiki about it or add a script in init.d such as 

```
#!/bin/sh

# chkconfig: 345 99 10
# description: Startup/shutdown script to enable ondemand / performance
#
### BEGIN INIT INFO
# Provides:          performance
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop::    $network $local_fs $remote_fs
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Performance / Ondemand scaling governor
### END INIT INFO

for CPUFREQ in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
        do
                [ -f $CPUFREQ ] || continue
                echo -n performance > $CPUFREQ
        done
```

**Comment by cubieplayer** [comment]
Hi, Thank for sharing, Here is my version https://github.com/mmplayer/fsupdate/blob/base/common/etc/init.d/cubian-ondemandcpufreq

**Comment by deksan** [comment]
Can't see yours, Error 404. Maybe it's private ?

**Comment by cubieplayer** [comment]
sry, link fixed

**Comment by deksan** [comment]
Looks better than mine :) Wondering if the values shouldn't be in a /etc/default/cpu-gouvernor file so one can decide what values to put ?

**Comment by cubieplayer** [comment]
Nice suggestion
