### ISSUE TITLE
Booting only from NAND

### ISSUE THREAD

**Issue by ronysk** [cubieplayer/Cubian#330]
Hi,
How do I set the cubieboard2 to boot entirely from NAND,  even if I have inserted bootable SD card in slot.
Thank you for help
Rony

**Comment by michalliu** [comment]
Just remove th bootloader on nand will do the trick.
dd if=/dev/zero of=/dev/sd bs=1M count=1

then repartition your sd card

**Comment by ronysk** [comment]
Hi,

I probably badly expressed. I want to boot from NAND only, not from SD, 
although the bootable image is on inserted SD

Thank you

Rony

2014-07-08 22:00 odosielateľ napísal:

**Comment by michalliu** [comment]
I think it's not possible, because the BROM will boot take higher priority on SD-card than NAND

**Comment by mzapa** [comment]
I believe michalliu is correct.  Refer to http://dl.linux-sunxi.org/A20/A20%20User%20Manual%202013-03-22.pdf section 1.6.2 on page 96.

**Comment by ronysk** [comment]
Hi,

Thank you for navigation.

Rony

2014-07-16 12:56 odosielateľ napísal:
