### ISSUE TITLE
CT Desktop on nandb not booting

### ISSUE THREAD

**Issue by ForrestLee** [cubieplayer/Cubian#337]
I have ct desktop running and updated on sd, but after nand-install it does not boot from nand. Even after I had linaro version booting from nand before running nand install (which ended in success) . Still boots from sd ok.

Should this work on ct desktop?  Suggestions?

**Comment by ForrestLee** [comment]
OK, I will move away from Cubian and use other image that works on nand, SD, and SSD ....

**Comment by michalliu** [comment]
http://cubian.org/2014/06/30/troubleshooting-nandinstall-on-a20/

**Comment by ForrestLee** [comment]
Already did this ... still does not work, as I said in the post.

michalliu wrote:

> http://cubian.org/2014/06/30/troubleshooting-nandinstall-on-a20/
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cubieplayer/Cubian/issues/337#issuecomment-50297617.

## 

Regards,
      Forrest

**Comment by michalliu** [comment]
Have no clue, can you paste some info from serial console?
