### ISSUE TITLE
Problems with YunoHost installed on Cubian with Cubieboard 1 & 2

### ISSUE THREAD

**Issue by M5oul** [cubieplayer/Cubian#339]
https://yunohost.org/#/

We have problems such as : 
- Don’t have acces to admin web
- Can’t install or remove applications

**Comment by michalliu** [comment]
Are you sure yunohost is compatible with debian?

**Comment by M5oul** [comment]
YunHost is based on Debian. This problem is corrected on YunoHost. Thanks.
