### ISSUE TITLE
CubieBoard1 : problem during updating modules 3.4.79

### ISSUE THREAD

**Issue by ambrosa** [cubieplayer/Cubian#341]
Today I've tried am upgrade:

root@Cubian:/etc/init.d# cubian-update 
**\* Performing self-update
**\* Cubian updater v1.3.6 http://cubian.org
**\* Checking updates from server
**\* Downloading Firmware/Updates (this may take a while)
**\* Updating firmware
**\* Updating kernel
**\* Updating modules
**\* Depmod 3.4.79-sun4i
ERROR: could not open directory //lib/modules/3.4.79-sun4i: No such file or directory
FATAL: could not search modules: No such file or directory
**\* Updating fs
**\* Update success, A reboot is needed for changes to take effects

root@Cubian:~# ls /lib/modules/
3.4.43+  3.4.67+  3.4.75-sun4i

3.4.79-sun4i ARE NOT downloaded.

root@Cubian:~# ls -la /boot/
total 6672
drwxr-xr-x  2 root root    4096 Sep 29  2013 .
drwxr-xr-x 25 root root    4096 Mar 10 19:02 ..
-rw-r--r--  1 root root     318 Aug 22  2013 boot.cmd
-rw-r--r--  1 root root     245 Aug 22  2013 boot.cmd.cubian
-rw-r--r--  1 root root     317 Aug 25  2013 boot.scr
-rw-r--r--  1 root root     317 Aug 22  2013 boot.scr.cubian
-rw-r--r--  1 root root     390 Aug 25  2013 boot.scr.maxram
-rw-r--r--  1 root root   48092 Sep 29  2013 script.bin
-rw-r--r--  1 root root   48092 Sep 29  2013 script.bin.bak
-rw-r--r--  1 root root   26358 Jul 28  2013 script.fex
-rw-r--r--  1 root root     138 Jul 22  2013 uEnv.txt
-rw-r--r--  1 root root     138 Aug 22  2013 uEnv.txt.cubian
-rw-r--r--  1 root root 6665984 Mar  6 17:46 uImage
I looks that uImage is not updated.

Any idea ?

**Comment by cubieplayer** [comment]
Thanks for reporting, problem resolved.

**Comment by ambrosa** [comment]
After a :
   root@Cubian:/etc/init.d#  cubian-update -r

I confirm: now all is OK.
Thanks
