### ISSUE TITLE
Problem compiling WiFi drivers

### ISSUE THREAD

**Issue by pato89xd** [cubieplayer/Cubian#342]
Hi, when I try to compile the drivers for the rtl8188eu i got this log
make ARCH=arm CROSS_COMPILE= -C /lib/modules/3.4.79-sun4i/build M=/home/cubie/De                                                   sktop/usb/rtl8188eu-master  modules
make[1]: Entering directory `/usr/src/linux-headers-3.4.79-sun4i'
  CC [M]  /home/cubie/Desktop/usb/rtl8188eu-master/core/rtw_ap.o
In file included from include/linux/timex.h:174:0,
                 from include/linux/jiffies.h:8,
                 from include/linux/ktime.h:25,
                 from include/linux/timer.h:5,
                 from include/linux/workqueue.h:8,
                 from include/linux/slub_def.h:12,
                 from include/linux/slab.h:185,
                 from /home/cubie/Desktop/usb/rtl8188eu-master/include/osdep_ser                                                   vice.h:34,
                 from /home/cubie/Desktop/usb/rtl8188eu-master/core/rtw_ap.c:22:
/usr/src/linux-headers-3.4.79-sun4i/arch/arm/include/asm/timex.h:15:24: fatal er                                                   ror: mach/timex.h: No such file or directory
compilation terminated.
make[2]: *** [/home/cubie/Desktop/usb/rtl8188eu-master/core/rtw_ap.o] Error 1
make[1]: *** [_module_/home/cubie/Desktop/usb/rtl8188eu-master] Error 2
make[1]: Leaving directory`/usr/src/linux-headers-3.4.79-sun4i'
make: **\* [modules] Error 2

**Comment by cubieplayer** [comment]
The header package has been fixed.Now it can compile driver normally. Please upgrade your header package to latest version.

**Comment by oguska** [comment]
We got two updates on headers first one was fine but second one gives  errors on this file `/usr/src/linux-headers-3.4.79-sun4i/include/linux/sched.h` when compile drivers.

Make command just spamming this over ssh.

``` bash
include/linux/sched.h:1:1: error: stray '\377' in program
```

linux-headers-3.4.79-sun4i
Version : 3.4.79-4cubian
