### ISSUE TITLE
Recompile kernel

### ISSUE THREAD

**Issue by mazBR** [cubieplayer/Cubian#35]
Cubieplayer, hi there!

EDIT: i'm using fresh debian wheezy as a base system to compile the kernel.

Would you please give me some directions of how to compile kernel? I mean, check the steps i've made:
1. checkout the sunxi-3.4 branch
2. copy your kernel config and renamed.
3. then i follow theses steps: http://jas-hacks.blogspot.com.br/2012/10/hackberry-a10-compiling-kernel-armhfs.html 

After copying uImage to /boot and the modules to /lib/modules the cubieboard doesn't boot.

I also saw in another post that you tell to use your toolchain, so i did it too. But when i try to compile, the gcc command from your toolchain says 'no such file or directory'. i've checked, the file exists(obviously) but i don't know why it doesn't run.

PS. when checking on the toolchain, i see there's a new 2013.05, do you use this one now?

hope u can help. regards

**Comment by mazBR** [comment]
well, don't know why. BUT... using EXACT jas-hacks method with latest ubunto, works fine! kernel compiled!

regards!

**Comment by cubieplayer** [comment]
Cheers!
