### ISSUE TITLE
Asix USB Gigabit Ethernet Drivers AX88179_178A

### ISSUE THREAD

**Issue by oguska** [cubieplayer/Cubian#355]
Hello, i try to complie this driver , but got no success.Can we include this on future relase, thanks.
http://www.asix.com.tw/FrootAttach/driver/AX88179_178A_LINUX_DRIVER_v1.10.0_SOURCE.tar.bz2

**Comment by oguska** [comment]
I successfully compiled this driver under 3.4.79 kernel, here is the module file.
https://mega.co.nz/#!2R8G1KbD!X--TKG0yN9jd6sjMH8j2zb8JSx-fKSKVi7I9ckGISr8

**Comment by cubieplayer** [comment]
Just grab the header through apt then compile the driver you want
