### ISSUE TITLE
cubietruck torrent server

### ISSUE THREAD

**Issue by marvindl** [cubieplayer/Cubian#357]
Hi,
Can I use cubietruck with torrent server?

I want use one External Hard Drive for file storage.

Is it possible?

Thanks

**Comment by stidn** [comment]
Hi there Marvindl, I currently use Cubian (for Cubietruck) in conjunction with Transmission-Daemon as my torrent box, and haven't hit a single glitch. External hard drive will work fine with it, just set the download folder to the external hard drive and you're ready to torrent away.

**Comment by milton14** [comment]
I use my Cubietruck with Cubian for torrents too. It works perfectly. I use Deluge demon and Deluge web on my Cubietruck and Transdrone on my phone (Android) for manage it.

**Comment by marvindl** [comment]
Hi guys,
Thanks for your help! I go buy this little machine.
Big hug to everyone

**Comment by cubieplayer** [comment]
Deluge looks very nice and professional. I personally use [PHPTracker](http://php-tracker.org/). It's simple and open source.
