### ISSUE TITLE
Cubieboard 1 unable to resize nand because cubieboard boots always from NAND

### ISSUE THREAD

**Issue by rggefrm** [cubieplayer/Cubian#358]
Hi,

this is my first install. I tried to resize the NAND to maximise the 4 Gbyte. However cibie-resize2 I get an error message that I have to boot from the sd card.
It looks like that although the SD card is inserted, the board still boots from the NAND.

I would very much appreciate any suggestion how to solve the problem

**Comment by michalliu** [comment]
cubian-resize is not working for NAND, you need to use 'nand-part' to repartition the NAND.
You can aslo try 'gpart' to resize you SD card
