### ISSUE TITLE
How do I create a new splash screen for cubian

### ISSUE THREAD

**Issue by rkwiles** [cubieplayer/Cubian#359]
I want to replace the splash screen of the two cubie shown at the top of the console screen during bootup.  Full screen without the scrolling startup process text would be even nicer.

How can I do this?
I have looked into splashy and plymouth but neither seem to work.

Thanks

**Comment by michalliu** [comment]
You need some tweaks in kernel, these commit might helps
https://github.com/mmplayer/linux-sunxi/commit/12764804c214085d4c37473c5f6566761134c44e
https://github.com/mmplayer/linux-sunxi/commit/c84b6ebe7b01b7de19a33e8b8eaacc484e7ca627
