### ISSUE TITLE
Hang on startup due to service start issue

### ISSUE THREAD

**Issue by xAragornx** [cubieplayer/Cubian#36]
Using and freshly flashed image on an SD card booting a Cubie1. It is hanging for an extended time (1min or so) at the end of the boot sequence. 

Terminal ouput:
[ ok ] Setting sysfs variables....
<7>eth0: no IPv6 routers present
Timeout reached while wating for return value
Killing background process.
done.

If I have the network cable disconnected, this hangup doesn't happen. I think one of the startup services is hanging and not completing for some reason and thus create the boot hang.

**Comment by cubieplayer** [comment]
I noticed this issue aslo, seems it's caused by ifplugd script.This will be consider as a bug to resolve in the future updates.

**Comment by cubieplayer** [comment]
This bug is fixed by commit https://github.com/mmplayer/fsupdate/commit/9dd1ca489e7edcdd7316b306123ced098af6e6b9

**Comment by cubieplayer** [comment]
Fixed on [r5](http://cubian.org/2013/09/06/cubian-r5-for-a10-and-r2-for-a20-released)
