### ISSUE TITLE
AX.25 is supported into Cubian ?

### ISSUE THREAD

**Issue by ch0mik** [cubieplayer/Cubian#361]
AX.25 (ham radio networking) is supported into Cubian like in https://romanrm.net/a10/kernel?s[]=radio  ?

Vy 73! de SQ7MRU, Paweł

**Comment by michalliu** [comment]
The latest linux-3.4.79 is compiled with this module

**Comment by ch0mik** [comment]
Hello,

Thanks, but I cant find the modules of ax25 and mkiss

cubie@Cubian:~$ modprobe ax25
FATAL: Module ax25 not found.
cubie@Cubian:~$ modprobe mkiss
FATAL: Module mkiss not found.
cubie@Cubian:~$ uname -a
Linux Cubian 3.4.79-sun4i #22 PREEMPT Thu Jul 3 06:32:24 CST 2014 armv7l
GNU/Linux

Regards
Pawel, SQ7MRU

**Comment by michalliu** [comment]
Hi, try to install the latest kernel.

```
apt-get update & apt-get install linux-image-3.4.79-sun4/7i
```
