### ISSUE TITLE
cubian-nandinstall does not create bootable nand

### ISSUE THREAD

**Issue by eagletree** [cubieplayer/Cubian#365]
This is identical to what I have seen reported earlier this year. cubian-nandinstall seems to complete normally, after system shutdown, removal of the SD and repowering the system, produces a blinking LED and a green bar on the monitor filled in a small portion of the way.

The fix for this referenced from the cubian site doesn't seem to apply as there is no formatted nandc containing a uEnv.txt. Is there an open source solution for correcting this without using proprietary software?

**Comment by michalliu** [comment]
It's opensource indeed, It's a shell script

**Comment by eagletree** [comment]
I apologize for being vague. I was referring to the only avenue left seems to be using livesuit/Phoenixsuit and that actually sounded odd anyway, since it would involve redoing it, whenever the nand is flashed again. I was hoping that either cubian-nandinstall had addressed this issue, or that there was a manual build instruction that would result in a bootable nand installation of cubian. I did alter the script to display what it was doing, and it appears that there are no failures in what it attempts. But the system can't be booted from nand when complete. (Edit: removing this comment, it was pure conjecture and had no place in this discussion ", presumably because it's trying to boot android?")

**Comment by michalliu** [comment]
You need to buy a serial cable to get the low level log from u-boot to figure out why it's not working.

**Comment by eagletree** [comment]
Okay, I was under the impression this is a common problem. I will take from your response that it normally works and I have a unique problem.

**Comment by eagletree** [comment]
I hacked a serial cable together and listed the boot. The remainder of your comment suggests I should "figure out why it's not working". It appears to be not working in the same manner that people reported it on cubieboard.org forums in February and June. Beyond that, I'm not sure how I'd figure out why it's not working. Maybe I am posting to the wrong place and I will post there, but I hoped I could find if there has been a resolution to this problem or an official description of how to work around it. But first and more basic, is this not the place to get help on cubian and cubian-nandinstall issues? I followed the link at the cubian.org page that said "Help" and it brought me here. If it's not, I apologize for posting the question here.

Here is the console output, it suggests that while cubian-nandinstall did what it thought it should, it didn't do what the bootstrap loader thinks it should. The partitioning isn't understood.

not burn nand partition table!
NB1 : nand_info_init fail
[      3.554]nand init fail
set to recovery
try sprite_led_gpio config
sprite_led_gpio start
sunxi sprite begin
screen_width = 1280
screen_height = 720
bar x1: 320 y1: 320
bar x2: 960 y2: 400
read mbr failed
sprite update error: no data part found
read mbr failed
sprite update error: read image start error
sprite update error: current card sprite failed
now hold the machine
fail to find part named env
Using default environment

In:    serial
Out:   serial
Err:   serial
--------fastboot partitions--------
mbr not exist
base bootcmd=run setargs_nand boot_normal
bootcmd set setargs_nand
key 0
recovery key high 6, low 4
cant find fstbt value
no misc partition is found
to be run cmd=run setargs_nand boot_normal
the part isn't exist
WORK_MODE_BOOT
WORK_MODE_BOOT
[      3.650]Hit any key to stop autoboot:  0 
cant find part named boot
sunxi_flash - sunxi_flash sub-system

Usage:
sunxi_flash read command parmeters : 
parmeters 0 : addr to load(hex only)
parmeters 1 : the name of the part to be load
[parmeters 2] : the number of bytes to be load(hex only)
if [parmeters 2] not exist, the number of bytes to be load is the size of the part indecated on partemeter 1
boota: bad boot image magic, maybe not a boot.img?
sunxi#

**Comment by michalliu** [comment]
Hi, It's totally fine to ask any question here. I just saying I need more information about the problem.
Well you problem semms quite similar to 
https://github.com/cubieplayer/Cubian/issues/231

**Comment by eagletree** [comment]
Okay, I had seen the thread and the hacks, but I did not notice that it is considered an open item. That was what I was really trying to find out, if there was a solution or not. I will follow that thread. Should I close this?

**Comment by michalliu** [comment]
If you resolved your problem through #231. You may consider to close this issue.

**Comment by eagletree** [comment]
I see there appears to be two or maybe three workarounds from that thread. I don't see a resolution for the cubieboard nand problem with cubian since that would mean that I could follow the instructions and end up with a nand-bootable cubieboard 2. The instructions currently say to create a bootable SD, then install and run cubian-nandinstall, which from what I can tell, doesn't work on some cubieboard 2s. I can understand it if the problem can't be corrected, but then perhaps the instructions for installing cubian to nand could be altered to include the best of the workarounds in a step by step manner. I'll close this.
