### ISSUE TITLE
nand安装失败

### ISSUE THREAD

**Issue by huolx** [cubieplayer/Cubian#37]
运行nandinstall后卡死在第一张图，拔除tf卡后重启，卡死在第二张图，用tf卡还可以启动，但是重新nandinstall也是一样的结果。
![img_0130](https://f.cloud.github.com/assets/5162420/907967/e9e8b042-fd71-11e2-836c-0b00d1fd994b.JPG)
![img_0134](https://f.cloud.github.com/assets/5162420/907968/019ab15e-fd72-11e2-9da8-25381bc1200b.JPG)

**Comment by cubieplayer** [comment]
重启再安装一下试试，貌似是执行sync命令时出错了，还是比较奇怪的

**Comment by cubieplayer** [comment]
[有人报告](https://github.com/cubieplayer/Cubian/issues/42) apt-get update 之后可以，建议试一下

**Comment by cubieplayer** [comment]
好像有时候rsync会报这个错误，但是具体原因目前不详，我有一次遇到这个错误，重复执行一下nandinstall就可以了。可能是驱动或者rsync的bug。
