### ISSUE TITLE
Idle system load always 1.00 0.99 0.99

### ISSUE THREAD

**Issue by scr34m** [cubieplayer/Cubian#38]
What is the reason that an idle system load is always 1? It should be 0.00 isnt?

**Comment by cubieplayer** [comment]
Is it a clean system? Maybe caused by software

**Comment by scr34m** [comment]
Yes it was a fresh install nothing modified.

```
top - 08:32:11 up  2:15,  1 user,  load average: 1.00, 1.01, 1.05
  PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND
    3 root      20   0     0    0    0 S   2.6  0.0   3:12.43 ksoftirqd/0
    9 root      20   0     0    0    0 S   2.3  0.0   2:08.30 ksoftirqd/1
11716 root      20   0  4744 1252  880 R   1.3  0.1   0:46.71 top
  396 root      20   0     0    0    0 D   0.3  0.0   0:01.92 usb-hardware-sc
```

**Comment by scr34m** [comment]
FYI, after cubian-update and / or  self compiled kernel both still show 1.00 load on idle system.

**Comment by cubieplayer** [comment]
I don't know the exactly reason. After i [upgrade kernel from 3.3.0 to 3.4.43](http://cubian.org/2013/08/18/kernel-update-to-3.4.43-on-a20/), this problem is sloved.

**Comment by scr34m** [comment]
After update it can't boot so need to reinstall and try after that.

**Comment by cubieplayer** [comment]
I'm sorry to hear that, Can you help me to reproduce the problem, using verbose output of  **cubian-update -v**

**Comment by scr34m** [comment]
I'have a custom kernel for nfs support and enlarged fs maybe thats caused. The system started but very slow booting time around 5 min just show sata init part. Now reinstalling SD card and trying again the update if im done then i will leave a comment about it.

**Comment by cubieplayer** [comment]
Thanks for your help, :+1:

**Comment by cubieplayer** [comment]
You need to backup your customed kernel, caz **cubian-update** won't do it for you.

**Comment by scr34m** [comment]
Updated a fresh 3.3 install so a few timing line:
- 47 sec sata init
- 100 sec eth0 lint not read

Now 3.4 kernel working "Linux Cubian 3.4.43.sun7i+ #18 PREEMPT Sat Aug 17 23:34:45 CST 2013 armv7l GNU/Linux" so maybe my custom kernel caused the problem.

Load seems ok `07:36:46 up 5 min,  1 user,  load average: 0.38, 0.89, 0.48`

**Comment by scr34m** [comment]
I have a feeling that 3.4 slower than 3.3 is that possible?

**Comment by cubieplayer** [comment]
I feels slower too. I don't know the reason. But gpio,mali and a lot wireless driver starts to work at the new kernel. It has long term support from the community.

**Comment by scr34m** [comment]
I will try and see how will works, i think SD card handling changed somehow. If you dont mind then could you build nfs kernel module too with 3.3 or 3.4? (if needed i will create separate ticket)

**Comment by scr34m** [comment]
The problem is that only one core used by the kernel thats the root of slowness!

```
Processor   : ARMv7 Processor rev 4 (v7l)
BogoMIPS    : 2106.81
Features    : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x0
CPU part    : 0xc07
CPU revision    : 4

Hardware    : sun7i
Revision    : 0000
Serial      : 0000000000000000
```

**Comment by scr34m** [comment]
Reverted to 3.3 `Linux Cubian 3.3.0+ #18 SMP PREEMPT Mon Aug 12 03:06:36 CST 2013 armv7l GNU/Linux` but load still under 1 thats intersting `08:08:54 up 4 min,  1 user,  load average: 0.02, 0.05, 0.03`.

CPU info looks much better now so there is something wrong with 3.4 kernel release.

```
Processor   : ARMv7 Processor rev 4 (v7l)
processor   : 0
BogoMIPS    : 670.35

processor   : 1
BogoMIPS    : 670.35

Features    : swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x0
CPU part    : 0xc07
CPU revision    : 4

Hardware    : sun7i
Revision    : 0000
Serial      : 0882146251524848808080541651658c
```

**Comment by cubieplayer** [comment]
Thanks for pointing in the right direction. I will create a issue to **cubietech** to solve this problem.

**Comment by cubieplayer** [comment]
Please create a new ticket for nfs support, that is convenient for others

**Comment by scr34m** [comment]
Could you share 3.3 kernel config, because i built the kernel again and load shown 1.00, but after reverting 3.4 to 3.3 the load was shown the good 0.00 value on idle system. Before kernel build i have used `git reset --hard stage/sunxi-3.3-a20` to be sure source is up to date.

I'm using `https://raw.github.com/mmplayer/sunxi-kernel-config/master/config-cubian-base-sun7i-3.3` as base and only enabled NFS at the moment.

**Comment by cubieplayer** [comment]
I'm using the same kernel config with you which is `https://raw.github.com/mmplayer/sunxi-kernel-config/master/config-cubian-base-sun7i-3.3`

**Comment by cubieplayer** [comment]
May be the magic is `depmod`? The source of `cubian-update` https://github.com/mmplayer/cubian-packages/blob/master/cubian-update/usr/sbin/cubian-update

**Comment by scr34m** [comment]
Same after `depmod -b / -a 3.3.0+` and a reboot.

**Comment by cubieplayer** [comment]
@scr34m `cubian-update` again, now dual-core cpu is supported.It's much faster than before.

**Comment by scr34m** [comment]
System load seems right now and 3.4 smooth as 3.3, everything went fine this time, now time to compile 3.4 NFS :) thanks for fixing!

```Processor    : ARMv7 Processor rev 4 (v7l)
processor   : 0
BogoMIPS    : 763.49

processor   : 1
BogoMIPS    : 766.11

Features    : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x0
CPU part    : 0xc07
CPU revision    : 4

Hardware    : sun7i
Revision    : 0000
Serial      : 0000000000000000```

**Comment by scr34m** [comment]
NFS compiled in just now noticed, thanks!
