### ISSUE TITLE
cubieboard a10 cubian x1 desktop nand install

### ISSUE THREAD

**Issue by zyg99** [cubieplayer/Cubian#380]
I apologise if I missed this issue while searching the forum...

I can boot my cubie a10 from sd without a problem, and if I perform sudo cubie-nandinstall it seems like it gets completed (I get the shutdown message at the end). But then when I boot without the sd card inserted, I get stuck on the cubian x logo... I tried to wait for an hour but it doesnt seem to get pass that...

Does anybody else have similar issues?

Thanks

**Comment by michalliu** [comment]
take a look http://cubian.org/2014/06/30/troubleshooting-nandinstall-on-a20/

**Comment by michalliu** [comment]
closed as duplicated with https://github.com/cubieplayer/Cubian/issues/381
