### ISSUE TITLE
Kernel source and how to build the version in the distribution

### ISSUE THREAD

**Issue by ghost** [cubieplayer/Cubian#384]
I am evaluating the use of a CubieBoard2 in a hobby project to replace a PC, and I encounter
an issue in the audio driver.  I asked on the sunxi group and I get referred to "Emilio's kernel"
that should have improved audio drivers.  So I am trying to find out how to switch to that kernel.
First, I try to find out what kernel is used in Cubian, and how I would go about compiling that from
sources.   This is where I already get stuck.  The tab on the startpage says I can do:
apt-get install linux-source
However, it installs a generic linux source from Debian, another version than is in the Cubian
binary kernel, and without the drivers for the A20-specific hardware.
Is that direction wrong?  I tried the second method as well, but of course I will get the current
version of that git archive, not the one that was used to compile the distributed binary kernel.
It appears to be different.   Is it safe to just compile the newest version or will there be issues
that were fixed in the Cubian build that are not in that version?
Is there any experience with "Emilio's kernel" here?

**Comment by michalliu** [comment]
linux-source is a virtual package, You should see a list of available source packages. from your description you need to install

```
apt-get install linux-source-3.4.79-sun7i
```

**Comment by ghost** [comment]
Thank you for your reply!
'apt-get install linux-source' installs linux-source-3.2 without any further questions.  I think it is
just a standard debian kernel source.   So the first method on the site does not work.
I have now used the 2nd method on the site to install the sources from git.
Hopefully that is ok too?

**Comment by michalliu** [comment]
Yeah, That's ok.
