### ISSUE TITLE
Cubian failure on boot - are all data lost?

### ISSUE THREAD

**Issue by res55** [cubieplayer/Cubian#385]
![cubie-error](https://cloud.githubusercontent.com/assets/2394465/4679095/e7c0fa3c-55fd-11e4-9c82-2134b3d28244.JPG)

My wife worked well with her Cubie and was so happy, that there is now no noise anymore in her room. She has her Cubian on an 16 GB SD-card and there is also her home dir.

When we came back from holidays she wanted to switch on her Cubie but it failed. She did not note down the original error msg but restarted several times to get it running. Now I attach a photo of the boot messages.
Can anyone help, how to proceed? Perhaps the filesystem (ext4) failed and must be repaired? But how?

Res

**Comment by michalliu** [comment]
Hi, You can try to run `fsck /dev/mmcblk0p1` on another linux system to repair the file system. The booting log is at serial line in older cubian. If you don't have a serial line, you need to change either uEnv.txt or boot.scr modify the kernel arguments, let kernel send booting log to tty0

**Comment by res55** [comment]
with sudo fdisk -l I found the card as /dev/sdc1
and I gave umount /dev/sdc1 to unmount.
Tried to repair with sudo fsck.ext4 -v -f -c /dev/sdc1 
But got lots of errors, finally this:
      cubieboard: *********\* WARNUNG: Noch Fehler im Dateisystem  **********

```
  124481 Inodes sind in Benutzung (13.48% von 923520)
     599 nicht zusammenhängende Dateien (0.5%)
      30 nicht zusammenhängende Verzeichnisse (0.0%)
     # von Inodes mit ind/dind/tind Blöcken: 0/0/0
     Histogramm der Tiefe von Erweiterungen: 111497/51
       2234196 Blöcke werden benutzt (57.15% von 3909376)
       0 ungültige Blöcke
       1 große Datei

   96957 reguläre Dateien
   13839 Verzeichnisse
       0 zeichenorientierte Gerätedateien
       0 Blockgerätedateien
       1 Fifo
      22 Verknüpfungen
   13675 symbolische Verknüpfungen (12924 schnelle symbolische Verknüpfungen)
       0 Sockets
```

---

```
  124461 Dateien
```

But a new reboot gave the same error. What can I do?

**Comment by michalliu** [comment]
so, what happend finally?

**Comment by res55** [comment]
I have redone the above procedure 2 further times and that ended without an error, so I was able to boot.
All data where still there, could be backuped now ;-)  and my wife is happy to continue working with her cubie.
Thanks.

**Comment by michalliu** [comment]
Glad to hear that :)
