### ISSUE TITLE
Cubian X on Cubietruck stalls at starting screen

### ISSUE THREAD

**Issue by BogdanIP** [cubieplayer/Cubian#386]
I installed Cubian X desktop vga version, using ubuntu, on a micro-sd card, 
(http://www.amazon.com/Sony-Class-Memory-SR16UYA-TQMN/dp/B00BW6KCW2)
I followed the instructions precisly from https://github.com/cubieplayer/cubian/wiki/Install-Cubian but when i am trying to boot Cubian X on Cubietruck the screen stalls at the opening screen with the Cubian X logo and the orange led is blinking continuously. I have tried, a couple of months ago, with the older version of Cubian and I had the same result. the screen was stalling and nothing was happening.
I don't know why this is happening. 
Does anyone else encountered this problem ?
Does anyone know why this is happening?
Is there a solution for this problem?
It boots from nand into android without a problem.

Thank you in advance for your attention to this matter.
Bogdan

**Comment by paulovillani** [comment]
I'm having the same problem. Changing to tty2 some erros are shown e some seg faults are displayed. I'm guessing thats some kernel problem.

**Comment by BogdanIP** [comment]
How do i change to tty2 ?

**Comment by BogdanIP** [comment]
I managed to solve the problem.
it seems that in the boot partition,in the file UEnv.txt the resolution was missing.
Insead of disp.screen0_output_mode=EDID:0 it should have been for example : disp.screen0_output_mode=EDID:1280x720p50.
http://linux-sunxi.org/UEnv.txt
I hope this helps.
Good luck
Bogdan

**Comment by michalliu** [comment]
`disp.screen0_output_mode=EDID:0` means autodetect resulution, I don't understand why it failed.
