### ISSUE TITLE
SSD operations crash system

### ISSUE THREAD

**Issue by mbierlee** [cubieplayer/Cubian#392]
I've attached an SSD to my Cubietruck and installed Cubian-nano-x1-a20-cubietruck-hdmi to micro-sd. I can partition the SSD just fine, but whenever I try to format a file system on it or zero-fill the whole drive, Cubian seems to crash. The HDMI output goes away and all connected SSH sessions freeze and eventually time-out. The activity LED seems to indicate that it either shut down or is locked-up, as it is not lighting up anymore.

Anywhere to see what might cause this?

**Comment by cs42** [comment]
This maybe a problem with your power source. On writing a SSD draws more power than on reading. Depending on the SSD up to 5W. If your power source rating is too low, the power will drop if the SSD starts writing and everything will fail...

**Comment by mbierlee** [comment]
This was indeed the issue. I hooked it up to a 5.1V 0.8A adapter, which is definitely not enough. Thanks!
