### ISSUE TITLE
Img does not work in PhoenixSuit

### ISSUE THREAD

**Issue by deares** [cubieplayer/Cubian#393]
I am still exploring CubieTruck, i.e. which image to use, which route to get it into the CT.

Is there any reason that the Image would not load into PhoenixSuit? Somehow it seems to have format issues and therefore does not recognize it as an image.  

Well, was using the latest releases: 
Cubian-desktop-x1-a20-cubietruck-vga.img
Cubian-nano-x1-a20-cubietruck-vga.img

Error message: Open Firmware failed! Possible reasons .. version too old .. format broken .. firmware blocked by other application.

Ciao.

**Comment by michalliu** [comment]
This is **NOT** a nand image, checkout https://github.com/cubieplayer/Cubian/wiki/Install-Cubian

**Comment by nocolour** [comment]
NAND version cubian image bellow
http://dl.cubieboard.org/software/a20-cubietruck/cubian/20140116/ct-cubian-r4/cubian-r4-nand.img.gz

PhoenixSuit is windows base software.
Reason it NOT working:
1.)Android USB device driver not working - USB driver issue or Windows problem
2.)Your existing nand OS NOT android. 
3.)FEL button not function. 
4.)Wrong Image files! (SD image and nand image are different)

*\* DON'T USE USB 3.0 Port!!!

***Once you change the default nand OS "Android" to linux. PheonixSuit can not use any more.

SD IMAGE writer download :http://dl.cubieboard.org/software/tools/windows/ImageWriter.exe
Burn SD image to SD card & boot from SD.

Bellow for NAND image ONLY!!
For MS Windows 
1.) Recommended use windows XP
2.) Make sure install the correct usb driver for cubieboard/cubietruck
3.) Use PhoenixUSBPro (search from internet, need license key).

For Linux
1.) Recommended use Ubuntu/Lubuntu
2.) Install & run Livesuite with sudo/root permission.

Forget PhoenixSuit, if default nand os not android any more.
All tool can download from http://dl.cubieboard.org. PhoenixUSBPro from other site, search from google. The version should 3.3.0. PhoenixUSBPro can flash any Allwinner A10 & A20 board NAND. DON'T FORGET press FEL, B4 power on.

Thanks!

**Comment by luzemario** [comment]
All the Cubieboard links are dead.
