### ISSUE TITLE
some monitors flicker with cubian on cubietruck

### ISSUE THREAD

**Issue by fspegni** [cubieplayer/Cubian#397]
Hallo,

I've just installed your Nano image and installed the X support following:

http://cubian.org/2013/09/29/install-lxde-with-opengles-accelerated-on-cubian/

I noticed that while I attach the board at a small toshiba (model 19AV734G( monitor, everything works ok. when I connect it to a bigger samsung tv (model LE46C630K1WXZG) it starts flickering as soon as the cubian driver is shown at boot.

the flickering is not constant: it happens every few seconds (maybe every 30"), and it lasts maybe one second. during the flickering I can still see the background and all the application, but it's very disturbing.

is there any way I can help you to debug this? should I run some command or send you some file as additional information?

thanks for this project, very simple and well documented

**Comment by michalliu** [comment]
Maybe the kernel failed to detect your screen resolution, You'd better change the kernel command line, follow this issue to resolve it.Please let me know your result, thanks.
https://github.com/cubieplayer/Cubian/issues/386

**Comment by fspegni** [comment]
I followed the instructions, but the outcome didn't change. 

One thing I've noticed is that if I:
1. plug TV SVGA cable to cubietruck
2. turnon cubietruck
3. power on TV

it doesn't flicker. If I switch steps 1 and 2 it works as well. If I move step 3 before step 2, it flickers. In order to stop flickering I can run the following script:

```
# xrandr --newmode "1024x768_60.00" 63.50 1024 1072 1176 1328 768 771 775 798 -hsync +vsync
# xrandr --addmode default 1024x768_60.00
# xrandr --output default --mode 1024x768_60.00
```

it seems to me it may not be a problem of "right" kernel parameters. does it ring any bell to you?
