### ISSUE TITLE
resize2fs 成功但 nand size 沒變

### ISSUE THREAD

**Issue by daiyoko** [cubieplayer/Cubian#40]
請問下面 nand size 正確嗎？？？

a20 板
Linux Cubian 3.3.0+ #13 SMP PREEMPT Sun Aug 4 02:40:54 CST 2013 armv7l GNU/Linux

root@Cubian:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs          952M  777M  128M  86% /
/dev/root       952M  777M  128M  86% /
devtmpfs        487M     0  487M   0% /dev
tmpfs            98M  220K   98M   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           195M     0  195M   0% /run/shm
tmpfs           488M   32K  487M   1% /tmp
tmpfs           488M     0  488M   0% /var/tmp
root@Cubian:~# cat /proc/partitions 
major minor  #blocks  name

  93        0    3866624 nand
  93        8        512 nand1
  93       16        256 nand2
  93       24    3849472 nand3
 179        0   15637504 mmcblk0
 179        1     976896 mmcblk0p1
root@Cubian:~# cat /etc/fstab
# <file system>  <mount point>   <type>  <options>   <dump>  <pass>

/dev/mmcblk0p1  /       ext4    defaults    0   1
tmpfs   /tmp    tmpfs   defaults    0   0
tmpfs   /var/tmp    tmpfs   defaults    0   0
root@Cubian:~#

**Comment by cubieplayer** [comment]
這個過程稍微有點兒復雜，建議參考[這篇教程](http://askubuntu.com/questions/24027/how-to-resize-a-ext4-root-partition-at-runtime)處理一下。我也寫好了一個工具，即將發布。

**Comment by cubieplayer** [comment]
腳本已經制作好了，安裝步驟
Step 1. Add GPG key (root privilege is needed)

> wget -O - http://packages.cubian.org/cubian.gpg.key | apt-key add -

Step 2. Add apt source, add line to /etc/apt/sources.list

> deb http://packages.cubian.org/ wheezy main  

Step 3. Install

> apt-get update && apt-get install cubian-resizefs  

最後執行 `cubian-resizefs`即可

**Comment by michalliu** [comment]
Please pay attention on cubian-resizefs tips, you need run `resize2fs /dev/mmcblk0p1` after a reboot.
