### ISSUE TITLE
cubian-x1-a20-hdmi does not boot ! (solved)

### ISSUE THREAD

**Issue by tofan8** [cubieplayer/Cubian#415]
hi
i get Cubian-desktop-x1-a20-hdmi.img and write that on sd card with "Win32DiskImager"
when i press power button green led is Bright for about 7 second after that start blinking for ever
time of blinking is Fixed and blue led is totally off
img file md5 : D218301DA4DB2EB4CA9A6173BF0B67C5
i don't have cubieboard in dhcp table on router
I've already older version of cubian on my sd card and work without problem
but x1 version looks don't start
thanks

**Comment by tofan8** [comment]
i think i trap in first boot cubian-config 
i dont have hdmi diplayer i just connect a keyboard , What are the keys to skip cubian-config ?
after skip cubian-config network started and i can connect with ssh .

**Comment by tofan8** [comment]
ok i wait more times , near 5 minute and cubieboard start successfully

**Comment by tofan8** [comment]
ok i press cntrl+alt+f2 and see in random boot freez in random steps .
every 10 times try to boot cubian start !

**Comment by kristjanvalur** [comment]
Looks like the problem that I had. 
You need to see this:  http://cubian.org/2014/07/05/resolve-stability-issue-on-cb2/
Basically, after extracting the image, you need to replace /boot/script.bin with one that is provided above.  This sets the cpu frequency to a more conservative value during the boot process.

Then, take a look at this:  http://cubian.org/2013/09/18/fix-random-crash/

**Comment by tofan8** [comment]
thanks very much kristjanvalur . that resolve my problem.
after boot i run command "top" and see atd is in the top and use 45% of cpu ! what is it ?
and when i use cpuburn-sunxi after 2 minute cubie poweroff !

**Comment by kristjanvalur** [comment]
Hi.
This also happened to me, but only after I followed these steps:  
apt-get update && apt-get install linux-image

(I actually had to select a kernel, and it was the 7i kernel)

Anyway. I tried again, installing the os to the flash card, then updating script.bin and it started up fine.
I then did:
cubian-update --verbose --update-board-cfg
and 
apt-get update && apt-get upgrade

after rebooting, everything was fine.  I don't know what was causing atd to take all the cpu, I think it had something to do with trying to upgrade the kernel.

**Comment by tofan8** [comment]
thanks
you uses cubieboard 2 ? can u put your script.bin ?

**Comment by tofan8** [comment]
can you test your cpu stability with cpuburn-sunxi ?

**Comment by kristjanvalur** [comment]
I just used this one:  https://github.com/mmplayer/cubian-updates/blob/a20-3.4.79_2/boot/script.bin?raw=true
I don't have this board anymore, so I cannot do the cpuburn-sunxi.

**Comment by tofan8** [comment]
thanks  kristjanvalur .
Well my boot problem solved
but cubie is not stable in 1000mhz feq .
and "atd" run in start and most cpu usage !

**Comment by tofan8** [comment]
ok i run this command :
sudo service atd stop
sudo find /var/spool/cron.d -type f -delete
sudo service atd start
and atd sleep :D
