### ISSUE TITLE
Cubian Nano auto login

### ISSUE THREAD

**Issue by FreedomLabsIO** [cubieplayer/Cubian#416]
How do i make Cubian Nano auto login (cubie / cubie) ?

I've tried to change the /etc/inittab file following this tutorial: http://elinux.org/RPi_Debian_Auto_Login

commented
1:2345:respawn:/usr/sbin/cubian-agetty tty1 38400

inserted
1:2345:respawn:/usr/bin/login -f cubie tty </dev/tty1 >/dev/tty1 2>&1

But it doesn't work.

Thanks

**Comment by vovcacik** [comment]
Enable and update `default_user` and `auto_login` in `/etc/slim.conf`.

**Comment by ghost** [comment]
it says he is using cubian Nano.  Slim is graphical (X desktop or whatever its called) dependant
