### ISSUE TITLE
Can't download images.

### ISSUE THREAD

**Issue by pedrosurf** [cubieplayer/Cubian#424]
Hi,
I'm trying to download cubian desktop image for cubiboard 2 but I'm getting "Error: Invalid response from tracker" and "Error: Timeout contacting tracker" from bt-cn.cubian.org/announce.php and bt-cn.cubian.org:8307/announce.php.

I'm using Ktorrent to download it.

What can I do in order to download the image?

**Comment by andrewklau** [comment]
There doesn't seem to be any seeders right now either for the latest build, would be nice if it could get hosted some where else..

**Comment by maswan** [comment]
If I can get a private rsync module to cron updates from, I can put up a mirror that can handle the load for http downloads.

**Comment by thhunder** [comment]
i have the nano-headless image now Online: http://thhunder.de/dl/Cubian-nano+headless-x1-a20.7z

i is the "untouched" image but not Original zipped file. i did a "re-zip" the rest is untouched! to keep it online for others!

**Comment by EtlamGit** [comment]
Re-Zipped means that the MD5 is not the same, therefore nobody can proof if that file is really the original one. Maybe the image file inside that 7zip could be checked.
Could someone "official" provide md5 hashes for all files please?
That is the only way for users to ensure they got the right file.

**Comment by EtlamGit** [comment]
I just start to provide sample data for the file mentioned above:
The command: find . -type f -print0 | xargs -0 md5sum
generates this output:

```
c26aebfd8e4a9a8d7cd8ebc1fd26955e *./Cubian-nano+headless-x1-a20.7z
1bee809d130386ff72dc2344f1742be1 *./Cubian-nano+headless-x1-a20.img
```

So the .7z hash is different to files found on MEGA (linked in #410), but the .img file seems to be the same. This is at least some minor indication that the available files are original.

**Comment by michalliu** [comment]
Hi, tracker server is online now, problem fixed
