### ISSUE TITLE
Driver USB Ethernet Adapter

### ISSUE THREAD

**Issue by 2w-consultoria** [cubieplayer/Cubian#43]
Hi, 
please, can you compile to me the driver for this USB Ethernet Adapter?
ASIX AX88772: http://www.asix.com.tw/FrootAttach/driver/AX88772C_772B_772A_760_772_178_LINUX_Driver_v4.10.0_Source.tar.bz2

Thanks.

Congratulations for your nice job!

**Comment by 2w-consultoria** [comment]
Hi, anyone can help me?

**Comment by cubieplayer** [comment]
Closed duplicated with https://github.com/cubieplayer/Cubian/issues/166
