### ISSUE TITLE
Recommended toolchain for Cubian X1

### ISSUE THREAD

**Issue by nickaein** [cubieplayer/Cubian#456]
Hi,

I am trying to cross-compile Qt for my Cubietruck running Cubian X1. There are two toolchains provided here: https://github.com/cubieplayer/Toolchain  as two branches:
- `arm-none-linux-gnueabi` based on Codesourcery.
- `arm-linaro-2013.06` based on Linaro

Which one is recommended? Besides their origin, what is the practical difference between these two toolchains?

**Comment by cubieplayer** [comment]
arm-none-linux-gnueabi is recommended, so it is the default branch.
