### ISSUE TITLE
Regenerate ssh keys at first boot

### ISSUE THREAD

**Issue by pgauret** [cubieplayer/Cubian#46]
Hi!

Thanks a lot for Cubian, this is great work! 

I've noticed that the system came with existing SSH keys, which is a security concern. The fix is to regenerate them by running:

```
rm /etc/ssh/ssh_host_*
dpkg-reconfigure openssh-server
```

This could either be added to the documentation, or even better taken care of in a startup script that would run once.

**Comment by cubieplayer** [comment]
Hi, Thanks for sharing, I mark it as a bug to be sovled

**Comment by phpmysqlfreak** [comment]
Perhaps you can go by moving /etc/rc.local to /etc/rc.local.orig and create new /etc/rc.local containing:

#!/bin/bash
rm /etc/ssh/ssh_host_*
dpkg-reconfigure openssh-server
mv /etc/rc.local.orig /etc/rc.local

The original /etc/rc.local is restored by starting /etc/rc.local once, which happens every boot ;)

**Comment by cubieplayer** [comment]
Closed by this commit https://github.com/mmplayer/fsupdate/blob/base/common/etc/init.d/cubian-firstrun

**Comment by cubieplayer** [comment]
Fixed on [r5](http://cubian.org/2013/09/06/cubian-r5-for-a10-and-r2-for-a20-released)
