### ISSUE TITLE
Download Cubian

### ISSUE THREAD

**Issue by cuxmini** [cubieplayer/Cubian#461]
Hi,
is it realy not possible to get a normal Download?
I don't use torrent - and i'm not willing to do it in the furure.
So i need a http or ftp download source!

**Comment by michalliu** [comment]
Http download
http://pan.baidu.com/s/1hqzNwtY

**Comment by gregor2005** [comment]
Thanks for the link. Can anybody please publish the checksome of the files on the main page. If anybdoy upload the files on a tracker please post the links I will help to seed it.
