### ISSUE TITLE
 board refused to start up with nand

### ISSUE THREAD

**Issue by mlibre** [cubieplayer/Cubian#469]
i install cubian A10 on sdcard.
then run cubian-nandinstall.
but board refused to start up.
the problem is uEnv.txt
root not setted to root=/dev/nandb.
i manually boot with sdcard.
mount /dev/nandb to /mnt.
edit /mnt/boot/uEnv.txt.
and set root to /dev/nandb.
and then problem was fixed.
and cubi board boot up with nand

**Comment by michalliu** [comment]
Yeah, It's a bug

**Comment by michalliu** [comment]
A10 user is few, I never discover this bug. Thanks for reporting

**Comment by mlibre** [comment]
your welcome.
thanks.

**Comment by necenzurat** [comment]
@mlibre solutin worked for me, thanks.
