### ISSUE TITLE
sudo not working

### ISSUE THREAD

**Issue by zoof** [cubieplayer/Cubian#5]
I don't know if this is a serial only issue but I am unable to use sudo, although the default user (cubie) owns large portions of the file system so I can write to configuration files.

The error message when I try to use sudo is:
sudo: effective uid is not 0, is sudo installed setuid root?

**Comment by cubieplayer** [comment]
Sry, This should be fixed now. Please [download the system IMG](http://cubieplayer.github.io/Cubian/dist/Cubian-base-r2-arm.img.bz2) again.

The MD5 hash should be `5ba3efca2e739f55ff81772159115452`

This is because of the incorrect owner of file `/usr/bin/sudo`

**Comment by zoof** [comment]
Now works.  Thank you!
