### ISSUE TITLE
NFS kernel modules

### ISSUE THREAD

**Issue by scr34m** [cubieplayer/Cubian#52]
Please include nfs client / server modules into cubian-update for both kernel version 3.3 and 3.4 if possible, thanks!

**Comment by cubieplayer** [comment]
It's compiled now
Ref: https://github.com/mmplayer/sunxi-kernel-config/commit/80623f9aa133d512e35849754b3cd89b3d6ca6ae

**Comment by scr34m** [comment]
Thanks!
