### ISSUE TITLE
Cubian on HDD?

### ISSUE THREAD

**Issue by mazBR** [cubieplayer/Cubian#53]
Hi cubie,
 As i weared out my cubie1 nand flash, i've got a brand new cubie2 and this time i would like to install on nand only the boot partition and the entire debian on a sdd hdd attached.

 what are the changes to do? can you help me on that?

regards.

**Comment by cubieplayer** [comment]
It might possible. You put kernel to the first partition, then set the correct root device in boot args. I will write a tutorial if i had time. The major things you need to do is:
1. let u-boot boot your kernel
2. kernel must be compiled with built-in SATA driver
3. set the correct bootargs when booting kernel

**Comment by mazBR** [comment]
do you think it's possible to change nandinstall so it can copy the files to hdd instead of nand? off course we should change the fdisk args to do so..

**Comment by cubieplayer** [comment]
@mazBR That's not the point. You can give a try.

**Comment by mazBR** [comment]
cubie, how do i change the bootargs? changing the uEnv.txt ?

**Comment by cubieplayer** [comment]
@mazBR It depends on the system installation type. If you system running on NAND. You should change uEnv.txt.
If you system running on MMC. You should change boot.scr.

I'd like to write a tutorial on this subject later

**Comment by bayuemu** [comment]
我看到论坛上说：

Re: cubian for cubieboard2 kernel updates to 3.4.43
« Reply #16 on: August 19, 2013, 05:59:18 PM »
Quote from: pcklee123 on August 19, 2013, 07:20:50 AM

```
Thanks. Can you compile the sata support built in so we can have the roofs on sata drive?
```

I have compiled the sata driver into kernel for convenience at server side.

是不是意味着kernel 3.4.43 已经  built-in SATA driver？？
假如是：那就意味着我们升级到kernel 3.4.43，只需要修改 boot.scr 或者  uEnv.txt，就可以 使用sata 做为 rootfs 了？？.

**Comment by cubieplayer** [comment]
@bayuemu 是的，你用cubian-update 更新一下内核，SATA驱动已经编译进内核了，理论上你可以使用SATA上的rootfs，修改下uEnv.txt和boot.scr就可以了。我没试过，应该可行。

**Comment by bayuemu** [comment]
谢谢大神，哈哈 你们是中国 linux 开源界最帅的，哈哈，真心的希望你们能成为影响世界linux的一部分，

**Comment by mazBR** [comment]
cubie... am i wrong, or the sata is already bultin? i've extracted .config from uImage used on the cubian for cb2, and almost everything is marked as "*" there... (including SCSI and SATA)

**Comment by cubieplayer** [comment]
@mazBR yes,The SATA drvier is built-in now.

**Comment by bayuemu** [comment]
测试完成，nand+sata 方式启动成功！

**Comment by cubieplayer** [comment]
Closed duplicated with https://github.com/cubieplayer/Cubian/issues/152
