### ISSUE TITLE
Enable support for USB webcams

### ISSUE THREAD

**Issue by zerodamage** [cubieplayer/Cubian#54]
To allow for use of USB webcams, could you please enable support for UVCvideo, either as kernel built-in or module. Kernel config flag is:
CONFIG_USB_VIDEO_CLASS

**Comment by cubieplayer** [comment]
I've compiled the driver not sure if it works. It's available via `cubian-update`

**Comment by zerodamage** [comment]
Not present in the A10 module repository, i need it as an A10 module, sorry i did not mention it

Could you try with the following:

# 

# Multimedia core support

# 

CONFIG_VIDEO_DEV=y 
CONFIG_VIDEO_V4L2_COMMON=y 
CONFIG_VIDEO_ALLOW_V4L1=y 
CONFIG_VIDEO_V4L1_COMPAT=y 
CONFIG_VIDEO_MEDIA=y 

# 

# Multimedia drivers

# 

CONFIG_VIDEO_V4L2=y 
CONFIG_VIDEO_V4L1=y 
CONFIG_VIDEOBUF_GEN=m 
CONFIG_VIDEOBUF_VMALLOC=m 
CONFIG_VIDEO_CAPTURE_DRIVERS=y 

CONFIG_V4L_USB_DRIVERS=y 
CONFIG_USB_VIDEO_CLASS=m 
CONFIG_USB_VIDEO_CLASS_INPUT_EVDEV=y

**Comment by cubieplayer** [comment]
Marked as accepted

**Comment by mindspawn** [comment]
I am running cubian on the A10 and still cannot seem to see webcam support. Is it enabled in the latest release?
I am running the following kernel "Linux Cubian 3.4.43+ #10 PREEMPT Tue Aug 20 06:04:29 CST 2013 armv7l GNU/Linux"

**Comment by zerodamage** [comment]
@cubieplayer has compiled the modules, but they have not been committed to cubian-update yet as far as I can see. They are in the A20 branch however

**Comment by cubieplayer** [comment]
Here is the kernel config for A10 https://github.com/mmplayer/sunxi-kernel-config/blob/master/config-cubian-base-sun4i

**Comment by mindspawn** [comment]
Thanks. That worked.

**Comment by cubieplayer** [comment]
@mindspawn np,it's pushed to the server now

**Comment by micromys** [comment]
Question? I'm new here. How can I use this on my A10. I've installed the latest A10 cubievoard1 R4 2 weeks ago. Thx..

**Comment by cubieplayer** [comment]
Fixed on [r5](http://cubian.org/2013/09/06/cubian-r5-for-a10-and-r2-for-a20-released)
