### ISSUE TITLE
resizefs usage question

### ISSUE THREAD

**Issue by lubeless** [cubieplayer/Cubian#55]
Hey there,

Im fairly novice at this so this might sound like a stupid question, but I couldnt find the answer anywhere.

I'd like to use the cubian-resizefs tool.

Its installed and everything has been updated.

I cant seem to run the cubian-resizefs END_SECTOR_POS (last part being replaced by a number)

i get -bash: cubian-resizefs: command not found

do you have a suggested number for me to try (got a 16gb sd card that id like to use as much as possible)

thanks for your patience... trying to learn

**Comment by cubieplayer** [comment]
`cubian-resizefs` is not installed by default. Follow the tutorial http://cubian.org/2013/08/12/enlarge-cubian-rootfs-partition/.  
or you can do it [manaually](http://askubuntu.com/questions/24027/how-to-resize-a-ext4-root-partition-at-runtime)

**Comment by lubeless** [comment]
As i said i already installed cubian-resizefs by following this tutorial.  i just cant seem to get it to work.

**Comment by zerodamage** [comment]
try to run it with sudo, sometimes it will tell you not found, if it is not able to run without sudo

sudo cubian-resizefs

alternatively you can reinstall with

sudo apt-get install --reinstall cubian-resizefs

**Comment by lubeless** [comment]
Yeah I did that already.  Also tried to delete and recreate the partition using fdisk, couldnt reboot. I must have failed somewhere. I also tried to resize thepartition using gparted on a ubuntu virtual machine but it didnt detect my sd card properly.   I will try all of these again tonight from a freshly formated sd card.  Thanks for the support! Ill keep updating this post as i try to progress.

**Comment by lubeless** [comment]
I reinstalled, didnt work either (as root or sudo).  reformated my sd card and put the image back on it, tried everything again, didnt work.  What line should i use to add the "deb http://packages.cubian.org/ wheezy main" line to the sources.list ? I did it this way

echo "deb http://packages.cubian.org/ wheezy main" | sudo tee -a /etc/apt/sources.list 

then apt-get update

**Comment by cubieplayer** [comment]
What's the output of  `fdisk -l`. Did you run `resize2fs` after `cubian-resizefs`?  BTW, Cubian-resizefs only supports SD-card system.

**Comment by lubeless** [comment]
Yes I know but still, nothing seemed to work for me. I tried resize2fs too, didnt work since the partition did not resize properly in the first place so I couldnt resize the sys file.  

I ended up doing a nand installation (4gb) and then installed LXDE and Gparted.  Resized the partition on the SD card using Gparted with no issue whatsoever.   Thanks for the support though.
