### ISSUE TITLE
重启后蓝灯为什么总是闪？

### ISSUE THREAD

**Issue by wolfan** [cubieplayer/Cubian#56]
sudo reboot重启后蓝灯总是不停的在闪这是怎么回事呢？

**Comment by mmplayer** [comment]
网络断掉了就会闪，reboot就断网了，所以在闪

**Comment by wolfan** [comment]
可是网络正常啊，我还wget了个文件回来，所以应该是正常的啊。

**Comment by cubieplayer** [comment]
那这就是Bug了，你是用的有线还是无线？A10还是A20，什么版本的cubian，有没有cubian-update？

**Comment by wolfan** [comment]
有线 A10，版本不记得了，上个月装上的。没有Update过。
