### ISSUE TITLE
cubian-update problem

### ISSUE THREAD

**Issue by mahdichi** [cubieplayer/Cubian#57]
hi, i try update kernel but when i run cubian-update it came with error

root@Cubian:~# cubian-update -v
Update From: https://github.com/cubieplayer/cubian-update.git
Root Path: /
Update Kernel: yes
Update Modules: yes
Branch: a10
SysInstallType: mmc
**\* Downloading firmware (this may take a while)
Cloning into '/root/.cubian-update'...
error: gnutls_handshake() failed: A TLS packet with unexpected length was received. while accessing https://github.com/cubieplayer/cubian-update.git/info/refs
fatal: HTTP request failed
!!! Failed to download firmware,Please check internet connection

please help.

**Comment by cubieplayer** [comment]
I searched the error message, found this http://stackoverflow.com/questions/13524242/error-gnutls-handshake-failed-git-repository

**Comment by mahdichi** [comment]
thanks, i try that.

**Comment by newgordan** [comment]
Hi, i had a simular problem when i tried to update my kernel 3.3+ with cubian-update.

i allways get a download error from git command with different error messages.
After a long search for a solution, to fix this handshake error but without any success, i diabled the cpufreq daemon on my system. 
After a reboot of my cb2 the problems are gone.

sudo -i
update-rc.d cpufrequtils disable
update-rc.d cubian-ondemandcpufreq disable
reboot

to reenable cpufrequtils:
sudo -i
update-rc.d cpufrequtils enable
update-rc.d cubian-ondemandcpufreq enable
reboot

@cubieplayer : thanks for the new 3.4.43 kernel with dual core support!! :+1:
