### ISSUE TITLE
CSI Camera Module Problem

### ISSUE THREAD

**Issue by mahdichi** [cubieplayer/Cubian#58]
Hi 
I try test OV7670 camera in cubian, i change script.bin csi1 part.
when i modprobe sun4i_csi1 it detect my camera

root@Cubian:/home/cubie# modprobe sun4i_csi1
root@Cubian:/home/cubie# lsmod
Module                  Size  Used by
ov7670                 10990  1
sun4i_csi1             29433  0
videobuf_dma_contig     7227  1 sun4i_csi1
videobuf_core          22230  2 sun4i_csi1,videobuf_dma_contig
cpufreq_stats           2930  0
ump                    58137  0

but when i try capture a frame it came with error.

root@Cubian:/home/cubie# luvcview -d /dev/video1 -i 10 -f YUYV
luvcview 0.2.6

SDL information:
  Video driver: fbcon
  Hardware surfaces are available (7200k video memory)
Device information:
  Device path:  /dev/video1
Stream settings:
  Frame format: YUYV
  Frame size:   640x480
  Frame rate:   10 fps
Unable to map buffer: Invalid argument
 Init v4L2 failed !! exit fatal

please help me.

**Comment by zerodamage** [comment]
Have you tried running it under X?

**Comment by mahdichi** [comment]
yes, i try guvcview but when i run it, it came with error that Unable to open device.
i try run it with command line and set device to be /dev/video1 but it doesn't work to.

**Comment by zerodamage** [comment]
maybe this will give some info, it also saves to file, so it does not depend on output graphics working:

try sudo fswebcam -v -d v4l2:/dev/video1
and
try sudo fswebcam -v -d v4l2:/dev/video1 --list-inputs

**Comment by mahdichi** [comment]
hi, i try your command with usb webcam and it work fine but
in Cubian r5 there is no csi kernel driver.

it's be good if add sun4i-csi1 module in next update.

**Comment by cubieplayer** [comment]
I will try to compile the webcam driver

**Comment by mahdichi** [comment]
thanks.

**Comment by cubieplayer** [comment]
Hi, These modules are compiled now, you can try `cubian-update` to get it, Please re-open the issue if it's not working.
