### ISSUE TITLE
SPI Kernel Module

### ISSUE THREAD

**Issue by mahdichi** [cubieplayer/Cubian#59]
Hi,

Please add SPI module to kernel.

thanks in advance.

**Comment by zerodamage** [comment]
For cubieplayers reference, these should be the flags:
CONFIG_SPI=y
CONFIG_SPI_MASTER=y
CONFIG_SPI_SUN4I=m

**Comment by mahdichi** [comment]
thank you for the answer, but i don't have kernel source now.
I want to suggest if possible, add this module to cubian-update.
thanks again.

**Comment by cubieplayer** [comment]
Kernel source link is in the wiki https://github.com/cubieplayer/Cubian/wiki/Wiki-Index
I will compile SPI support later

**Comment by cubieplayer** [comment]
It's compiled for A10 https://github.com/mmplayer/sunxi-kernel-config/commit/b2e1cd6d8902ee06a01f64dbae72814bce8bf8d3
But this driver is not available on A20

**Comment by mahdichi** [comment]
thanks, i appreciate if add SPI_SPIDEV module too, and
One question, 
i try patch spi driver in other kernel source for SPI full-duplex, but i couldn't. 
does it work for your driver?

**Comment by cubieplayer** [comment]
SPI module is enabled on A10, but the driver doesn't work on A20
