### ISSUE TITLE
mount: you must specify the filesystem type

### ISSUE THREAD

**Issue by davidbogdanprivate** [cubieplayer/Cubian#6]
cubie@Cubian:~$ sudo nandinstall/install.sh 
This will completely destory your data on /dev/nand, Are you sure to continue? yes
spawn /home/cubie/nandinstall/sunxi-tools/nand-part /dev/nand linux 4000000 swap 8000000
check partition table copy 0: OK
check partition table copy 1: OK
check partition table copy 2: OK
check partition table copy 3: OK
partition  0: name =   bootloader, partition start =     2048, partition size =    32768
partition  1: name =        linux, partition start =    34816, partition size =  4000000
partition  2: name =         swap, partition start =  4034816, partition size =  8000000
3 partitions
check partition table copy 0: OK
check partition table copy 1: OK
check partition table copy 2: OK
check partition table copy 3: OK

ready to write new partition tables:
partition  0: name =   bootloader, partition start =     2048, partition size =    32768
partition  1: name =        linux, partition start =    34816, partition size =  4000000
partition  2: name =         swap, partition start =  4034816, partition size =  8000000
3 partitions

write new partition tables? (Y/N)
y

verifying new partition tables:
check partition table copy 0: OK
check partition table copy 1: OK
check partition table copy 2: OK
check partition table copy 3: OK
partition  0: name =   bootloader, partition start =     2048, partition size =    32768
partition  1: name =        linux, partition start =    34816, partition size =  4000000
partition  2: name =         swap, partition start =  4034816, partition size =  8000000
3 partitions
please wait for a moment
waiting 20 seconds
waiting 10 seconds
waiting 5 seconds
mke2fs 1.42.5 (29-Jul-2012)
Filesystem label=
OS type: Linux
Block size=4096 (log=2)
Fragment size=4096 (log=2)
Stride=0 blocks, Stripe width=0 blocks
125184 inodes, 500000 blocks
25000 blocks (5.00%) reserved for the super user
First data block=0
Maximum filesystem blocks=515899392
16 block groups
32768 blocks per group, 32768 fragments per group
7824 inodes per group
Superblock backups stored on blocks: 
    32768, 98304, 163840, 229376, 294912

Allocating group tables: done  
Writing inode tables: done  
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information: done 

mke2fs 1.42.5 (29-Jul-2012)
Filesystem label=
OS type: Linux
Block size=4096 (log=2)
Fragment size=4096 (log=2)
Stride=0 blocks, Stripe width=0 blocks
123392 inodes, 493024 blocks
24651 blocks (5.00%) reserved for the super user
First data block=0
Maximum filesystem blocks=507510784
16 block groups
32768 blocks per group, 32768 fragments per group
7712 inodes per group
Superblock backups stored on blocks: 
    32768, 98304, 163840, 229376, 294912

Allocating group tables: done  
Writing inode tables: done  
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information: done 

mount: you must specify the filesystem type
cubie@Cubian:~$ 

please help.

**Comment by cubieplayer** [comment]
Try to run the script again, see what happens.

**Comment by davidbogdanprivate** [comment]
hi, thx for reply.

i run the script again, and shows message again :/

**Comment by cubieplayer** [comment]
It's wired, I will try to reproduce the problem to figure out the problem.

PS. If you have experience on shell script, please try to execute the code line by line in `install.sh`, It's not hard to understand

You code stopped at line 138

**Comment by davidbogdanprivate** [comment]
hi, i think it's problem with the nand.

i checked the dmesg, shows:
[  531.240000] NTFS-fs error (device nanda): read_ntfs_boot_sector(): Primary boot sector is invalid.
[  531.270000] NTFS-fs error (device nanda): read_ntfs_boot_sector(): Mount option errors=recover not used. Aborting without trying to recover.
[  531.300000] NTFS-fs error (device nanda): ntfs_fill_super(): Not an NTFS volume.
[  531.390000] UDF-fs: warning (device nanda): udf_load_vrs: No anchor found
[  531.410000] UDF-fs: Rescanning with blocksize 2048
[  531.490000] UDF-fs: warning (device nanda): udf_load_vrs: No anchor found
[  531.520000] UDF-fs: warning (device nanda): udf_fill_super: No partition found (1)
[  662.980000] Dev nand: part 1, start 2048, size 32768
[  663.010000] Dev nand: part 2, start 34816, size 4000000
[  663.030000] Dev nand: part 3, start 4034816, size 3944192
[  663.050000]  nand: nanda nandb nandc
[  703.360000] EXT3-fs (nanda): error: can't find ext3 filesystem on dev nanda.
[  703.420000] EXT2-fs (nanda): error: can't find an ext2 filesystem on dev nanda.
[  703.450000] EXT4-fs (nanda): VFS: Can't find ext4 filesystem
[  703.480000] FAT-fs (nanda): bogus number of reserved sectors
[  703.490000] FAT-fs (nanda): Can't find a valid FAT filesystem
[  703.520000] FAT-fs (nanda): bogus number of reserved sectors
[  703.530000] FAT-fs (nanda): Can't find a valid FAT filesystem
[  703.620000] ISOFS: Unable to identify CD-ROM format.
[  703.650000] NTFS-fs error (device nanda): read_ntfs_boot_sector(): Primary boot sector is invalid.
[  703.680000] NTFS-fs error (device nanda): read_ntfs_boot_sector(): Mount option errors=recover not used. Aborting without trying to recover.
[  703.710000] NTFS-fs error (device nanda): ntfs_fill_super(): Not an NTFS volume.
[  703.800000] UDF-fs: warning (device nanda): udf_load_vrs: No anchor found
[  703.820000] UDF-fs: Rescanning with blocksize 2048
[  703.900000] UDF-fs: warning (device nanda): udf_load_vrs: No anchor found
[  703.920000] UDF-fs: warning (device nanda): udf_fill_super: No partition found (1)

**Comment by cubieplayer** [comment]
I can't reproduce the problem, I suggest to add a sleep between `mkFS` and `mountDevice`,then run it again.

```
mkFS
sleep 30
mountDevice
```

Maybe its too quickly to mount after mkfs.

The NAND uses special driver from AllWInner instead of the standard driver, so,you cant use fdsik or similar tools.

**Comment by cubieplayer** [comment]
Still can't reproduce the problem

**Comment by davidbogdanprivate** [comment]
Hi,
i found the solution.

i think the nand partition was bad.

from:
http://linux-sunxi.org/Cubieboard/Installing_on_NAND

"NAND boot partition and MBR image: http://dl.cubieforums.com/loz/boot_partition/bootloader/cubie_nand_uboot_partition_image.bin"

with dd i've fixed the problem:
"dd bs=4096 if=./cubie_nand_uboot_partition_image.bin of=/dev/nand"

thx for anyway!

best.
