### ISSUE TITLE
Monitor Problem

### ISSUE THREAD

**Issue by McBodik** [cubieplayer/Cubian#60]
Hi. I have installed Cubian, it's work great, except monitor. I haven't hdmi monitor, but I have convertor HDMI -> VGA. Android work fine, but Cubian give me only black screen (system work, I connect via ssh). How can I fix it?

**Comment by zerodamage** [comment]
Look at your boot configuration, make sure your display supports the default configuration (1280x600p60) as EDID info is probably not passed though your adaptor. It must be an active adaptor, so could you tell me which one?

**Comment by McBodik** [comment]
Thanks, you have already helped me:) 
I tried to use old monitor. It can't support so high resolution. Now all fine. 
About adaptor: I bought there http://dx.com/p/1080p-hdmi-male-to-vga-female-adapter-cable-w-mini-hdmi-male-to-hdmi-female-adapter-black-193337 .

**Comment by zerodamage** [comment]
You can change the resolution using uEnv.txt or boot.scr depending on kernel, it should have a line containing:
disp.screen0_output_mode=EDID:1280x600p60
You can change the last part to something smaller if you wish to use a different resolution

Please mark the issue as closed

**Comment by McBodik** [comment]
Thank you again!
