### ISSUE TITLE
wireless

### ISSUE THREAD

**Issue by McBodik** [cubieplayer/Cubian#63]
Hi again. I have problems with wifi. 
I configure /etc/network/interfaces  as wiki:

auto wlan0
allow-hotplug wlan0
iface wlan0 inet dhcp
wireless-essid mynetwork 

but when try sudo ifup wlan0 :

No DHCPOFFERS received.
No working leases in persistent database - sleeping.

I have mac filter on router, but add Cubie wifi mac  adress . 

In router I saw non expected : http://clip2net.com/s/5Bk8ng 
It's all eth0. Nothing about wifi. But most surprised - all macs are diferent- why/how?

Also I can't understand why Cubian is eth0 connected when there was 
# auto eth0

In wiki I saw: If you absolutely don't need the wired network,plase disable this feature by comment or delete auto eth0.
It is comment by default, why eth0 start working after system start?

ifconfig:

eth0      Link encap:Ethernet  HWaddr 4e:e5:30:cc:06:c5  
          inet addr:192.168.1.9  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::4ce5:30ff:fecc:6c5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2119 errors:0 dropped:0 overruns:0 frame:0
          TX packets:986 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:202605 (197.8 KiB)  TX bytes:98022 (95.7 KiB)
          Interrupt:55 Base address:0xb000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan0     Link encap:Ethernet  HWaddr 14:cf:92:13:47:45  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

P.S. wlan0 mac isn't change after reboot… 

P.S.S. sorry for my English…

**Comment by zerodamage** [comment]
The eth0 MAC is auto generated, they will stay for 23 hours more as shown.
Try using package wicd or NetworkManager instead of manual config (remove interfaces from etc/network/interfaces)
You also need wpa-supplicant or similar for WPA networks

**Comment by McBodik** [comment]
It's mean /etc/network/interfaces isn't the end inet config file? If the NetworkManager have another?

**Comment by McBodik** [comment]
Ok, but why there is nothing about NetworkManager in wiki?

And about eht0 - but MAC is a unique identifier… I always thought - its hardware address, or is this a specific Cubieboard implementation?

**Comment by cubieplayer** [comment]
There is **no** network manager. Please take a look at http://www.debian.org/doc/manuals/debian-reference/ch05.en.html to solve the problem. If you follows the wiki, It should work.

**Comment by McBodik** [comment]
Ok, if there is no another network utilities, why despite #auto eth0, eth0 connects at startup?

P.S. Sorry for so many questions, I just want to understand...

**Comment by zerodamage** [comment]
Sorry to have indicated NetworkManager was present @cubieplayer, @McBodik , it was from my LXDE install.
However i would still _personally_ recommend using one, if the network is not very simple.

To clairfy: i know **there is no manager**, but i _recommend_ using one

**Comment by cubieplayer** [comment]
@zerodamage cubian has no GUI, and no network manager. It uses network configuration file which is `/etc/network/interfaces` to config the network. If you installed LXDE, you should follow the LXDE's documentation to solve the problem.

**Comment by McBodik** [comment]
Ok, I try to do this manually. If I will fall, I'll install some gui. But I still don't understand how eth0 connect if auto connect is commented?

**Comment by zerodamage** [comment]
@McBodik I dont know why/how it does that sorry, have only been using GUI

**Comment by McBodik** [comment]
@zerodamage, @cubieplayer thanks for this, if  I find the answer, or have something new - I'll write:)

**Comment by McBodik** [comment]
Hi again. I fixed my problem, but have the second. 
My bad because I have router and repeater with one ssid to cover a larger area, and Cubian doesn't know what to use. Now Cubian remember ap to connect, but maybe you know how can I specify MAC address to connect for feature?

**Comment by mmplayer** [comment]
@McBodik http://linux-sunxi.org/EMAC and http://www.debian-administration.org/article/501/Working_with_MAC_addresses

**Comment by McBodik** [comment]
Because I have repeater, I need to tell Cubian where is DHCP thats why

auto wlan0
allow-hotplug wlan0
iface wlan0 inet dhcp
wireless-essid My_network_name
HWaddr DHCP_MAC_address

**Comment by cubieplayer** [comment]
This problem might be the same with http://www.debian-administration.org/article/501/Working_with_MAC_addresses

**Comment by cubieplayer** [comment]
duplicated with https://github.com/cubieplayer/Cubian/issues/47
