### ISSUE TITLE
nand install cannot find /dev/nand1

### ISSUE THREAD

**Issue by bgleonard** [cubieplayer/Cubian#64]
install.sh exits with an error in mkfs.vfat. /dev/nand1 does not exist. the command 'dd of=/dev/nand' using the .gz file as input seems to not create /dev/nand1 partition. I can see nand2, nanda, and nandb partitions.

**Comment by cubieplayer** [comment]
The new nand driver has changed the name in the new kernel. Use the universal nand installer instead http://cubian.org/2013/08/18/universal-and-separate-nandinstaller-is-released/

**Comment by bgleonard** [comment]
thanks. the link is on the 2nd page of the blog and i completely missed it.
