### ISSUE TITLE
Universal cubian-nandinstaller sets incorrect root in uEnv.txt

### ISSUE THREAD

**Issue by bgleonard** [cubieplayer/Cubian#67]
Like another user said in the blog post, the universal cubian-nandinstaller set the extra arg 'root' to /dev/nand3 which results in a kernel panic on boot from nand. Mounting /dev/nandc while booted from the SD and setting it 'root=/dev/nandc' in uEnv.txt resolves the issue.

**Comment by cubieplayer** [comment]
I've update the blog post as a reminder. http://cubian.org/2013/08/18/universal-and-separate-nandinstaller-is-released/
The nandinstall is success, so it's not a problem about nandinstall script itself.
