### ISSUE TITLE
Morse ....

### ISSUE THREAD

**Issue by micromys** [cubieplayer/Cubian#68]
Is it possible to remove the morse code operation to speed up the start-up process, especially when you a fixed ip-address this process is in fact not necessary. 

Thanks.

Vincent

**Comment by cubieplayer** [comment]
Sure, you can remove the asscioate lines in `/etc/ifplugd/ifplugd.action`, just comment cubian-networklight.

**Comment by micromys** [comment]
Thanks, I just commented out all of the following lines in ifplugd.action. The boot process is now back to 30 secs.

.
.
.
set -e

case "$2" in
up)
        #run-parts --arg="$1" --arg="$2" /etc/ifplugd/action.d/
       # give sometime for ifupdown to bring the if up/down
    #sleep 5
        #/etc/cubian-networklight $1 $2 &
        #/etc/cubian-ntpdate $1 $2 &
        ;;
down)
        #run-parts --reverse --arg="$1" --arg="$2" /etc/ifplugd/action.d/
    #sleep 5
        #/etc/cubian-networklight $1 $2 &
        ;;
*)
        echo "ifplugd.action: Incorrect action argument" >&2
        exit 1
        ;;
esac
