### ISSUE TITLE
XBMC A20

### ISSUE THREAD

**Issue by lubeless** [cubieplayer/Cubian#69]
Hey there,

Since the new kernel update, is XBMC possible on A20 Cubian? Ive got it for cb2 but i also have lxde... its very laggy almost unusable.  Is xbmc something on your mind Cubieplayer?

**Comment by cubieplayer** [comment]
I hope someone can make one, I don't have too much free time on the XBMC stuff. I suggest you use android instead. http://cubieboard.org/download/

**Comment by lubeless** [comment]
Yeah I tried android but I couldnt get my wifi adapter to work with it, same goes for my wireless keyboard.  I also prefer using a debian based OS for many reasons.  I REALLY like your work with Cubian, I was just thinking that it would make a good ''official'' cubieboard OS if it could also be used as a XBMC device or a tv box. 

Do you think I could run XBMC without LXDE?  Would it be faster then?

**Comment by cubieplayer** [comment]
I believe there's a lot work needs to be done to make XBMC smoothly on cb, and aslo LXDE. They will work but the unoptimized(configured) version will be slow i think. Because cubieboard is pretty new, something has to be modified to get better performance.

**Comment by lubeless** [comment]
Yes that makes a lot of sense.  Since video acceleration now seems to be possible with the kernel update, I think that Cubian got closer to making it possible. If thats ever in your plans to help make it happen, let us know :) Im sure there is a few people out there willing to give you a hand with this great project of yours.  Cant wait to see whats next. keep up the amazing work :)
