### ISSUE TITLE
CPU temperature

### ISSUE THREAD

**Issue by Deban** [cubieplayer/Cubian#71]
Hi,
is there to tool to read the cpu core temperature from Cubieboard 2?

**Comment by necenzurat** [comment]
same issue on Cubieboard 1, can someone confirm that there is a sensor on cubieboard?

**Comment by s-kostyuk** [comment]
Similar question.

I have installed lm-sensors from source but sensors-detect can't find any sensor on Cubieboard 1. So I waiting for another solution.

**Comment by michalliu** [comment]
There is no temperature sensor on the CPU.
