### ISSUE TITLE
Crash after try to login from SD

### ISSUE THREAD

**Issue by ebuildy** [cubieplayer/Cubian#72]
I just insert the SD card on my Cubieboard1, type login then enter and :

Got a big "Unable to handle kernel paging request ..." "cpufreq_stats"

I didnt manage to read properly the message sorry.

**Comment by zerodamage** [comment]
When I get paging request errors, something is usually corrupt on the SD card. If you have a linux pc you can try to scan it with e2fsck. Otherwise verify the problem by reformating and reflashing a freshly downloaded image. You can also try a different card if all else fails.

**Comment by ebuildy** [comment]
Thanks, I tried at least 4 times ;-) Still happening on my cubieboard1 just after run the nand install script (nandinstall/install.sh).

Then the SD card is "corrupted" and I have to reflash it. 

I am using image "Cubian-base-r4-arm-a10.img", is there a more recent file?

**Comment by zerodamage** [comment]
It is the most recent image yes.

**Comment by mlenger** [comment]
Same problem here. Cubian crashes randomly as if memory was corrupted: seg-faults, kernel-crashes, kernel oops...
I didn´t face similar problems with the preinstalled android image on nand flash.

**Comment by ebuildy** [comment]
I tried at least 10 times with 4 differents SD cards of 8Gb, class 10. Always crash. I got no problem with other distribution so I guess your upload may be corrupted ?

**Comment by cubieplayer** [comment]
Use new release, problem should not exists anymore
