### ISSUE TITLE
Kernel panics on A20 SMP

### ISSUE THREAD

**Issue by ghost** [cubieplayer/Cubian#74]
Hi, Whenever I try and build anything I get 

Unpacking manpages-dev (from .../manpages-dev_3.44-1_all.deb) ...
Processing triggers for man-db ...
Errors were encountered while processing:
 /var/cache/apt/archives/libicu48_4.8.1.1-12_armhf.deb
 /var/cache/apt/archives/libboost1.49-dev_1.49.0-3.2_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@Cubian:~/bitcoin/doc# 
Message from syslogd@Cubian at Aug 23 22:25:28 ...
 kernel:[  825.826002] Internal error: Oops: 5 [#1] PREEMPT SMP

Message from syslogd@Cubian at Aug 23 22:25:28 ...
 kernel:[  826.550040] Process hdmi proc (pid: 695, stack limit = 0xeeaae2f8)

Message from syslogd@Cubian at Aug 23 22:25:28 ...
 kernel:[  826.563018] Stack: (0xeeaaffb0 to 0xeeab0000)

Message from syslogd@Cubian at Aug 23 22:25:28 ...
 kernel:[  826.574136] ffa0:                                     ef035e88 c02f0fd4 00000000 c02f222c

Message from syslogd@Cubian at Aug 23 22:25:28 ...
 kernel:[  826.589199] ffc0: 00000000 c0067a94 c000ec2c 00000000 00000000 00000000 00000000 00000000

Message from syslogd@Cubian at Aug 23 22:25:28 ...
 kernel:[  826.604280] ffe0: eeaaffe0 eeaaffe0 ef035e88 c0067a10 c000ec2c c000ec2c aaaaaaaa aaaaaaaa

**Comment by s-kostyuk** [comment]
Similar problem for Cubieboard 1, extra cooling must help: https://github.com/cubieplayer/Cubian/issues/70#issuecomment-23278295.

**Comment by ghost** [comment]
I doubt it because I've switched to Cubieez and I'm running bitcoind, cgminer and building packages as well often running at close to 200% CPU and never had any kernel panics. I think there's a definate issue with Cubian as I couldn't build a single package when nothing else was running.
