### ISSUE TITLE
怎么释放被占用的内存了？？

### ISSUE THREAD

**Issue by bayuemu** [cubieplayer/Cubian#77]
我升级到3.4后，使用free 查看发现 只有800m的内存，怎么才能释放被占用的200m内存了?谢谢

![free](https://f.cloud.github.com/assets/1875909/1023453/6f8a51fc-0ded-11e3-8e1a-a60605f2e129.PNG)

**Comment by vfasky** [comment]
同问。 难道分到显卡了？
新内核很好，终于不会花屏了。 分辨率也正常了。 
感谢开发都们的劳动。

**Comment by mmplayer** [comment]
嗯，是分给显卡用了

**Comment by bayuemu** [comment]
那能不能 有什么操作，可以取消对显卡的内存分配，因为我就没有显示器，不需要显示，只是通过ssh凡是登录，操作系统，我想把分配给显卡的 内存回收到系统，给系统使用了，请问我应该怎么办？

**Comment by cubieplayer** [comment]
> setenv bootargs console=tty0 console=ttyS0,115200 sunxi_no_mali_mem_reserve sunxi_g2d_mem_reserve=0 sunxi_ve_mem_reserve=0 hdmi.audio=EDID:0 disp.screen0_output_mode=EDID:1280x800p60 root=/dev/mmcblk0p1 rootwait panic=10

Ref: https://github.com/cubieplayer/Cubian/issues/48

**Comment by michalliu** [comment]
ref: https://github.com/cubieplayer/Cubian/issues/142

**Comment by michalliu** [comment]
https://github.com/cubieplayer/Cubian/wiki/Why-the-total-memory-is-827MB-instead-of-1GB
