### ISSUE TITLE
Using one of LED's to monitor nand activites

### ISSUE THREAD

**Issue by s-kostyuk** [cubieplayer/Cubian#79]
Good day.

My feature request is similar to ambrosa's post (https://github.com/cubieplayer/Cubian/issues/66), but now with internal storage. I tried to execute "echo nand-disk > /sys/class/leds/blue:ph21:led2/trigger" from root and received "bash: echo: write error: Invalid argument". In file /sys/class/leds/blue:ph21:led2/trigger parameter "nand-disk" also missing but is mentioned on kernel.org (link: https://www.kernel.org/doc/Documentation/leds/leds-class.txt, phrase "Examples are the ide-disk, nand-disk and sharpsl-charge triggers."). Please, help to realize this function. Thank you.

**Comment by michalliu** [comment]
I tried the trigger, it's not working
