### ISSUE TITLE
cubian-update does not work

### ISSUE THREAD

**Issue by ghost** [cubieplayer/Cubian#80]
root@Cubian:/home/cubie# cubian-update
**\* Updating firmware
error: pathspec './' did not match any file(s) known to git.
root@Cubian:/home/cubie#

**Comment by zerodamage** [comment]
Had the same error, apt-get purge git && apt-get purge cubian-update and then reinstall resolved the issue.

**Comment by ghost** [comment]
thanks to @zerodamage, but then I had another error (internet fail) which I solved with this thread: https://github.com/cubieplayer/Cubian/issues/57

And now i have this following error:
-vmalloc.ko'
cp: writing `/lib/modules/3.4.43.sun7i+/kernel/drivers/media/video/videobuf2-vmalloc.ko': No space left on device
cp: failed to extend`/lib/modules/3.4.43.sun7i+/kernel/drivers/media/video/videobuf2-vmalloc.ko': No space left on device
`/root/.cubian-update/modules/3.4.43.sun7i+/kernel/drivers/media/video/videobuf2-memops.ko' ->`/lib/modules/3.4.43.sun7i+/kernel/drivers/media/video/videobuf2-memops.ko'
cp: writing `/lib/modules/3.4.43.sun7i+/kernel/drivers/media/video/videobuf2-memops.ko': No space left on device
cp: failed to extend`/lib/modules/3.4.43.sun7i+/kernel/drivers/media/video/videobuf2-memops.ko': No space left on device
`/root/.cubian-update/modules/3.4.43.sun7i+/kernel/drivers/media/video/ov6650.ko' ->`/lib/modules/3.4.43.sun7i+/kernel/drivers/media/video/ov6650.ko'
cp: writing `/lib/modules/3.4.43.sun7i+/kernel/drivers/media/video/ov6650.ko': No space left on device
cp: failed to extend`/lib/modules/3.4.43.sun7i+/kernel/drivers/media/video/ov6650.ko': No space left on device
cp: cannot create directory `/lib/modules/3.4.43.sun7i+/kernel/drivers/media/video/cx231xx': No space left on device
`/root/.cubian-update/modules/3.4.43.sun7i+/kernel/drivers/media/video/tveeprom.ko' -
[...]

My micro sd card have 8gb space

**Comment by ghost** [comment]
im trying to run the nandinstall script and the same error occurred (nothing enough space)

**Comment by phikman** [comment]
I can across a similar problem. Check your root partition is actually using all of your SD card. Type: ~df and check the root partition size. I found mine was only 900 MB of a 8 gig drive. Using cfdisk and resize2fs I expanded it to the whole SD card. Be wary though, you can destroy you data, so make an image of your SD card first using win32diskimager.

See: http://serverfault.com/a/509472

**Comment by cubieplayer** [comment]
@Cyborlex http://cubian.org/2013/08/12/enlarge-cubian-rootfs-partition

**Comment by cubieplayer** [comment]
This bug may be fixed by this commit https://github.com/mmplayer/cubian-packages/commit/14d688937b7353b7dbef247c1a4818af591b373b

**Comment by cubieplayer** [comment]
Please update your `cubian-update` to 1.0_8 which is the latest version

**Comment by cubieplayer** [comment]
Fixed on cubian-update(1.1.1)
