### ISSUE TITLE
Cubian support for TUN and multitables routing

### ISSUE THREAD

**Issue by gklipel** [cubieplayer/Cubian#81]
Hi all!

I've got success to run OpenVPN and iproute2 advanced routing tables features with Cubian. I think at this time everybody knows that these features was lacking of support on the original Cubian Kernel.

I just want to know how can I send the file to analysis to make this modifications on default Cubian kernel! How can I do it?

Thanks in advance!

**Comment by cubieplayer** [comment]
Try `cubian-update`,`iptable` is compiled now.

**Comment by gklipel** [comment]
OK I guess it is, but multitable or advanced routing is not, I've done this yet with no success.
My need was to put up a multilink with link detection. Had done the cubian-update yesterday, was not working.

**Comment by FedericoCeratto** [comment]
TUN/TAP support is also required by miredo (an IPv6 tunnelling daemon). Thanks!

**Comment by gklipel** [comment]
OK, I guess that I'll have to post it in here...

First of all, this will generate 160 megabytes in modules and an uImage about 5.7 megabytes. Side by side with the original /lib/modules is a huge amount of modules. Now Cubian will have DLM, GFS2, TUN/TAP support and many other features, including huge support for wireless sticks and USB RJ45 adapters. Not far at all will have support for IPROUTE2 MULTITABLE ROUTING, this and TUN/TAP were the reasons for me to get this work done.

By the way, I could not get SATA working properly with sw_ahci module built in, so I moved out from Kernel once more and now SATA is working again. The problem was that the HD was not detected with built in module, external module works well!

So, just copy/paste the content to .config and happy kernel hacking!

http://pastebin.com/6E1bkJnQ

**Comment by gklipel** [comment]
It would be interesting to remove USB_GADGET from it... This is known to be broken, sorry...

**Comment by cubieplayer** [comment]
Hi, These modules are compiled now, you can try `cubian-update` to get it, Please re-open the issue if it's not working.

**Comment by FedericoCeratto** [comment]
TUN/TAP support is still missing, see #22

**Comment by FedericoCeratto** [comment]
Both #81 and #22 have been closed but the problem is still outstanding.

**Comment by cubieplayer** [comment]
@FedericoCeratto have you tried cubian-update?
