### ISSUE TITLE
Kernel support for encrypted block devices

### ISSUE THREAD

**Issue by alexmbird** [cubieplayer/Cubian#82]
Could support be added to the next kernel for encrypted block devices?

CONFIG_BLK_DEV_CRYPTOLOOP=y
CONFIG_CRYPTO_SHA256=m
CONFIG_CRYPTO_SHA512=m
CONFIG_CRYPTO_AES=y

Then we should be able to mount / off encrypted partitions.

**Comment by cubieplayer** [comment]
Added. https://github.com/mmplayer/sunxi-kernel-config/commit/58fc9e8e8613a661d613040a8a4060b639a812ef

**Comment by cubieplayer** [comment]
Fixed on [r5](http://cubian.org/2013/09/06/cubian-r5-for-a10-and-r2-for-a20-released)

**Comment by innir** [comment]
Not really useful now as you didn't set

CONFIG_MD=y
CONFIG_BLK_DEV_DM=m
CONFIG_DM_CRYPT=m

Adding

CONFIG_CRYPTO_XTS=m

would be really nice too.

Thanks for your work!

**Comment by cubieplayer** [comment]
Hi, These modules are compiled now, you can try `cubian-update` to get it, Please re-open the issue if it's not working.
