### ISSUE TITLE
jdk-7u21-linux-arm-sfp.tar.gz 安装问题，

### ISSUE THREAD

**Issue by bayuemu** [cubieplayer/Cubian#84]
我在安装 oracle 的jdk-7u21-linux-arm-sfp.tar.gz 时 输入 java 提示  bash: ./java no such file or direction  但是 使用 jdk8时没有问题，请问 jdk7 如何解决，应为jdk8 还不稳定

**Comment by cubieplayer** [comment]
看起来是软件包的问题，到邮件列表里问问
