### ISSUE TITLE
cubian-update in ssd

### ISSUE THREAD

**Issue by railton** [cubieplayer/Cubian#86]
My cubieboard2 running in SSD 64G

Boot via nand

root@Cubian:/boot# cat /boot/uEnv.txt
console=tty0
extraargs=console=ttyS0,115200 hdmi.audio=EDID:0 disp.screen0_output_mode=EDID:1280x800p60 root=/dev/sda1 rootwait panic=10

/etc/fstab
root@Cubian:/boot# cat /etc/fstab
# <file system>  <mount point>   <type>  <options>   <dump>  <pass>

/dev/sda1   /       ext4    defaults    0   1
/dev/sda2       none        swap    sw          0       0
tmpfs   /tmp    tmpfs   defaults    0   0
tmpfs   /var/tmp    tmpfs   defaults    0   0

root@Cubian:/boot# cubian-update -v
**\* Performing self-update
Hit http://security.debian.org wheezy/updates Release.gpg
Hit http://security.debian.org wheezy/updates Release
Hit http://security.debian.org wheezy/updates/main armhf Packages
Hit http://packages.cubian.org wheezy Release.gpg
Hit http://security.debian.org wheezy/updates/contrib armhf Packages
Hit http://security.debian.org wheezy/updates/non-free armhf Packages
Hit http://security.debian.org wheezy/updates/contrib Translation-en
Hit http://packages.cubian.org wheezy Release
Hit http://security.debian.org wheezy/updates/main Translation-en
Hit http://security.debian.org wheezy/updates/non-free Translation-en
Hit http://http.debian.net wheezy Release.gpg
Hit http://packages.cubian.org wheezy/main armhf Packages
Hit http://download.opensuse.org  Release.gpg
Hit http://http.debian.net wheezy Release
Hit http://http.debian.net wheezy/main armhf Packages
Hit http://download.opensuse.org  Release
Hit http://http.debian.net wheezy/contrib armhf Packages
Hit http://http.debian.net wheezy/non-free armhf Packages
Hit http://http.debian.net wheezy/contrib Translation-en
Hit http://http.debian.net wheezy/main Translation-en
Ign http://packages.cubian.org wheezy/main Translation-en_US
Hit http://http.debian.net wheezy/non-free Translation-en
Ign http://packages.cubian.org wheezy/main Translation-en
Hit http://download.opensuse.org  Packages
Ign http://download.opensuse.org  Translation-en_US
Ign http://download.opensuse.org  Translation-en
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
cubian-update is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
**\* Cubian updater v1.0.9 http://cubian.org
Update From: https://github.com/cubieplayer/cubian-update.git
Root Path: /
Update Kernel: yes
Update Modules: yes
Branch: a20
error: can't update, failed to detect system type

**Comment by cubieplayer** [comment]
Thanks for reporting this problem.I'll improve the updater to supported the **mixed** system type.

**Comment by Frankenshtine** [comment]
# cubian-update

**\* Performing self-update
**\* Cubian updater v1.2.1 http://cubian.org
error: can't update, failed to detect system type

Problem is here:
---8<---
determineSysInstallType(){
        set +e
        cat $FSTAB | awk '{if($2=="/") {print $1}}' | grep -q $MMC_DEVICE && \
                SYS_INSTALL_TYPE="$SYS_INSTALL_TYPE_MMC"
        if [[ -z $SYS_INSTALL_TYPE ]];then
                cat $FSTAB | awk '{if($2=="/") {print $1}}' | grep -q $NAND_DEVICE && \
                SYS_INSTALL_TYPE="$SYS_INSTALL_TYPE_NAND"
        fi
        set -e
}
--->8---
but, in /etc/fstab
/dev/sda2       /               auto    noatime                 0       0
so, there is no hdd (ssd) recognition.

**Comment by michalliu** [comment]
Yes, This is a known issue

**Comment by Daniel-Brosnan** [comment]
cubian-update is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
**\* Cubian updater v1.2.9 http://cubian.org
Update From: https://github.com/cubieplayer/cubian-updates.git
Proxy:
Root Path: /
Update Kernel: yes
Update Modules: yes
Update Rootfs: yes
Update Bootloader: no
Update Boot configuration: no
Update Board configuration: no
Branch: a10
error: can't update, failed to detect system type

Have the error been resolved?

The rootfs is in an USB. The output of uname -a is:
Linux Cubian 3.4.67+ #18 PREEMPT Wed Nov 6 08:26:36 CST 2013 armv7l GNU/Linux

Thank you in advance!
Regards.
Dani.

**Comment by s-kostyuk** [comment]
Similar: https://github.com/cubieplayer/Cubian/issues/233

**Comment by Daniel-Brosnan** [comment]
Thank you VeryStrangeMan!

**Comment by s-kostyuk** [comment]
@Daniel-Brosnan It's my pleasure :)

**Comment by cubieplayer** [comment]
The latest version (1.3.7) should work
