### ISSUE TITLE
cubian-update

### ISSUE THREAD

**Issue by micromys** [cubieplayer/Cubian#87]
After running apt-get update and apt-get upgrade (today 9/2/13) cubian-update was updated. (A10 board)

Running cubian-update (after dd backup!!!) gives a warning "bootloader not loaded" and the system could not be rebooted, Got following info on console. What is (the/my) problem?

Loaded environment from /uEnv.txt
48092 bytes read in 12 ms (3.8 MiB/s)
/*******************************************_/
1004d  10  30147  8b  40022c  170  f0001  26
150395  258  80000  286  b0049  2c9  80003  1b8
102e6  388  b0004  1e7  100c8  1c6  10380  6a8
20016  38a  10159  71d  10143  149  10011  792
ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff
ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  724  7c7
2e1  7f1  357  7ae  617  345  2fa  2fb
2fc  65e  68a  f9  6b4  207  c7  334
251  272  445  3b0  611  2eb  425  512
6ef  5b9  3e2  391  6a1  6f9  6bc  6bb
3ba  4af  4e1  306  5fa  307  35b  4d9
363  5d6  2b2  310  311  313  314  315
316  514  5a2  319  31a  31b  3b3  5ad
63a  719  3d2  608  7f7  4b4  742  5eb
4ee  534  351  47a  49a  5d3  56c  6db
6a2  24b  5bb  27c  4be  297  618  117
233  36c  712  7c4  25c  2f9  46b  308
189  78f  7a7  22f  787  7b7  3bc  c1
3a9  6eb  7dc  5ce  2d0  387  28b  6a7
166  76d  6d8  759  1bd  2a5  273  2b1
4f8  1de  423  378  12b  243  103  1e8
694  368  65c  227  2da  6e2  2e5  7e2
40d  1f2  14d  27f  151  29b  36e  348
327  26d  1f8  4fc  b1  6c5  167  148
33e  124  7bf  2df  1c3  691  72a  2e6
342  a9  5c9  592  106  2b9  1b0  9d
169  7b1  29c  374  75b  244  360  465
35d  282  795  118  353  137  3a3  67d
d9  2de  614  6d4  111  79c  698  281
469  2cd  7d3  ad  d8  780  706  12e
6e5  709  f6  2d6  69f  71b  3c6  1e0
70f  6dd  3c1  37f  414  df  66d  25e
2f4  2ed  656  5e0  751  301  6ab  13e
3b7  392  2f5  3bd  412  32c  3ad  42c
312  68f  437  6cb  3a8  64f  38f  367
30e  3c4  2f1  60c  3cb  42a  66c  6ac
2f3  6aa  3a0  5c1  372  366  39e  3b8
396  78d  355  67c  4f  1d6  1ea  43c
3d8  10c  7c0  a4  79b  553  5b6  73a
6f1  3fc  3f3  3eb  744  41f  456  3d4
3d5  71c  6b0  436  3f7  3e4  3e5  3e6
37a  69a  6ce  3de  3ed  767  789  127
45b  49b  3f1  74c  3ef  3dc  2f7  3e1
305  4d8  4d2  460  76b  3f5  3a5  3a6
154  400  3e3  1c9  475  484  39b  2f8
7c3  217  332  36b  3fd  393  379  6dc
416  3d7  3f6  409  377  455  44c  4d0
40b  3f4  433  402  7e9  3d6  481  4e3
4c8  727  42d  30c  426  442  771  47d
488  421  464  466  449  47c  3d1  447
30f  44d  420  3b9  69c  3e0  43f  bc
413  3ac  49d  40e  485  398  443  427
594  48b  30b  44b  459  45f  45e  4b8
446  5d0  461  376  450  477  453  432
471  53a  70d  46a  4dc  4e6  50a  3fb
516  43e  49e  46d  479  622  70c  304
2ee  4a4  4a8  480  781  39f  303  3fe
493  440  47e  4b1  45a  48a  4c0  403
50b  48d  48e  467  491  404  4fb  5b7
30a  474  497  4c4  496  19e  3ec  46e
454  4ca  3ff  4a0  4ce  478  4e4  457
4a1  4a6  2a7  13b  47f  4aa  511  4d1
4ad  494  486  4b0  4ae  4f2  473  4f1
468  483  489  6a6  46c  4ba  42e  7b8
1004d  10  30147  8b  40022c  170  f0001  26
150395  258  80000  286  b0049  2c9  80003  1b8
102e6  388  b0004  1e7  100c8  1c6  10380  6a8
20016  38a  10159  71d  10143  149  10011  792
ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff
ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  4eb  4e7
38e  4d5  4ef  318  4e5  506  472  5aa
2ef  3fa  522  370  4f9  525  48f  4da
382  4c5  555  1ba  3b4  4fa  53e  501
502  4ff  4fe  505  492  4f3  5b3  ac
50d  50e  d7  32a  515  341  495  799
73  4f4  517  51b  510  51a  52b  4bf
51d  51e  541  503  521  4c9  4f5  524
560  507  6a0  55d  4a7  52a  552  470
52d  52e  4ed  500  531  55b  6bf  241
452  730  537  4cb  54e  530  50f  3cd
5ec  519  5d2  5c7  5cb  174  513  343
542  4a5  546  544  545  549  547  548
54c  54d  56b  54b  550  551  56e  520
554  571  52c  557  575  523  55a  3e7
31f  584  533  55f  587  529  562  58a
526  565  598  504  53d  569  56a  59c
568  498  59f  54f  7cf  278  4c1  582
93  535  556  577  578  34b  559  57b
57c  44e  55c  57f  580  57d  57e  583
604  573  586  581  55e  589  77d  561
58c  791  564  58f  590  58d  58e  593
5d4  558  596  597  5c5  45c  59a  59b
5c8  536  59e  5cc  5bf  31d  509  616
508  344  572  5a7  7ce  5a8  576  5ab
5af  5a9  5ae  56d  532  317  329  7cb
642  570  4dd  5ac  32f  5b1  5db  30d
664  5fb  94  45d  612  661  77b  3e8
346  633  4d  601  566  543  610  5dc
58b  31c  659  411  5b0  2e3  84  48
6a  76a  5e2  5a6  33d  302  31e  350
5f4  5da  2b7  4ea  50c  588  463  98
6ca  631  735  5f8  1fe  5c3  5d1  321
5e8  5ed  5ee  5ef  5f0  5f1  5f2  5f3
7b6  63b  630  5b2  69e  619  223  47b
5a4  5e5  66b  5c4  60e  648  5c0  540
49  43b  655  624  62e  668  5be  5a0
60b  38b  5b5  5c2  43d  632  645  70
60a  73e  63d  651  61a  5ff  785  53f
6fe  5a  3b2  2ce  59  5f6  644  66e
7c  5a3  6de  5cd  5fe  634  635  657
53c  61f  458  623  7d  405  5cf  5e3
386  462  62f  638  621  5e7  5e1  5df
627  64c  56  6c1  8c  625  60f  615
5b8  6fb  3da  3a1  600  61c  666  7eb
4f6  5bc  482  2a8  3cf  5d7  60d  629
654  82  606  52  64d  44a  672  51f
574  96  4d4  de  3ce  647  201  7a
62b  5fc  70a  364  fe  762  3f2  ea
8d  90  91  95  9a  9b  9e  a0
a5  a6  ab  b2  b3  b4  b5  b6
ba  bb  bf  c2  cc  ce  d0  d5
d6  dc  ec  f0  f3  f4  128  156
165  172  1c2  1f7  249  270  287  2bb
2d1  2d9  2f0  33b  362  3aa  407  417
490  595  66a  693  6a9  6cc  6e4  6ff
715  747  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff
ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff
ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  ffffffff  11732b
 *_ ext4fs_devread read error - block
*\* Unable to read file /boot/uImage **
*\* Unrecognized filesystem type **

**Comment by michalliu** [comment]
It shouldn't happen at current release. If it happens again please reopen the issue.
