### ISSUE TITLE
cubian-update bug

### ISSUE THREAD

**Issue by Deopmen** [cubieplayer/Cubian#88]
/etc/apt/sources.list 
# deb http://http.debian.net/debian/ wheezy main contrib non-free
# deb http://security.debian.org/ wheezy/updates main contrib non-free

deb http://packages.cubian.org/ wheezy main

root@Cubian[/home/cubie]>cubian-update -v  
**\* Performing self-update
Hit http://packages.cubian.org wheezy Release.gpg
Hit http://packages.cubian.org wheezy Release
Hit http://packages.cubian.org wheezy/main armhf Packages
W: Failed to fetch http://packages.cubian.org/dists/wheezy/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by Deopmen** [comment]
dpkg -l | grep cubian  
ii  cubian-update                   1.0-9                        all          update cubian
cubian-update -v  
**\* Performing self-update
Hit http://security.debian.org wheezy/updates Release.gpg
Hit http://packages.cubian.org wheezy Release.gpg
Hit http://security.debian.org wheezy/updates Release
Hit http://packages.cubian.org wheezy Release  
Hit http://http.debian.net wheezy Release.gpg  
Hit http://security.debian.org wheezy/updates/main armhf Packages
Hit http://packages.cubian.org wheezy/main armhf Packages
Hit http://security.debian.org wheezy/updates/contrib armhf Packages
Hit http://security.debian.org wheezy/updates/non-free armhf Packages
Hit http://security.debian.org wheezy/updates/main i386 Packages
Hit http://security.debian.org wheezy/updates/contrib i386 Packages
Hit http://http.debian.net wheezy Release  
Hit http://security.debian.org wheezy/updates/non-free i386 Packages
Hit http://security.debian.org wheezy/updates/contrib Translation-en
Hit http://security.debian.org wheezy/updates/main Translation-en
Hit http://http.debian.net wheezy/main armhf Packages
Hit http://security.debian.org wheezy/updates/non-free Translation-en
Hit http://http.debian.net wheezy/contrib armhf Packages
Hit http://http.debian.net wheezy/non-free armhf Packages
Hit http://http.debian.net wheezy/main i386 Packages
Hit http://http.debian.net wheezy/contrib i386 Packages
Hit http://http.debian.net wheezy/non-free i386 Packages
Hit http://http.debian.net wheezy/contrib Translation-en
Hit http://http.debian.net wheezy/main Translation-en
Hit http://http.debian.net wheezy/non-free Translation-en
W: Failed to fetch http://packages.cubian.org/dists/wheezy/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by zerodamage** [comment]
Why are you trying to download i386 packages to an armhf system?

**Comment by Deopmen** [comment]
I do not know... how to switch on armhf system packages?

**Comment by Deopmen** [comment]
iam understood
dpkg --remove-architecture i386
dpkg --add-architecture armhf

**Comment by zerodamage** [comment]
Good :+1:
