### ISSUE TITLE
Question: SD Card can be used after install in NAND as bootable drive?

### ISSUE THREAD

**Issue by eirisdg** [cubieplayer/Cubian#89]
Hi.

I've installed Cubian to Nand, and formatted SD Card after it to use as bootable drive, but when I insert in the board and reboot, cubian doesn't start.

The SD is formated to NTFS, but i've tried too with FAT32 and nothing.

**Comment by zerodamage** [comment]
What exactly do you mean by bootable drive?
- Cubian should run completely from SD card?
- Cubian rootfs should be on SD card, kernel on NAND?
- Cubian should be able to access files on SD card?

**Comment by eirisdg** [comment]
Sorry, cubian should be able to acces files on SD Card.

2013/9/3 zerodamage notifications@github.com

**Comment by zerodamage** [comment]
To be sure to remove the bootloader completely from the SD card, you can dd /dev/null to the SD card to make sure its completely wiped of all partitions. Then format it to whichever you like.

**Comment by eirisdg** [comment]
Cannot enter in linux with the sd card pluged.

**Comment by cubieplayer** [comment]
@tupacsoul 
Wipe out the bootloader on SD-card should work

> dd if=/dev/zero of=/dev/SD_CARD bs=1M count=1

**Comment by eirisdg** [comment]
I cannot mount the sd, system doesnt starts :(

**Comment by cubieplayer** [comment]
Use `mkfs.ext4 /dev/SD_CARD` to format the card

**Comment by zerodamage** [comment]
Take the card out, start, then plugin and format

Sent from my Windows Phone

**Comment by eirisdg** [comment]
Ok, i will try it. Thanks!
