### ISSUE TITLE
cubieplayer! please add drv/net/wireless/Realtek8187 drv on next update

### ISSUE THREAD

**Issue by Deopmen** [cubieplayer/Cubian#90]
your kernel not compile 

root@debian:/home/user/linux-sunxi-dev-sunxi-3.4-a20# make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- uImage
scripts/kconfig/conf --silentoldconfig Kconfig
  CHK     include/linux/version.h
  CHK     include/generated/utsrelease.h
make[1]: `include/generated/mach-types.h' is up to date.
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  GZIP    kernel/config_data.gz
  CHK     kernel/config_data.h
  UPD     kernel/config_data.h
  CC      kernel/configs.o
  LD      kernel/built-in.o
  CC      drivers/video/sunxi/disp/OSAL_Clock.o
In file included from drivers/video/sunxi/disp/OSAL_Clock.c:21:0:
drivers/video/sunxi/disp/OSAL_Clock.h:223:22: error: redefinition of typedef вЂ__hdleвЂ™
drivers/video/sunxi/disp/bsp_display.h:53:22: note: previous declaration of вЂ__hdleвЂ™ was here
make[3]: **\* [drivers/video/sunxi/disp/OSAL_Clock.o] Error 1
make[2]: **\* [drivers/video/sunxi/disp] Error 2
make[1]: **\* [drivers/video] Error 2
make: **\* [drivers] Error 2

**Comment by Deopmen** [comment]
7z x linux-sunxi-sunxi-3.4.zip
cd linux-sunxi-sunxi-3.4/
wget https://raw.github.com/mmplayer/sunxi-kernel-config/master/config-cubian-base-sun7i-3.4
mv config-cubian-base-sun7i-3.4 .config
make ARCH=arm menuconfig
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- uImage modules

....
  LD      drivers/hid/hid.o
  LD      drivers/hid/built-in.o
  LD      drivers/hsi/clients/built-in.o
  LD      drivers/hsi/built-in.o
  CC      drivers/hwmon/hwmon.o
  CC      drivers/hwmon/mma7660.o
drivers/hwmon/mma7660.c:39:25: fatal error: mach/system.h: No such file or directory
compilation terminated.
make[2]: **\* [drivers/hwmon/mma7660.o] Error 1
make[1]: **\* [drivers/hwmon] Error 2
make: **\* [drivers] Error 2

**Comment by Deopmen** [comment]
wget https://raw.github.com/mmplayer/sunxi-kernel-config/master/config-cubian-base-sun7i-3.4
mv  config-cubian-base-sun7i-3.4 .config
make ARCH=arm menuconfig
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- uImage modules
...
  LD      drivers/video/omap2/built-in.o
  CC      drivers/video/sunxi/disp/dev_disp.o
  CC      drivers/video/sunxi/disp/dev_fb.o
  CC      drivers/video/sunxi/disp/OSAL_Clock.o
In file included from drivers/video/sunxi/disp/OSAL_Clock.c:21:0:
drivers/video/sunxi/disp/OSAL_Clock.h:223:22: error: redefinition of typedef вЂ__hdleвЂ™
drivers/video/sunxi/disp/bsp_display.h:53:22: note: previous declaration of вЂ__hdleвЂ™ was here
make[3]: **\* [drivers/video/sunxi/disp/OSAL_Clock.o] Error 1
make[2]: **\* [drivers/video/sunxi/disp] Error 2
make[1]: **\* [drivers/video] Error 2
make: **\* [drivers] Error 2

**Comment by Deopmen** [comment]
7z x linux-sunxi-dev-sunxi-3.4-a20.zip 
   cd linux-sunxi-dev-sunxi-3.4-a20
   wget https://raw.github.com/mmplayer/sunxi-kernel-config/master/config-cubian-base-sun7i-3.4
   mv config-cubian-base-sun7i-3.4 .config
   make ARCH=arm menuconfig
   make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- uImage modules

...
  CC      arch/arm/mach-sun7i/dma/dma_interface.o
  CC      arch/arm/mach-sun7i/dma/dma_csp.o
  CC      arch/arm/mach-sun7i/dma/dma_core.o
  LD      arch/arm/mach-sun7i/dma/built-in.o
  CC      arch/arm/mach-sun7i/pm/pm.o
In file included from arch/arm/mach-sun7i/pm/mem_divlibc.h:4:0,
                 from arch/arm/mach-sun7i/pm/pm.h:15,
                 from arch/arm/mach-sun7i/pm/pm.c:37:
arch/arm/mach-sun7i/pm/pm_types.h:14:29: error: redefinition of typedef вЂ__s8вЂ™
include/asm-generic/int-ll64.h:19:25: note: previous declaration of вЂ__s8вЂ™ was here
arch/arm/mach-sun7i/pm/pm_types.h:15:29: error: redefinition of typedef вЂ__u8вЂ™
include/asm-generic/int-ll64.h:20:23: note: previous declaration of вЂ__u8вЂ™ was here
arch/arm/mach-sun7i/pm/pm_types.h:16:29: error: redefinition of typedef вЂ__s16вЂ™
include/asm-generic/int-ll64.h:22:26: note: previous declaration of вЂ__s16вЂ™ was here
arch/arm/mach-sun7i/pm/pm_types.h:17:29: error: redefinition of typedef вЂ__u16вЂ™
include/asm-generic/int-ll64.h:23:24: note: previous declaration of вЂ__u16вЂ™ was here
arch/arm/mach-sun7i/pm/pm_types.h:18:29: error: redefinition of typedef вЂ__s32вЂ™
include/asm-generic/int-ll64.h:25:24: note: previous declaration of вЂ__s32вЂ™ was here
arch/arm/mach-sun7i/pm/pm_types.h:19:29: error: redefinition of typedef вЂ__u32вЂ™
include/asm-generic/int-ll64.h:26:22: note: previous declaration of вЂ__u32вЂ™ was here
arch/arm/mach-sun7i/pm/pm_types.h:20:29: error: redefinition of typedef вЂ__s64вЂ™
include/asm-generic/int-ll64.h:29:44: note: previous declaration of вЂ__s64вЂ™ was here
arch/arm/mach-sun7i/pm/pm_types.h:21:29: error: redefinition of typedef вЂ__u64вЂ™
include/asm-generic/int-ll64.h:30:42: note: previous declaration of вЂ__u64вЂ™ was here
arch/arm/mach-sun7i/pm/pm_types.h:23:23: error: redefinition of typedef вЂsize_tвЂ™
include/linux/types.h:63:26: note: previous declaration of вЂsize_tвЂ™ was here
make[2]: **\* [arch/arm/mach-sun7i/pm/pm.o] Error 1
make[1]: **\* [arch/arm/mach-sun7i/pm] Error 2
make: **\* [arch/arm/mach-sun7i] Error 2

**Comment by Deopmen** [comment]
7z x linux-sunxi-sunxi-3.4.zip 
cd linux-sunxi-sunxi-3.4
wget https://raw.github.com/mmplayer/sunxi-kernel-config/master/config-cubian-base-sun7i-3.4 
mv config-cubian-base-sun7i-3.4 .config
make ARCH=arm menuconfig
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- uImage modules

...
  CC      drivers/ata/libata-scsi.o
  CC      drivers/ata/libata-eh.o
  CC      drivers/ata/libata-transport.o
  CC      drivers/ata/libata-sff.o
  CC      drivers/ata/libata-pmp.o
  LD      drivers/ata/libata.o
  CC      drivers/ata/ahci_platform.o
  CC      drivers/ata/libahci.o
  CC      drivers/ata/sw_ahci_platform.o
drivers/ata/sw_ahci_platform.c:42:29: fatal error: plat/sys_config.h: No such file or directory
compilation terminated.
make[2]: **\* [drivers/ata/sw_ahci_platform.o] Error 1
make[1]: **\* [drivers/ata] Error 2
make: **\* [drivers] Error 2

**Comment by cubieplayer** [comment]
Where is the driver source?

**Comment by Deopmen** [comment]
https://github.com/mmplayer/linux-sunxi/tree/sunxi-3.4/drivers/net/wireless/rtl818x/rtl8187

**Comment by cubieplayer** [comment]
Did you try this toolchain ? https://github.com/cubieplayer/Toolchain

**Comment by Deopmen** [comment]
Yes

**Comment by cubieplayer** [comment]
Ok, I will try to compile the driver

**Comment by cubieplayer** [comment]
Closed duplicated with https://github.com/cubieplayer/Cubian/issues/153

**Comment by cubieplayer** [comment]
It's different with #153

**Comment by cubieplayer** [comment]
Hi, These modules are compiled now, you can try `cubian-update` to get it, Please re-open the issue if it's not working.

**Comment by Deopmen** [comment]
root@Cubian:/home/cubie# cubian-update -v
**\* Performing self-update
Get:1 http://security.debian.org wheezy/updates Release.gpg [836 B]
Get:2 http://security.debian.org wheezy/updates Release [102 kB]
Get:3 http://http.debian.net wheezy Release.gpg [1,672 B]  
Get:4 http://http.debian.net wheezy Release [168 kB]  
Get:5 http://packages.cubian.org wheezy Release.gpg [316 B]
Get:6 http://packages.cubian.org wheezy Release [920 B]  
Get:7 http://security.debian.org wheezy/updates/main armhf Packages [110 kB]  
Get:8 http://packages.cubian.org wheezy/main armhf Packages [2,676 B]  
Get:9 http://packages.cubian.org wheezy/main Translation-en_US [2,866 B]  
Get:10 http://packages.cubian.org wheezy/main Translation-en [2,866 B]  
Get:11 http://security.debian.org wheezy/updates/contrib armhf Packages [14 B]  
Get:12 http://security.debian.org wheezy/updates/non-free armhf Packages [14 B]  
Get:13 http://security.debian.org wheezy/updates/contrib Translation-en [14 B]  
Get:14 http://security.debian.org wheezy/updates/main Translation-en [66.9 kB]  
Get:15 http://security.debian.org wheezy/updates/non-free Translation-en [14 B]  
Get:16 http://http.debian.net wheezy/main armhf Packages [5,693 kB]  
Get:17 http://http.debian.net wheezy/contrib armhf Packages [33.1 kB]  
Get:18 http://http.debian.net wheezy/non-free armhf Packages [55.8 kB]  
Get:19 http://http.debian.net wheezy/contrib Translation-en [34.8 kB]  
Get:20 http://http.debian.net wheezy/main Translation-en [3,851 kB]
Get:21 http://http.debian.net wheezy/non-free Translation-en [66.1 kB]  
Fetched 10.2 MB in 3min 9s (53.9 kB/s)  
Reading package lists... Done
Reading package lists... Done
Building dependency tree  
Reading state information... Done
cubian-update is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.
**\* Cubian updater v1.2.5 http://cubian.org
Update From: https://github.com/cubieplayer/cubian-updates.git
Root Path: /
Update Kernel: yes
Update Modules: yes
Update Rootfs: yes
Update Bootloader: no
Update Boot configuration: no
Update Board configuration: no
Branch: a20
SysInstallType: mmc
set firmware url to https://github.com/cubieplayer/cubian-updates.git
**\* Checking updates from server
Checking updates from server https://github.com/cubieplayer/cubian-updates.git
Remote revision: a20-3.4.61_6
Local revision: a20-3.4.61_6
**\* Your firmware is up to date
root@Cubian:/home/cubie# 

root@Cubian:/home/cubie# ls -laF /lib/modules/3.4.61+/kernel/drivers/net/wireless/
total 44
drwxr-xr-x 11 root root 4096 Oct 20 02:30 ./
drwxr-xr-x  8 root root 4096 Oct 20 02:30 ../
drwxr-xr-x  3 root root 4096 Oct 20 02:30 ath/
drwxr-xr-x  2 root root 4096 Oct 20 02:30 bcm4330/
drwxr-xr-x  2 root root 4096 Oct 20 02:30 rt2x00/
drwxr-xr-x  2 root root 4096 Oct 20 02:30 rtl8188eu/
drwxr-xr-x  2 root root 4096 Oct 20 02:30 rtl8189es/
drwxr-xr-x  2 root root 4096 Oct 20 02:30 rtl8192cu/
drwxr-xr-x  2 root root 4096 Oct 20 02:30 rtl8723as/
drwxr-xr-x  4 root root 4096 Oct 20 02:30 rtlwifi/
drwxr-xr-x  2 root root 4096 Oct 20 02:30 rtxx7x/
root@Cubian:/home/cubie#

**Comment by Deopmen** [comment]
none module rtl8187!

**Comment by cubieplayer** [comment]
Try run cubian-update, this driver should be included by now.If not please report and re-open the issue.

**Comment by Deopmen** [comment]
cubian-update -v
...
Branch: a20
SysInstallType: mmc
set firmware url to https://github.com/cubieplayer/cubian-updates.git
Apply proxy setting
**\* Checking updates from server
Checking updates from server https://github.com/cubieplayer/cubian-updates.git
Remote revision: a20-3.4.61_7
Local revision: a20-3.4.61_6
**\* Downloading updates (this may take a while)
clean up repository
HEAD is now at 9fc381c supports rtl8187
From https://github.com/cubieplayer/cubian-updates
- branch            a20        -> FETCH_HEAD
  Already up-to-date.
  **\* Updating firmware
  As requested using tag a20-3.4.61_7 from local repository
  clean up repository
  HEAD is now at 9fc381c supports rtl8187
  error: pathspec 'tags/a20-3.4.61_7' did not match any file(s) known to git.

root@Cubian:/home/cubie# ls -laF /lib/modules/3.4.61+/kernel/drivers/net/wireless/
total 44
drwxr-xr-x 11 root root 4096 Oct 20 02:30 ./
drwxr-xr-x  8 root root 4096 Oct 20 02:30 ../
drwxr-xr-x  3 root root 4096 Oct 20 02:30 ath/
drwxr-xr-x  2 root root 4096 Oct 20 02:30 bcm4330/
drwxr-xr-x  2 root root 4096 Oct 20 02:30 rt2x00/
drwxr-xr-x  2 root root 4096 Oct 20 02:30 rtl8188eu/
drwxr-xr-x  2 root root 4096 Oct 20 02:30 rtl8189es/
drwxr-xr-x  2 root root 4096 Oct 20 02:30 rtl8192cu/
drwxr-xr-x  2 root root 4096 Oct 20 02:30 rtl8723as/
drwxr-xr-x  4 root root 4096 Oct 20 02:30 rtlwifi/
drwxr-xr-x  2 root root 4096 Oct 20 02:30 rtxx7x/

none rtl8187 !

**Comment by cubieplayer** [comment]
There is an error when you do cubian-update, the driver is located here

>  pathspec 'tags/a20-3.4.61_7' did not match any file(s) known to git.

https://github.com/cubieplayer/cubian-updates/tree/a20-3.4.61_7/modules/3.4.61%2B/kernel/drivers/net/wireless/rtl818x/rtl8187

You can solve the problem run `cubian-update -c && cubian-update -v`
