### ISSUE TITLE
CDC-ACM suppport

### ISSUE THREAD

**Issue by BBELLIDO** [cubieplayer/Cubian#92]
Hello, cubian has CDC-ACM module installed? I have to compile kernel?

**Comment by cubieplayer** [comment]
Where is the driver source?

**Comment by BBELLIDO** [comment]
Hello, cdc-acm, you need to include in kernel compilation, Best regards!

**Comment by mc-b** [comment]
Hello,

the cdc-acm modul is needed for Arduino UNO (www.arduino.cc).

I found this sources http://lxr.linux.no/linux+v3.11.2/drivers/usb/class/.

greetings
marcel

**Comment by Lu6ith** [comment]
Hello :)
@cubieplayer please input these in config:

----- USB Device Class drivers

CONFIG_USB_ACM=m
CONFIG_USP_PRINTER=m
CONFIG_USB_WDM=m

This will compile cdc-acm(wdm) drivers as modules.
I'd like also connect cboard with arduino.

greetings

Wojciech

**Comment by BBELLIDO** [comment]
Hello, I need cdc-acm.ko for kernel 3.4.43 kernel, anybody has compiled it? I'm newbie and I 'dont know how i can do it

**Comment by BBELLIDO** [comment]
Hello again, someone could be so kind to compile for me cdc-acm module? I have had trying it for 5 days and I'm desperate.

Best regards

**Comment by BBELLIDO** [comment]
Another day still trying? how can i make my kernel support cdc-acm?  I have compiled the kernel but doesn'wor, any idea? seems to be invalid. I'm newbie

**Comment by mc-b** [comment]
Hello,

Try the latest version of Cubian - http://cubian.org/downloads/

within this version, the module exists.

greeting
Marcel

**Comment by BBELLIDO** [comment]
Hello mc-b,

in Cubian-base-r2-arm-a20.img.7z ? I have installed it and I can't find it, this is the version I was using. is in cubie 1 version? may I use cubie 1 module in cubie 2? could you post me the module? I need this module for cubie 2

Thanks a lot, I'm desperate

**Comment by mc-b** [comment]
try

<pre>
uname -a
Output: Linux Cubian 3.4.43+ #8 SMP PREEMPT Mon Sep 30 12:11:02 CST 2013 armv7l GNU/Linux
</pre>

Older version don't work.

then

<pre>
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install cubian-update
sudo cubian-update
</pre>

for me work's with Arduino UNO (www.arduino.cc).

greeting
Marcel

**Comment by BBELLIDO** [comment]
Hello Again,

it doesn't work form me, I have installed de latest version for download 

Hardware:Cubieboard2
FileName:Cubian-base-r2-arm-a20.img.7z
Size: 105.2MB

cubie@Cubian:~$ uname -a
Linux Cubian 3.4.43+ #11 SMP PREEMPT Thu Sep 5 00:04:37 CST 2013 armv7l GNU/Linux

I have done:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install cubian-update
sudo cubian-update

After all:

cubie@Cubian:~$ uname -a
Linux Cubian 3.4.61+ #2 SMP PREEMPT Wed Oct 9 06:49:50 CST 2013 armv7l GNU/Linux

But i still haven't support for cdc-acm module.  Could yo be si kind to send me cdc-acm.ko  to bbellido@gmail.com?

Best regards and thanks a lot

**Comment by mc-b** [comment]
Have tried to copy the modules into the cubian image, no success

My suggestion: use linaro linux. There, the module is available.

greeting
marcel

**Comment by BBELLIDO** [comment]
Thanks Marcel, I'm very gratefully,,

I want to use cubian, because cubian have cubian-nandinstaller and it works. I need to be able to flash in nand my project which is in SD whenever I want, it's a requisite of my professor. Linaro I think you have to flash linaro image with livesuite and after it you have to reinstall reinstall all the software and programs of my project. All my university project is done in cubian, and this is the only thing remains me.

Cubieplayer has kindly accepted my suggestion, I'm gonna wait a bit, I'm very tired, any suggestion is welcome. 

thanks for your support!!!

**Comment by cubieplayer** [comment]
Hi, It's supported by now. try with cubian-update
