### ISSUE TITLE
Upgrading A20 from r1 to r2

### ISSUE THREAD

**Issue by gahpee** [cubieplayer/Cubian#93]
Hi,

Forgive me if this has been covered elsewhere but if it has I have been unable to find it.

I initially installed the r1 image on my A20 and wish to upgrade it to r2. Running cubian-update  has successfully upgraded the kernel to 3.4.43+ and it now reports that all packages are up to date when run with the -v option. However, I have noticed that the the file, /etc/ifplugd/ifplugd.action is still the original that was installed from the r1 image and does not match the modified version now distributed in the r2 image.

I know I could simply copy this file from the r2 image but is that the correct way to do it?

**Comment by cubieplayer** [comment]
cubian-update doesn't support to update rootfs file currently.

**Comment by gahpee** [comment]
Ok thanks. I'll manually copy files as I see the need.
