### ISSUE TITLE
xf86-video-sunxifb

### ISSUE THREAD

**Issue by kklem0** [cubieplayer/Cubian#94]
Any plan for xf86-video-sunxifb?
Looks a lot faster.

http://www.youtube.com/watch?v=Vzmckw3fAQo

**Comment by kklem0** [comment]
G2D is not enabled yet.

**Comment by cubieplayer** [comment]
G2D and cedar is not available on A20 currently

**Comment by kklem0** [comment]
Hmmm... I obviously heard a different story from @ssvb .
Are we using https://github.com/linux-sunxi/linux-sunxi ?

**Comment by ssvb** [comment]
@clementhk G2D support can be enabled on A20, at least I have tested it with 3.3 kernel using some minor tweaks several months ago. Also G2D does not bring any really groundbreaking performance improvements, it is a nice optional feature.

**Comment by kklem0** [comment]
https://github.com/linux-sunxi/linux-sunxi/commits/stage/sunxi-3.4

**Comment by kklem0** [comment]
It looks ready in staging, I don't know their release circle so I don't know when it will get into sunxi-3.4 branch, but I'll do a test anyway. It will be cool if cubian can include xf86-video now.

**Comment by cubieplayer** [comment]
The driver is available now http://cubian.org/2013/09/29/install-lxde-with-opengles-accelerated-on-cubian/
