### ISSUE TITLE
我的cb2现在 使用 nand方式不能启动，请问有什么方式能解决？谢谢

### ISSUE THREAD

**Issue by bayuemu** [cubieplayer/Cubian#95]
我的cb2，前几天 nand还好这了，由于瞎折腾，nand的系统不能用，我就从新安装了cubie，使用cubian-nandinstall ，安装nand，但是去掉sd卡，cb就是启动不了，绿灯不亮，我也看nand有文件，都能查看，就是启动不了，请问大神有什么方式，能让nand再次启动，还是我的cb2坏了？
我给我同事安装的cubian，使用nandinstall 没有问题，我就有问题，是不是我板子那块快了导致的？？ 谢谢

**Comment by michalliu** [comment]
应该是启动参数不对，用sd卡启动系统,修改nanda里面的uEnv.txt，参见文章http://cn.cubian.org/2013/08/18/universal-and-separate-nandinstaller-is-released/

**Comment by bayuemu** [comment]
不行的，我试过了。不知道为什么，就是不行，我给我同事 装的方式 和给我装的方式一样，但是他的能启动，我的就是启动不了，我怀疑我的nand 是不是 有问题了 ？或者，是 我把板子的哪快 弄坏了，

**Comment by cubieplayer** [comment]
你有TTL线没有，如果有的话把屏幕上的输出信息贴一下，这样才能看出问题。
