### ISSUE TITLE
请问cubain有没有把watchdog的驱动编译到内核里？

### ISSUE THREAD

**Issue by wicastchen** [cubieplayer/Cubian#96]
RT
想用watchdog的功能做一个死机自动重启的功能，但是第一步要用modprobe 加载watchdog的硬件模块。

**Comment by michalliu** [comment]
不太懂这个模块，是需要这个驱动吗？

**Comment by wicastchen** [comment]
http://geekpi.cn/blog/2013/01/2173
第一步就是开启watchdog的硬件驱动模块

**Comment by wicastchen** [comment]
我在源代码里找到了这个watchdog的驱动，但是完全不会编译。。。
https://github.com/mmplayer/linux-sunxi/tree/stage/sunxi-3.4-a10/drivers/watchdog

**Comment by michalliu** [comment]
抽空编一下

**Comment by cubieplayer** [comment]
问一下这个必须要编译进内核吗？还是编成模块也可以？

**Comment by cubieplayer** [comment]
Hi, These modules are compiled now, you can try `cubian-update` to get it, Please re-open the issue if it's not working.
