### ISSUE TITLE
Mjpeg-Streamer Error Compile

### ISSUE THREAD

**Issue by chuprex** [cubieplayer/Cubian#97]
Has anyone already success to setup mjpg-streamer on cubian?? I need this to stream my camera. I've tried many times, but always Error.

root@Cubian:/usr/src/mjpg-streamer-r63# make all clean
make -C plugins/input_gspcav1 all
make[1]: Entering directory `/usr/src/mjpg-streamer-r63/plugins/input_gspcav1'
gcc -c -O2 -DLINUX -D_GNU_SOURCE -Wall -shared -fPIC -o spcav4l.lo spcav4l.c
In file included from spcav4l.c:25:0:
spcav4l.h:134:20: error: field ‘vmmap’ has incomplete type
spcav4l.h:135:26: error: field ‘videocap’ has incomplete type
spcav4l.h:137:20: error: field ‘videombuf’ has incomplete type
spcav4l.h:138:23: error: field ‘videopict’ has incomplete type
spcav4l.h:139:22: error: field ‘videowin’ has incomplete type
spcav4l.h:140:23: error: field ‘videochan’ has incomplete type
spcav4l.c: In function ‘convertframe’:
spcav4l.c:162:7: error: ‘VIDEO_PALETTE_YUV420P’ undeclared (first use in this function)
spcav4l.c:162:7: note: each undeclared identifier is reported only once for each function it appears in
spcav4l.c:165:7: error: ‘VIDEO_PALETTE_RGB24’ undeclared (first use in this function)
spcav4l.c:168:7: error: ‘VIDEO_PALETTE_RGB565’ undeclared (first use in this function)
spcav4l.c:171:7: error: ‘VIDEO_PALETTE_RGB32’ undeclared (first use in this function)
spcav4l.c: In function ‘v4lGrab’:
spcav4l.c:200:26: error: ‘VIDIOCSYNC’ undeclared (first use in this function)
spcav4l.c:236:27: error: ‘VIDIOCMCAPTURE’ undeclared (first use in this function)
spcav4l.c:192:10: warning: variable ‘temps’ set but not used [-Wunused-but-set-variable]
spcav4l.c: In function ‘GetVideoPict’:
spcav4l.c:294:22: error: ‘VIDIOCGPICT’ undeclared (first use in this function)
spcav4l.c: In function ‘SetVideoPict’:
spcav4l.c:310:22: error: ‘VIDIOCSPICT’ undeclared (first use in this function)
spcav4l.c: In function ‘init_v4l’:
spcav4l.c:335:22: error: ‘VIDIOCGCAP’ undeclared (first use in this function)
spcav4l.c:342:23: error: ‘VIDIOCGCHAN’ undeclared (first use in this function)
spcav4l.c:393:26: error: ‘VIDIOCGMBUF’ undeclared (first use in this function)
spcav4l.c:410:23: error: ‘VIDIOCMCAPTURE’ undeclared (first use in this function)
spcav4l.c:424:26: error: ‘VIDIOCGWIN’ undeclared (first use in this function)
spcav4l.c:428:26: error: ‘VIDIOCSWIN’ undeclared (first use in this function)
spcav4l.c: In function ‘probePalette’:
spcav4l.c:439:33: error: ‘VIDEO_PALETTE_YUV420P’ undeclared (first use in this function)
spcav4l.c:439:55: error: ‘VIDEO_PALETTE_RGB24’ undeclared (first use in this function)
spcav4l.c:439:75: error: ‘VIDEO_PALETTE_RGB565’ undeclared (first use in this function)
spcav4l.c:439:96: error: ‘VIDEO_PALETTE_RGB32’ undeclared (first use in this function)
spcav4l.c:440:23: error: storage size of ‘pict’ isn’t known
spcav4l.c:446:21: error: ‘VIDIOCGPICT’ undeclared (first use in this function)
spcav4l.c:446:2: warning: passing argument 2 of ‘ioctl’ makes integer from pointer without a cast [enabled by default]
/usr/include/arm-linux-gnueabihf/sys/ioctl.h:42:12: note: expected ‘long unsigned int’ but argument is of type ‘int *’
spcav4l.c:453:6: error: request for member ‘palette’ in something not a structure or union
spcav4l.c:453:2: warning: statement with no effect [-Wunused-value]
spcav4l.c:455:6: error: request for member ‘depth’ in something not a structure or union
spcav4l.c:455:2: warning: statement with no effect [-Wunused-value]
spcav4l.c:456:41: error: request for member ‘palette’ in something not a structure or union
spcav4l.c:456:54: error: request for member ‘depth’ in something not a structure or union
spcav4l.c:456:2: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘int *’ [-Wformat]
spcav4l.c:456:2: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘int *’ [-Wformat]
spcav4l.c:457:21: error: ‘VIDIOCSPICT’ undeclared (first use in this function)
spcav4l.c:457:2: warning: passing argument 2 of ‘ioctl’ makes integer from pointer without a cast [enabled by default]
/usr/include/arm-linux-gnueabihf/sys/ioctl.h:42:12: note: expected ‘long unsigned int’ but argument is of type ‘int *’
spcav4l.c:462:2: warning: passing argument 2 of ‘ioctl’ makes integer from pointer without a cast [enabled by default]
/usr/include/arm-linux-gnueabihf/sys/ioctl.h:42:12: note: expected ‘long unsigned int’ but argument is of type ‘int *’
spcav4l.c:467:10: error: request for member ‘palette’ in something not a structure or union
spcav4l.c:467:19: warning: comparison between pointer and integer [enabled by default]
spcav4l.c:440:23: warning: unused variable ‘pict’ [-Wunused-variable]
spcav4l.c: In function ‘probeSize’:
spcav4l.c:489:22: error: storage size of ‘win’ isn’t known
spcav4l.c:495:21: error: request for member ‘maxwidth’ in something not a structure or union
spcav4l.c:495:7: warning: assignment makes integer from pointer without a cast [enabled by default]
spcav4l.c:496:21: error: request for member ‘minwidth’ in something not a structure or union
spcav4l.c:496:7: warning: assignment makes integer from pointer without a cast [enabled by default]
spcav4l.c:497:21: error: request for member ‘maxheight’ in something not a structure or union
spcav4l.c:497:7: warning: assignment makes integer from pointer without a cast [enabled by default]
spcav4l.c:498:21: error: request for member ‘minheight’ in something not a structure or union
spcav4l.c:498:7: warning: assignment makes integer from pointer without a cast [enabled by default]
spcav4l.c:507:22: error: ‘VIDIOCGWIN’ undeclared (first use in this function)
spcav4l.c:507:3: warning: passing argument 2 of ‘ioctl’ makes integer from pointer without a cast [enabled by default]
/usr/include/arm-linux-gnueabihf/sys/ioctl.h:42:12: note: expected ‘long unsigned int’ but argument is of type ‘int *’
spcav4l.c:513:5: error: request for member ‘width’ in something not a structure or union
spcav4l.c:513:2: warning: statement with no effect [-Wunused-value]
spcav4l.c:514:5: error: request for member ‘height’ in something not a structure or union
spcav4l.c:514:2: warning: statement with no effect [-Wunused-value]
spcav4l.c:515:21: error: ‘VIDIOCSWIN’ undeclared (first use in this function)
spcav4l.c:515:2: warning: passing argument 2 of ‘ioctl’ makes integer from pointer without a cast [enabled by default]
/usr/include/arm-linux-gnueabihf/sys/ioctl.h:42:12: note: expected ‘long unsigned int’ but argument is of type ‘int *’
spcav4l.c:517:13: error: request for member ‘width’ in something not a structure or union
spcav4l.c:517:24: error: request for member ‘height’ in something not a structure or union
spcav4l.c:517:10: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘int *’ [-Wformat]
spcav4l.c:517:10: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘int *’ [-Wformat]
spcav4l.c:521:8: error: request for member ‘width’ in something not a structure or union
spcav4l.c:521:19: error: request for member ‘height’ in something not a structure or union
spcav4l.c:521:5: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘int *’ [-Wformat]
spcav4l.c:521:5: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘int *’ [-Wformat]
spcav4l.c:490:21: warning: variable ‘minh’ set but not used [-Wunused-but-set-variable]
spcav4l.c:490:16: warning: variable ‘maxh’ set but not used [-Wunused-but-set-variable]
spcav4l.c:489:22: warning: unused variable ‘win’ [-Wunused-variable]
spcav4l.c: In function ‘changeSize’:
spcav4l.c:542:31: error: request for member ‘palette’ in something not a structure or union
spcav4l.c:542:16: warning: assignment makes integer from pointer without a cast [enabled by default]
spcav4l.c:543:28: error: request for member ‘depth’ in something not a structure or union
spcav4l.c:543:13: warning: assignment makes integer from pointer without a cast [enabled by default]
spcav4l.c:552:16: error: request for member ‘height’ in something not a structure or union
spcav4l.c:552:7: warning: statement with no effect [-Wunused-value]
spcav4l.c:553:16: error: request for member ‘width’ in something not a structure or union
spcav4l.c:553:7: warning: statement with no effect [-Wunused-value]
spcav4l.c:554:16: error: request for member ‘format’ in something not a structure or union
spcav4l.c:554:7: warning: statement with no effect [-Wunused-value]
spcav4l.c:560:26: error: ‘VIDIOCGWIN’ undeclared (first use in this function)
spcav4l.c:560:7: warning: passing argument 2 of ‘ioctl’ makes integer from pointer without a cast [enabled by default]
/usr/include/arm-linux-gnueabihf/sys/ioctl.h:42:12: note: expected ‘long unsigned int’ but argument is of type ‘int *’
spcav4l.c:562:19: error: request for member ‘height’ in something not a structure or union
spcav4l.c:562:7: warning: statement with no effect [-Wunused-value]
spcav4l.c:563:19: error: request for member ‘width’ in something not a structure or union
spcav4l.c:563:7: warning: statement with no effect [-Wunused-value]
spcav4l.c:564:26: error: ‘VIDIOCSWIN’ undeclared (first use in this function)
spcav4l.c:564:7: warning: passing argument 2 of ‘ioctl’ makes integer from pointer without a cast [enabled by default]
/usr/include/arm-linux-gnueabihf/sys/ioctl.h:42:12: note: expected ‘long unsigned int’ but argument is of type ‘int *’
spcav4l.c:567:20: error: request for member ‘height’ in something not a structure or union
spcav4l.c:567:41: error: request for member ‘width’ in something not a structure or union
spcav4l.c:567:8: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘int *’ [-Wformat]
spcav4l.c:567:8: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘int *’ [-Wformat]
spcav4l.c:540:7: warning: variable ‘erreur’ set but not used [-Wunused-but-set-variable]
spcav4l.c: In function ‘convertpalette’:
spcav4l.c:654:7: error: ‘VIDEO_PALETTE_YUV420P’ undeclared (first use in this function)
spcav4l.c:657:7: error: ‘VIDEO_PALETTE_RGB24’ undeclared (first use in this function)
spcav4l.c:660:7: error: ‘VIDEO_PALETTE_RGB565’ undeclared (first use in this function)
spcav4l.c:663:7: error: ‘VIDEO_PALETTE_RGB32’ undeclared (first use in this function)
spcav4l.c: In function ‘paletteconvert’:
spcav4l.c:678:10: error: ‘VIDEO_PALETTE_YUV420P’ undeclared (first use in this function)
spcav4l.c:678:3: warning: return makes integer from pointer without a cast [enabled by default]
spcav4l.c:681:10: error: ‘VIDEO_PALETTE_RGB24’ undeclared (first use in this function)
spcav4l.c:681:3: warning: return makes integer from pointer without a cast [enabled by default]
spcav4l.c:684:10: error: ‘VIDEO_PALETTE_RGB565’ undeclared (first use in this function)
spcav4l.c:684:3: warning: return makes integer from pointer without a cast [enabled by default]
spcav4l.c:687:10: error: ‘VIDEO_PALETTE_RGB32’ undeclared (first use in this function)
spcav4l.c:687:3: warning: return makes integer from pointer without a cast [enabled by default]
spcav4l.c: In function ‘checkpalette’:
spcav4l.c:731:16: error: request for member ‘height’ in something not a structure or union
spcav4l.c:731:7: warning: statement with no effect [-Wunused-value]
spcav4l.c:732:16: error: request for member ‘width’ in something not a structure or union
spcav4l.c:732:7: warning: statement with no effect [-Wunused-value]
spcav4l.c:733:16: error: request for member ‘format’ in something not a structure or union
spcav4l.c:733:7: warning: statement with no effect [-Wunused-value]
spcav4l.c:735:13: error: request for member ‘frame’ in something not a structure or union
spcav4l.c:735:4: warning: statement with no effect [-Wunused-value]
spcav4l.c:736:23: error: ‘VIDIOCMCAPTURE’ undeclared (first use in this function)
spcav4l.c:736:4: warning: passing argument 2 of ‘ioctl’ makes integer from pointer without a cast [enabled by default]
/usr/include/arm-linux-gnueabihf/sys/ioctl.h:42:12: note: expected ‘long unsigned int’ but argument is of type ‘int *’
spcav4l.c: In function ‘GetDepth’:
spcav4l.c:888:10: error: ‘VIDEO_PALETTE_RAW’ undeclared (first use in this function)
spcav4l.c:893:10: error: ‘VIDEO_PALETTE_YUV420P’ undeclared (first use in this function)
spcav4l.c:898:10: error: ‘VIDEO_PALETTE_RGB565’ undeclared (first use in this function)
spcav4l.c:901:10: error: ‘VIDEO_PALETTE_RGB24’ undeclared (first use in this function)
spcav4l.c:904:10: error: ‘VIDEO_PALETTE_RGB32’ undeclared (first use in this function)
spcav4l.c: In function ‘SpcaGetBrightness’:
spcav4l.c:924:27: error: request for member ‘brightness’ in something not a structure or union
spcav4l.c:924:40: error: invalid operands to binary >> (have ‘int *’ and ‘int’)
spcav4l.c:924:3: warning: return makes integer from pointer without a cast [enabled by default]
spcav4l.c: In function ‘SpcaSetBrightness’:
spcav4l.c:930:18: error: request for member ‘brightness’ in something not a structure or union
spcav4l.c:930:3: warning: statement with no effect [-Wunused-value]
spcav4l.c: In function ‘SpcaGetContrast’:
spcav4l.c:945:27: error: request for member ‘contrast’ in something not a structure or union
spcav4l.c:945:38: error: invalid operands to binary >> (have ‘int *’ and ‘int’)
spcav4l.c:945:3: warning: return makes integer from pointer without a cast [enabled by default]
spcav4l.c: In function ‘SpcaSetContrast’:
spcav4l.c:951:18: error: request for member ‘contrast’ in something not a structure or union
spcav4l.c:951:3: warning: statement with no effect [-Wunused-value]
spcav4l.c: In function ‘SpcaGetColors’:
spcav4l.c:965:27: error: request for member ‘colour’ in something not a structure or union
spcav4l.c:965:36: error: invalid operands to binary >> (have ‘int *’ and ‘int’)
spcav4l.c:965:3: warning: return makes integer from pointer without a cast [enabled by default]
spcav4l.c: In function ‘SpcaSetColors’:
spcav4l.c:971:18: error: request for member ‘colour’ in something not a structure or union
spcav4l.c:971:3: warning: statement with no effect [-Wunused-value]
spcav4l.c: In function ‘upbright’:
spcav4l.c:982:26: error: request for member ‘brightness’ in something not a structure or union
spcav4l.c:982:9: warning: assignment makes integer from pointer without a cast [enabled by default]
spcav4l.c:985:17: error: request for member ‘brightness’ in something not a structure or union
spcav4l.c:985:2: warning: statement with no effect [-Wunused-value]
spcav4l.c: In function ‘downbright’:
spcav4l.c:998:26: error: request for member ‘brightness’ in something not a structure or union
spcav4l.c:998:9: warning: assignment makes integer from pointer without a cast [enabled by default]
spcav4l.c:1001:17: error: request for member ‘brightness’ in something not a structure or union
spcav4l.c:1001:2: warning: statement with no effect [-Wunused-value]
spcav4l.c: In function ‘upcontrast’:
spcav4l.c:1014:28: error: request for member ‘contrast’ in something not a structure or union
spcav4l.c:1014:11: warning: assignment makes integer from pointer without a cast [enabled by default]
spcav4l.c:1017:17: error: request for member ‘contrast’ in something not a structure or union
spcav4l.c:1017:2: warning: statement with no effect [-Wunused-value]
spcav4l.c: In function ‘downcontrast’:
spcav4l.c:1030:28: error: request for member ‘contrast’ in something not a structure or union
spcav4l.c:1030:11: warning: assignment makes integer from pointer without a cast [enabled by default]
spcav4l.c:1033:17: error: request for member ‘contrast’ in something not a structure or union
spcav4l.c:1033:2: warning: statement with no effect [-Wunused-value]
spcav4l.c: In function ‘spcaSetAutoExpo’:
spcav4l.c:1085:14: error: ‘BASE_VIDIOCPRIVATE’ undeclared (first use in this function)
spcav4l.c:1085:14: error: invalid operands to binary << (have ‘int *’ and ‘int’)
spcav4l.c:1085:14: error: invalid operands to binary | (have ‘unsigned int’ and ‘int *’)
spcav4l.c:1085:14: error: invalid operands to binary | (have ‘int *’ and ‘unsigned int’)
spcav4l.c:1085:14: warning: passing argument 2 of ‘ioctl’ makes integer from pointer without a cast [enabled by default]
/usr/include/arm-linux-gnueabihf/sys/ioctl.h:42:12: note: expected ‘long unsigned int’ but argument is of type ‘int *’
spcav4l.c: In function ‘spcaPrintParam’:
spcav4l.c:1093:14: error: ‘BASE_VIDIOCPRIVATE’ undeclared (first use in this function)
spcav4l.c:1093:14: error: invalid operands to binary << (have ‘int *’ and ‘int’)
spcav4l.c:1093:14: error: invalid operands to binary | (have ‘unsigned int’ and ‘int *’)
spcav4l.c:1093:14: error: invalid operands to binary | (have ‘int *’ and ‘unsigned int’)
spcav4l.c:1093:14: warning: passing argument 2 of ‘ioctl’ makes integer from pointer without a cast [enabled by default]
/usr/include/arm-linux-gnueabihf/sys/ioctl.h:42:12: note: expected ‘long unsigned int’ but argument is of type ‘int *’
spcav4l.c: In function ‘spcaSetTimeInterval’:
spcav4l.c:1105:14: error: ‘BASE_VIDIOCPRIVATE’ undeclared (first use in this function)
spcav4l.c:1105:14: error: invalid operands to binary << (have ‘int *’ and ‘int’)
spcav4l.c:1105:14: error: invalid operands to binary | (have ‘unsigned int’ and ‘int *’)
spcav4l.c:1105:14: error: invalid operands to binary | (have ‘int *’ and ‘unsigned int’)
spcav4l.c:1105:14: warning: passing argument 2 of ‘ioctl’ makes integer from pointer without a cast [enabled by default]
/usr/include/arm-linux-gnueabihf/sys/ioctl.h:42:12: note: expected ‘long unsigned int’ but argument is of type ‘int *’
spcav4l.c: In function ‘spcaSetQuality’:
spcav4l.c:1117:14: error: ‘BASE_VIDIOCPRIVATE’ undeclared (first use in this function)
spcav4l.c:1117:14: error: invalid operands to binary << (have ‘int *’ and ‘int’)
spcav4l.c:1117:14: error: invalid operands to binary | (have ‘unsigned int’ and ‘int *’)
spcav4l.c:1117:14: error: invalid operands to binary | (have ‘int *’ and ‘unsigned int’)
spcav4l.c:1117:14: warning: passing argument 2 of ‘ioctl’ makes integer from pointer without a cast [enabled by default]
/usr/include/arm-linux-gnueabihf/sys/ioctl.h:42:12: note: expected ‘long unsigned int’ but argument is of type ‘int *’
make[1]: *** [spcav4l.lo] Error 1
make[1]: Leaving directory`/usr/src/mjpg-streamer-r63/plugins/input_gspcav1'
make: **\* [input_gspcav1.so] Error 2

Help me Please.
 i use Cubieboard A20

**Comment by cubieplayer** [comment]
It seems a problem of Mjpeg-Streamer source code

**Comment by chuprex** [comment]
the problem is solved, i have some problem again with system hang on 2 camera with zoneminder application.

**Comment by a0s** [comment]
@chuprex , how you solve this problem?
My problem is

```
-- Build files have been written to: /home/cubie/mjpg-streamer/mjpg-streamer-experimental/plugins/input_raspicam/build
make -C plugins/input_raspicam/build
make[1]: Entering directory `/home/cubie/mjpg-streamer/mjpg-streamer-experimental/plugins/input_raspicam/build'
make[2]: Entering directory `/home/cubie/mjpg-streamer/mjpg-streamer-experimental/plugins/input_raspicam/build'
make[3]: Entering directory `/home/cubie/mjpg-streamer/mjpg-streamer-experimental/plugins/input_raspicam/build'
Scanning dependencies of target input_raspicam
make[3]: Leaving directory `/home/cubie/mjpg-streamer/mjpg-streamer-experimental/plugins/input_raspicam/build'
make[3]: Entering directory `/home/cubie/mjpg-streamer/mjpg-streamer-experimental/plugins/input_raspicam/build'
[100%] Building C object CMakeFiles/input_raspicam.dir/input_raspicam.c.o
/home/cubie/mjpg-streamer/mjpg-streamer-experimental/plugins/input_raspicam/input_raspicam.c:44:22: fatal error: bcm_host.h: No such file or directory
compilation terminated.
make[3]: *** [CMakeFiles/input_raspicam.dir/input_raspicam.c.o] Error 1
make[3]: Leaving directory `/home/cubie/mjpg-streamer/mjpg-streamer-experimental/plugins/input_raspicam/build'
make[2]: *** [CMakeFiles/input_raspicam.dir/all] Error 2
make[2]: Leaving directory `/home/cubie/mjpg-streamer/mjpg-streamer-experimental/plugins/input_raspicam/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/cubie/mjpg-streamer/mjpg-streamer-experimental/plugins/input_raspicam/build'
make: *** [input_raspicam.so] Error 2
```
