### ISSUE TITLE
Cubian-base-r2-arm-a20, "Packet corrupt" when SFTP to/from cb2

### ISSUE THREAD

**Issue by cubieplayer** [cubieplayer/Cubian#98]
Hello cubieplayer,

  I've noticed one problem with Cubian-base-r2-arm-a20 that I just installed. I get "packet corrupt" when transferring large files ~700MB using "sftp". I tried sending to cb2 (put) the file and also receiving it on cb2 (get). I know that there are a lot of things that can go wrong, but can someone try to transfer a large file (700MB or more) over SFTP on cb2 ? I get the problem after 200..300 MB were already transferred. No problems with the free space on the microSD.

I am on "Fedora 19" (with Gigabit Ethernet) and I am using just a simple cable to connect to cb2. They are connecting at 100 Mbit/s full-duplex from what I've noticed. Everything else seems to be OK regarding the network (I've installed "lxde" without problems - F19 provides the "Internet"). I will try FTP next.

Regards,
Ioan LUPU...

**Comment by gahpee** [comment]
SFTP works fine for me. I transferred a 700MB file from my debian server to my A20 which is running  Cubian-base-r2-arm-a20 without any problems. My server only has a 100Mb ethernet port - not sure if that makes a difference.

Regards
Greg

**Comment by cubieplayer** [comment]
Hi, Please take a look at http://cubian.org/2013/09/18/fix-random-crash/, does it help?

**Comment by michalliu** [comment]
lower clock rate sloved the problem
