### ISSUE TITLE
xf86-video driver

### ISSUE THREAD

**Issue by derekdhaas** [cubieplayer/Cubian#99]
I've compiled the xf86 driver for xorg

You will need to install the xorg server yourself (I haven't included the dependencies for xorg-server).
aptitude install xserver-xorg-video-fbdev xserver-xorg-input-evdev xinit

You might want to include them into your distro:
http://test.directcode.com/cubieboard2/

G2D isn't compiled yet, so I haven't included the acceleration.

Working xorg conf:

```
Section "Device"
        Identifier "sunxifb-Fbdev"
        #Driver "fbdev"
        #Driver  "mali"
        Driver "sunxifb"
        Option  "fbdev"                 "/dev/fb0"
        Option  "DRI2"                  "true"
        # mali only
        #Option  "DRI2_PAGE_FLIP"        "true"
        #Option  "DRI2_WAIT_VSYNC"       "false"
        #Option  "UMP_CACHED"            "true"
        #Option  "UMP_LOCK"              "true"
        # sunxifb only
        Option  "DRI2HWOverlay"         "true"
        #Option  "AccelMethod"          "G2D"
EndSection

Section "Screen"
        Identifier   "Sunxifb-Screen"
        Device       "sunxifb-Fbdev"
        DefaultDepth  24
EndSection

Section "DRI"
        Mode 0666
EndSection
```

**Comment by derekdhaas** [comment]
Hmm my description wasn't that clear, but I've created .deb files which you (cubieplayer) can include in your cubian packages. I haven't added a Xorg.conf file (you will have to add it yourself).

Everyone else can also install it using dpkg -i <the 3 packages>

I also fixed the link (was returning a 404 page)

**Comment by michalliu** [comment]
Nice work, where i can download it?

**Comment by derekdhaas** [comment]
http://test.directcode.com/cubieboard2/

**Comment by chuprex** [comment]
whether it has been tested and works well ??

**Comment by derekdhaas** [comment]
It's working as good as on the A10, so no G2D acceleration because it isn't available in the kernel. When it is, it will boost the performance 1.5 times. (I have seen a patch floating around, also discussed in another topic here). Just grab the .deb files, install them and adjust your xorg config file in /usr/share/X11/xorg.conf.d/. Please do not forget to install the above mentioned packages from the debian distro to install X11/xorg correctly.

**Comment by deutrino** [comment]
Is this intended to be in a Cubian A20 release soon?  I would like to know if I should do this myself or just wait for updates if it'll only be a few weeks.

**Comment by mmplayer** [comment]
xf86 driver is available now http://cubian.org/2013/09/29/install-lxde-with-opengles-accelerated-on-cubian/
